### ISSUE TITLE
Vardict table sometimes has lines with different number of columns and missing values

### ISSUE THREAD

**Issue by BilyanaStoilova** [bcbio/bcbio-nextgen#2563] opened 2018-11-05 17:52 UTC
Hi,
I posted this issue on the Vardict GitHub page but got no reply, so apologies for duplicating it here.
I am trying to run Vardict on WES data from paired tumour and germline sample. I used BWA mem for alignment. However, when I pipe the Vardict code I get in ~50% of the cases an empty vcf file as an output. Here is my script:
vardict -G Homo_sapiens_assembly38.fasta -f 0.05 -N CM0403_1-tumour -b "CM0403_1-tumour.bam|CM0403_1-control.bam" -c 1 -S 2 -E 3 -g 4 S07604514_Padded_full_hg38.bed | testsomatic.R | var2vcf_paired.pl -N "CM0403_1-tumour|CM0403_1-control" -f 0.05 > vardict_CM0403_1.vcf
Then I tried running the three different scripts of the code separately so that I try to pinpoint the problem. testsomatic.R produced the empty file. What I realised is that some of the lines in the text file produced by vardict which is the input for testsomatic.R have a different number of columns - it seems as if these lines went out of sync. You can see this in the attached file lines 143, 368, 478. These are always lines with StrongLOH filter, however not all lines with StrongLOH filter have this issue. Furthermore, I get for other lines in the file missing values (1-5 per file, see lines 1,2 and 6 in the second attached file), which also crushes the code. Could you please help me figure out what is the problem and advice me how to solve it - for the moment I did grep -v "StrongLOH" and also grep-out the lines with the missing values but in this way I also exclude some lines which don't have the problem, or lines with variants which might be important. Once I omit these lines vardict runs from the beginning till the end without any issues. The most confusing thing is that this happens only in half of my files and the other half are completely fine.
And second question: do you advice to run vardict on bam files with or without GATK BQSR (base quality score recalibration)? I have run it for the moment on bam files without BQSR.
Thank you very much
[vardict_500l.stdout.txt](https://github.com/bcbio/bcbio-nextgen/files/2549895/vardict_500l.stdout.txt)
[vardict.stdout_v2.txt](https://github.com/bcbio/bcbio-nextgen/files/2549920/vardict.stdout_v2.txt)

**Comment by chapmanb** [comment] 2018-11-06 19:46
Bilyana;
Sorry about this issue and thanks for the report. I tried to pin Polina into AstraZeneca-NGS/VarDict#72 because I know there is on going work on these problems. My two practical suggestions are:

- Use VarDictJava, rather than VarDict, as that's faster and more production ready code.
- Work around the issue by restricting to output with a correct number of columns using `awk 'NF>=48'`. This is the approach we use in bcbio currently to avoid any of these edge cases:

https://github.com/bcbio/bcbio-nextgen/blob/ad3da20ac33e7a47eb20550ee86428e30a839cdc/bcbio/variation/vardict.py#L334

Hope these help you get your analysis finished and thanks for any help you can provide on reproducing the issue.

**Comment by roryk** [comment] 2019-08-10 15:59
Thanks, VarDict has a bunch of fixes for stuff like this since the issue was open, so closing it as we haven't had reports of other issues and this is likely to be solved.

**Closed by roryk** 2019-08-10 15:59 UTC
