### ISSUE TITLE
Update breaks itself (?)

### ISSUE THREAD

**Issue by lbeltrame** [bcbio/bcbio-nextgen#2889] opened 2019-07-25 08:44 UTC
```
The following packages will be REMOVED:

  argcomplete-1.9.4-py36_1000
  argh-0.26.2-py36_1001
  arrow-0.14.2-py36_0
  backcall-0.1.0-py_0
  beautifulsoup4-4.8.0-py36_0
  bioblend-0.12.0-py_0
  bismark-0.22.1-0
  boto-2.49.0-py_0
  coverage-4.5.3-py36h14c3975_0
  cython-0.29.12-py36he1b5a44_0
  dnapi-1.1-py_3
  fadapa-0.3.1-py_1
  gffutils-0.9-py_1
  hisat2-2.1.0-py36h2d50403_1
  ipykernel-5.1.1-py36h5ca1d4c_0
  ipyparallel-6.2.4-py36_0
  ipython-7.6.1-py36h5ca1d4c_0
  ipython-cluster-helper-0.6.3-py_0
  jedi-0.14.1-py36_0
  jupyter_client-5.3.1-py_0
  libsodium-1.0.17-h516909a_0
  logbook-1.4.3-py36h14c3975_0
  mock-3.0.5-py36_0
  msgpack-python-0.6.1-py36h6bb024c_0
  netifaces-0.10.4-py36_1
  parso-0.5.1-py_0
  pexpect-4.7.0-py36_0
  pickleshare-0.7.5-py36_1000
  prompt_toolkit-2.0.9-py_0
  ptyprocess-0.6.0-py_1001
  pycrypto-2.6.1-py36h14c3975_1002
  pygments-2.4.2-py_0
  pytest-cov-2.7.1-py_0
  pytest-mock-1.10.4-py36_0
  pyzmq-18.0.2-py36h1768529_2
  requests-toolbelt-0.5.0-py36_0
  seaborn-0.9.0-py_1
  soupsieve-1.9.2-py36_0
  tabulate-0.8.3-py_0
  toolz-0.10.0-py_0
  yamllint-1.2.1-py36_0
  zeromq-4.3.2-he1b5a44_2
```

This breaks bcbio completely since stuff like `zeromq` and `toolz` are essential. I've tried to keep the bcbio environment mostly clean from extra stuff (basically just `Rmpi` is an extra), but I can't figure out what is prompting such a change (anaconda is way weaker than proper package managers on that regard).

**Comment by lbeltrame** [comment] 2019-07-25 09:24
OTOH, might it be related to reportlab, which I installed off conda-forge?

**Comment by roryk** [comment] 2019-07-25 23:40
Thanks, I'm seeing issues with installs and upgrades too, I think they are probably related. This is going to be a little diary about where I'm at figuring it out. The reportlab issue should be fixed from https://github.com/ContinuumIO/anaconda-issues/issues/11109, but now on an upgrade from a fresh install there is an issue with openlibblas:

```
534% [rdk4@compute-e-16-236:~/tmp] 130 $ /home/rdk4/local/test/anaconda/bin/bcbio_nextgen.py upgrade --tooldir=/home/rdk4/local/test/tools
Traceback (most recent call last):
  File "/home/rdk4/local/test/anaconda/bin/bcbio_nextgen.py", line 39, in <module>
    from bcbio.distributed import runfn, clargs
  File "/home/rdk4/local/test/anaconda/lib/python3.6/site-packages/bcbio/distributed/runfn.py", line 20, in <module>
    from bcbio.distributed import multitasks
  File "/home/rdk4/local/test/anaconda/lib/python3.6/site-packages/bcbio/distributed/multitasks.py", line 5, in <module>
    from bcbio.srna import sample as srna
  File "/home/rdk4/local/test/anaconda/lib/python3.6/site-packages/bcbio/srna/sample.py", line 26, in <module>
    from bcbio.srna.umis import umi_transform
  File "/home/rdk4/local/test/anaconda/lib/python3.6/site-packages/bcbio/srna/umis.py", line 18, in <module>
    from bcbio.rnaseq.umi import get_transform_file, \
  File "/home/rdk4/local/test/anaconda/lib/python3.6/site-packages/bcbio/rnaseq/umi.py", line 8, in <module>
    import scipy.io
  File "/home/rdk4/local/test/anaconda/lib/python3.6/site-packages/scipy/io/__init__.py", line 97, in <module>
    from .matlab import loadmat, savemat, whosmat, byteordercodes
  File "/home/rdk4/local/test/anaconda/lib/python3.6/site-packages/scipy/io/matlab/__init__.py", line 13, in <module>
    from .mio import loadmat, savemat, whosmat
  File "/home/rdk4/local/test/anaconda/lib/python3.6/site-packages/scipy/io/matlab/mio.py", line 12, in <module>
    from .miobase import get_matfile_version, docfiller
  File "/home/rdk4/local/test/anaconda/lib/python3.6/site-packages/scipy/io/matlab/miobase.py", line 22, in <module>
    from scipy.misc import doccer
  File "/home/rdk4/local/test/anaconda/lib/python3.6/site-packages/scipy/misc/__init__.py", line 68, in <module>
    from scipy.interpolate._pade import pade as _pade
  File "/home/rdk4/local/test/anaconda/lib/python3.6/site-packages/scipy/interpolate/__init__.py", line 175, in <module>
    from .interpolate import *
  File "/home/rdk4/local/test/anaconda/lib/python3.6/site-packages/scipy/interpolate/interpolate.py", line 20, in <module>
    import scipy.linalg
  File "/home/rdk4/local/test/anaconda/lib/python3.6/site-packages/scipy/linalg/__init__.py", line 190, in <module>
    from .misc import *
  File "/home/rdk4/local/test/anaconda/lib/python3.6/site-packages/scipy/linalg/misc.py", line 5, in <module>
    from .blas import get_blas_funcs
  File "/home/rdk4/local/test/anaconda/lib/python3.6/site-packages/scipy/linalg/blas.py", line 214, in <module>
    from scipy.linalg import _fblas
ImportError: libopenblas.so.0: cannot open shared object file: No such file or directory
```

I think there is some problems when including the `defaults` channel and including `conda-forge`. If you have no defaults in your `.condarc`then there are some packages that don't get picked up, so it is necessary for it to be there. But if you include it, there is a mixture of stuff from `conda-forge` and stuff from `pkgs/main` getting installed, which seems to be breaking some things. I've been trying to figure out a workaround all day but I'm stuck at the moment.

If i install `libopenblas` I can get it to install but some other packages are missing. I think the issue with this is that the scipy version that is being installed may be old:

```
scipy                     1.1.0           py36_blas_openblash7943236_201  [blas_openblas]  conda-forge
```

Forcing install of `scipy 1.3.0` fixes it. But some other things are broken, will update with those in a bit.

**Comment by roryk** [comment] 2019-07-26 18:35
Ok, I fixed the scipy problem so that shouldn't come up anymore. There are some other problems that are coming up on a fresh install plus an upgrade. The next one is that the package `bioconductor-vsn` is not correct; when you load it in R it gives this message:

```
Error: package or namespace load failed for ‘vsn’:
 package ‘vsn’ was installed by an R version with different internals; it needs to be reinstalled for use with this R version
```

Working on that one now.

**Comment by roryk** [comment] 2019-07-26 18:37
I'm trying to get the install + upgrade to work correctly so at least we can fall back on nuking installs that got into a bad state and reinstalling if all else fails.

**Closed** 2019-07-29 04:45 UTC

**Comment by chapmanb** [comment] 2019-07-29 04:47
Thanks much for these reports and sorry about the install problems. Rory and I have been tag teaming on this and the latest CloudBioLinux has three fixes that hopefully will resolve the problems:                                          
- Not include preseq for now, which seems to trigger issues between openblas, libopenblas, libblas and libblasc (so many blas libraries):
```                                                                                                                                                                                                                                          The environment is inconsistent, please check the package plan carefully
The following packages are causing the inconsistency:

  - conda-forge/linux-64::blas==1.1=openblas
  - conda-forge/linux-64::gsl==2.2.1=blas_openblash47a8a8e_5
  - conda-forge/linux-64::libopenblas==0.3.6=h6e990d7_5
  - bioconda/linux-64::preseq==2.0.3=h26b358d_2
done

ERROR conda.core.link:_execute(656): An error occurred while installing package 'conda-forge::libblas-3.8.0-6_h6e990d7_netlib'.
Rolling back transaction: done
                                                                                                                                                                                                                                             [Errno 17] File exists: 'libblas.so.3.8.0' -> '/home/chapmanb/tmp/bcbio/install/base/anaconda/lib/libblas.so'
```
- Move bismark to the python2 environment. It pulls in hisat2, which is python2 only, and results in removals that can remove some standard required packages (like toolz and logbook) on upgrades.

- Pin to python 3.6 rather than just python 3, which avoids churn between python 3.6 and python 3.7. This back and forth seems to result in the loss of standard packages required by conda and bcbio. It's a bit tricky to recover from these as they appear to be installed, but are missing the libraries.                                                                                                                                                                             
The recommendation for the best way to fix a busted system is to remove your current anaconda directory and re-install the tools in place:
```                                                                                                                                                                                                                                          rm -rf tmpbcbio-install                                                                                                                                                                                                                      mv /path/to/bcbio/anaconda /path/to/bcbio/anaconda.broken
wget https://raw.githubusercontent.com/bcbio/bcbio-nextgen/master/scripts/bcbio_nextgen_install.py
python bcbio_nextgen_install.py /path/to/bcbio --tooldir=/path/to/tools                                                                                                                                                                      ```
which hopefully will give a more stable install.

Sorry about all this conda churn and hope this resolves the issues.

**Comment by lbeltrame** [comment] 2019-08-30 10:10
FTR, it broke again. The newest update just removed `toolz` and a bunch of other necessary packages.

**Comment by chapmanb** [comment] 2019-08-30 18:26
Luca -- sorry about the continued problems with upgrade. Do you have any logs or other details you can share to help us try to reproduce what you're seeing to help fix?

**Comment by lbeltrame** [comment] 2019-09-02 08:36
Was "hisat2" supposed to get removed from the default environment? IIRC yes, and I assume (perhaps incorrectly) that was the cause of the removal of everything else. For now I have reinstalled the minimal packages needed with `bcbio_conda` without actually incurring in dependency problems.

**Comment by chapmanb** [comment] 2019-09-03 17:48
Luca -- that's right, both bismark and hisat2 should be in the python2 environment, not in the main environment. I'm glad a re-install fixed it; perhaps there were some conflicts from an older install -- sometimes conda is not too great about upgrading like this. Let us know if you run into other issues and thanks again for the help debugging.
