### ISSUE TITLE
FR:Adding QualityByDepth (QD) to VCF files produces by Freebayes

### ISSUE THREAD

**Issue by NeillGibson** [bcbio/bcbio-nextgen#1410] opened 2016-05-30 10:30 UTC
Hi, 

Would it be possible to add a step / script to the freebayes variant calling pipe to calculate and set the QualityByDepth value for each variant.
https://github.com/chapmanb/bcbio-nextgen/blob/master/bcbio/variation/freebayes.py#L125

We use the QD value as quick single value  indication of  _Variant Confidence / depth normalized variant quality_ . 

I currently have a small PyVCF script to calculate this downstream but putting this in the variant calling pipe ensures that the QD value  is calculated on the full VCF file with all samples. 
(calculating it downstream on a VCF with some samples removed outputs very wrong/high QD values)

Below is a PyVCF implementation to calculate the QualityByDepth value for a VCF record. 
It is based on the GATK QualityByDepth documentation
https://www.broadinstitute.org/gatk/guide/tooldocs/org_broadinstitute_gatk_tools_walkers_annotator_QualByDepth.php
http://gatkforums.broadinstitute.org/gatk/discussion/comment/18866

Instead of using the GATK AD values is uses the corresponding Freebayes RO+ AO values.
Instead of setting a soft limit at QD 35 it uses a hard limit at QD 35. 

I did not implement a normalization for INDEL lenght. 
Without any hard or soft limit I get a QD distribution for SNP variants up to mostly 35 so I think the implementation is correct.

Would it be possible to add this as a PyVCF script in the Freebayes variant calling pipe?

Thank you. 

```
def calculate_quality_by_depth(record):
    """ Return the quality of depth for a VCF variant record
     Method is based on QD  formula from
     https://www.broadinstitute.org/gatk/gatkdocs/org_broadinstitute_gatk_tools_walkers_annotator_QualByDepth.php
     http://gatkforums.broadinstitute.org/discussion/comment/18866
     If there are no samples, or alternative genotypes in the samples, 0 is returned as quality of depth"""

    # Set the default quality by depth to zero.
    quality_by_depth = 0
    sum_ro_in_var_genotypes = 0
    sum_ao_in_var_genotypes = 0

    if record.QUAL != 0:

        for sample in record.samples:
            if sample is not None and sample.is_variant:

                sum_ro_in_var_genotypes = sum_ro_in_var_genotypes + sample['RO']

                # Check if there are multiple alternate alleles, by checking if the AO object is a list
                if isinstance(sample['AO'], list):
                    # If so take the sum of the reads that support any of the alternate allele
                    sum_ao_in_var_genotypes = sum_ao_in_var_genotypes + sum(
                        sample['AO'])
                # Else just take the read count for the single alternate allele
                else:
                    sum_ao_in_var_genotypes = sum_ao_in_var_genotypes + sample[
                        'AO']

        sum_depth_in_var_samples = sum_ro_in_var_genotypes + sum_ao_in_var_genotypes

        # somehow it is possibly to have very low quality variants without  any RO or AO depth
        # in this case the quality by depth is set to zero
        if sum_depth_in_var_samples == 0:
            quality_by_depth = 0
        # otherwise the quality by depth is:
        # the quality divided by the depth in the samples that have a variant genotype
        else:
            quality_by_depth = record.QUAL / sum_depth_in_var_samples

            # enforce a hard limit of 35 as advised by GATK
            if quality_by_depth > 35:
                quality_by_depth = 35


    # Format the QD as a string with 2 decimal places
    return str("%.2f" % quality_by_depth)
```

**Comment by NeillGibson** [comment] 2016-05-31 11:58
Freebayes is switching to also use the standard AD fields (instead of RO and AO) so maybe it makes sense to wait for this. 
https://github.com/ekg/freebayes/issues/270

Maybe this would also enable usage of an already existing QualityByDepth annotation tool. 
For all variant callers.

**Comment by chapmanb** [comment] 2016-06-01 13:01
Neill;
Thanks for looking at this -- having QualityByDepth annotations would be useful to have for easier downstream filtering. Practically you could filter/assess on this using bcftools expressions right now (http://samtools.github.io/bcftools/bcftools.html#expressions) but have a single number and standard annotation would definitely be helpful.

My only concern is that PyVCF can be slow so I worry about having this applied globally. If there are other general approaches where this has already been implemented we could apply those. We could also approach the Broad folks about including the annotation parts in the MIT licensed framework. I'm not sure how this will work with the upcoming GATK 4 releases. Definitely happy to consider and work on it either way.

**Comment by NeillGibson** [comment] 2016-06-06 08:40
Hi Brad. Good point about the speed of PyVCF. Makes no sense to risk slowing variant calling pipe down.  

Maybe the best thing is indeed to ask the Broad folks if they would be willing to move QualityByDepth annotation to the MIT licensed framework. QD concept / formula seems like a pretty generic thing.  Do you known who / how to ask them?

Or maybe ask if the annotation could be implemented in VCFLIB after freebayes changes to AD fields? The formula is straight forward. 

For the time being I'll build in a check that we are running the annotation on a full VCF file (no bcftools view -S / -s  command used. )

**Comment by roryk** [comment] 2019-08-10 17:47
Thanks, closing this as the issue is really old and we haven't had talk about it for a long time. Please re-open if this is still useful. Thanks!

**Closed by roryk** 2019-08-10 17:47 UTC
