### ISSUE TITLE
TitanCNA fail on some samples

### ISSUE THREAD

**Issue by apastore** [bcbio/bcbio-nextgen#2304] opened 2018-03-05 00:38 UTC
I was testing TitanCNA on some exome and it seems to fail in some case. I do not know yet if the problem is the quality of the samples or what or if there are some case where the optimal Cluster number can not be inferred. I was wondering if such samples could be skipped instead of stoping the run. 

Thanks!

[2018-03-04T23:05Z] lt16: tabix index TS-108T_cluster02.segs.vcf.gz
2018-03-04 18:05:52.300 [IPClusterStop] Using existing profile dir: u'/lila/data/abdelwao-lab/pastorea/Project/Project_06301_L/Project_06301_L/work/log/ipython'
2018-03-04 18:05:52.389 [IPClusterStop] Stopping cluster [pid=52024] with [signal=2]
2018-03-04 18:05:53.586 [IPClusterStop] Using existing profile dir: u'/lila/data/abdelwao-lab/pastorea/Project/Project_06301_L/Project_06301_L/work/log/ipython'
2018-03-04 18:05:53.592 [IPClusterStop] Stopping cluster [pid=52024] with [signal=2]
Traceback (most recent call last):
  File "/lila/home/pastore/data/bcbio_tool/bin/bcbio_nextgen.py", line 241, in <module>
    main(**kwargs)
  File "/lila/home/pastore/data/bcbio_tool/bin/bcbio_nextgen.py", line 46, in main
    run_main(**kwargs)
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 51, in run_main
    fc_dir, run_info_yaml)
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 87, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 174, in variant2pipeline
    samples = structural.run(samples, run_parallel, "standard")
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/__init__.py", line 177, in run
    for xs in to_process.values()))
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipython.py", line 137, in run
    for data in view.map_sync(fn, items, track=False):
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/ipyparallel/client/view.py", line 342, in map_sync
    return self.map(f,*sequences,**kwargs)
  File "<decorator-gen-137>", line 2, in map
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/ipyparallel/client/view.py", line 50, in sync_results
    ret = f(self, *args, **kwargs)
  File "<decorator-gen-136>", line 2, in map
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/ipyparallel/client/view.py", line 35, in save_ids
    ret = f(self, *args, **kwargs)
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/ipyparallel/client/view.py", line 1109, in map
    return pf.map(*sequences)
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/ipyparallel/client/remotefunction.py", line 285, in map
    return self(*sequences, __ipp_mapping=True)
  File "<decorator-gen-119>", line 2, in __call__
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/ipyparallel/client/remotefunction.py", line 76, in sync_view_results
    return f(self, *args, **kwargs)
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/ipyparallel/client/remotefunction.py", line 271, in __call__
    return r.get()
  File "/home/pastore/data/bcbio/anaconda/lib/python2.7/site-packages/ipyparallel/client/asyncresult.py", line 167, in get
    raise self.exception()
ipyparallel.error.CompositeError: one or more exceptions from call to method: detect_sv
[23:apply]: CalledProcessError: Command 'set -o pipefail; titanCNA_selectSolution.R --ploidyRun2=/lila/data/abdelwao-lab/pastorea/Project/Project_06301_L/Project_06301_L/work/structural/TS-109T/titancna/run_ploidy2 --ploidyRun3=/lila/data/abdelwao-lab/pastorea/Project/Project_06301_L/Project_06301_L/work/structural/TS-109T/titancna/run_ploidy3 --ploidyRun4=/lila/data/abdelwao-lab/pastorea/Project/Project_06301_L/Project_06301_L/work/structural/TS-109T/titancna/run_ploidy4 --outFile=/scratch/pastore/tmp3Mh1Ik/optimalClusters.txt
$ploidyRun2
[1] "/lila/data/abdelwao-lab/pastorea/Project/Project_06301_L/Project_06301_L/work/structural/TS-109T/titancna/run_ploidy2"
$ploidyRun3
[1] "/lila/data/abdelwao-lab/pastorea/Project/Project_06301_L/Project_06301_L/work/structural/TS-109T/titancna/run_ploidy3"
$ploidyRun4
[1] "/lila/data/abdelwao-lab/pastorea/Project/Project_06301_L/Project_06301_L/work/structural/TS-109T/titancna/run_ploidy4"
$threshold
[1] 0.05
$outFile
[1] "/scratch/pastore/tmp3Mh1Ik/optimalClusters.txt"
$help
[1] FALSE
Error in data.frame(..., check.names = FALSE) : 
  arguments imply differing number of rows: 1, 2, 3
Calls: getParamAllClusters -> cbind -> cbind -> data.frame
Execution halted
' returned non-zero exit status 1
[20:apply]: CalledProcessError: Command 'set -o pipefail; titanCNA_selectSolution.R --ploidyRun2=/lila/data/abdelwao-lab/pastorea/Project/Project_06301_L/Project_06301_L/work/structural/TS-106T/titancna/run_ploidy2 --ploidyRun3=/lila/data/abdelwao-lab/pastorea/Project/Project_06301_L/Project_06301_L/work/structural/TS-106T/titancna/run_ploidy3 --ploidyRun4=/lila/data/abdelwao-lab/pastorea/Project/Project_06301_L/Project_06301_L/work/structural/TS-106T/titancna/run_ploidy4 --outFile=/scratch/pastore/tmpgMQULT/optimalClusters.txt
$ploidyRun2
[1] "/lila/data/abdelwao-lab/pastorea/Project/Project_06301_L/Project_06301_L/work/structural/TS-106T/titancna/run_ploidy2"
$ploidyRun3
[1] "/lila/data/abdelwao-lab/pastorea/Project/Project_06301_L/Project_06301_L/work/structural/TS-106T/titancna/run_ploidy3"
$ploidyRun4
[1] "/lila/data/abdelwao-lab/pastorea/Project/Project_06301_L/Project_06301_L/work/structural/TS-106T/titancna/run_ploidy4"
$threshold
[1] 0.05
$outFile
[1] "/scratch/pastore/tmpgMQULT/optimalClusters.txt"
$help
[1] FALSE
Error in data.frame(..., check.names = FALSE) : 
  arguments imply differing number of rows: 1, 0, 3
Calls: getParamAllClusters -> cbind -> cbind -> data.frame
Execution halted
' returned non-zero exit status 1

**Comment by chapmanb** [comment] 2018-03-12 00:38
Thanks much for the report and sorry about the delay in fixing this. The way we've tried to work with TitanCNA failures is to look at the input file of variants:
```
work/structural/TS-109T/titancna/*-prep.csv
```
to determine if we should proceed:

https://github.com/bcbio/bcbio-nextgen/blob/1514961ded3f67b0f408d0b9c4e06ec064186585/bcbio/structural/titancna.py#L67

This avoids needing to try and catch confusing R errors like this and make sense of them. From your run, would we be able to guess we're going to fail by having a low number of variants in this file? If so, we could adjust the checking parameters to correctly skip here. Thanks much for the help coming up with a general solution.

**Comment by apastore** [comment] 2018-03-23 22:32
Hi Brad, I am running in this issues again. In this case the sample have good GC ( 100X Coverage, 200M reads), about 900 Somatic variants called by vardict, and  if a look a the Probably gremlin variants (grep -vP "LowAlleleDepth|LikelySomatic|StrongSomatic") I get 275706 variants (all with FILTER REJECT)

Let me know If I you need more informations,

Thanks a lot!

**Comment by chapmanb** [comment] 2018-03-23 23:45
Sorry about the continued problems. Are you able to share the prepared inputs from the TitanCNA work directory so we can try to reproduce? Unfortunately we don't have a good way to diagnose or fix with only a high level description of the inputs. It sounds like this is a good sample from your description but we're missing something that's making Titan unable to process. Thanks for the help debugging.

**Comment by apastore** [comment] 2018-03-24 00:15
Sure ! Thanks a lot for your help!
Let  me know if you have issues to get the files.

**Comment by roryk** [comment] 2019-08-10 15:37
Thanks, closing since there hasn't been any action and there is a fix that should catch it in place. Please re-open if you're still having this problem.

**Closed by roryk** 2019-08-10 15:37 UTC
