### ISSUE TITLE
Use Warning instead of Exception at data upload ?

### ISSUE THREAD

**Issue by biocyberman** [bcbio/bcbio-nextgen#2122] opened 2017-10-24 10:03 UTC
The following exception was thrown because `/proj11/work/structural/Son1/cnvkit/raw/Son1-sort-recal-mybatch1.cnr` does not exist (on why it does not exist, I don't know yet).

```
[2017-10-24T08:52Z] [INFO   ]         multiqc : MultiQC complete
Traceback (most recent call last):
  File "/bcbio/bin/bcbio_nextgen.py", line 234, in <module>
    main(**kwargs)
  File "/bcbio/bin/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 42, in run_main
    fc_dir, run_info_yaml)
  File "/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 86, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 182, in variant2pipeline
    samples = qcsummary.generate_parallel(samples, run_parallel)
  File "/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/qcsummary.py", line 38, in generate_parallel
    samples = run_parallel("multiqc_summary", [samples])
  File "/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1)(joblib.delayed(fn)(x) for x in items):
  File "/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 804, in __call__
    while self.dispatch_one_batch(iterator):
  File "/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 662, in dispatch_one_batch
    self._dispatch(tasks)
  File "/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 570, in _dispatch
    job = ImmediateComputeBatch(batch)
  File "/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 183, in __init__
    self.results = batch()
  File "/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 72, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/bcbio/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 50, in wrapper
    return apply(f, *args, **kwargs)
  File "/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 203, in multiqc_summary
    return multiqc.summary(*args)
  File "/bcbio/anaconda/lib/python2.7/site-packages/bcbio/qc/multiqc.py", line 79, in summary
    file_list_final = _save_uploaded_file_list(samples, file_list, out_dir)
  File "/bcbio/anaconda/lib/python2.7/site-packages/bcbio/qc/multiqc.py", line 91, in _save_uploaded_file_list
    upload_path_mapping.update(get_all_upload_paths_from_sample(sample))
  File "/bcbio/anaconda/lib/python2.7/site-packages/bcbio/upload/__init__.py", line 47, in get_all_upload_paths_from_sample
    for finfo in _get_files(sample):
  File "/bcbio/anaconda/lib/python2.7/site-packages/bcbio/upload/__init__.py", line 62, in _get_files
    return _get_files_variantcall(sample)
  File "/bcbio/anaconda/lib/python2.7/site-packages/bcbio/upload/__init__.py", line 156, in _get_files_variantcall
    return _add_meta(out, sample)
  File "/bcbio/anaconda/lib/python2.7/site-packages/bcbio/upload/__init__.py", line 127, in _add_meta
    raise ValueError("Unexpected path for upload: %s" % x)
ValueError: Unexpected path for upload: {'sample': 'mybatch1', 'path': '/proj11/work/structural/Son1/cnvkit/raw/Son1-sort-recal-mybatch1.cnr', 'ext': 'cnvkit', 'type': 'cnr', 'variantcaller': 'cnvkit'}
```
I changed this line: https://github.com/chapmanb/bcbio-nextgen/blob/master/bcbio/upload/__init__.py#L127 
From:
`raise ValueError("Unexpected path for upload: %s" % x)`
To:

```
# This needs importing of logger from bcbio.log on the header.
logger.warning("Unexpected path for upload: %s" % x)   
continue      
```     
Would this be the better way? I am not sure about this so I did not send a PR :)

**Comment by chapmanb** [comment] 2017-10-24 13:47
Vang;
In general, we don't use warnings in bcbio as they're easily ignored and can lead to missing underlying problems. For this case it would be best to debug why the CNVkit output is missing and determine how best to handle that case. If you're able to share your configuration and files in the `/proj11/work/structural/Son1/cnvkit/raw/` directory we can try to figure out what happened that CNVkit failed. Thanks much for the help debugging.

**Comment by lbeltrame** [comment] 2017-10-27 08:59
Perhaps the wording could be changed. Prior to finding this issue I had no idea I was missing a file.

**Comment by chapmanb** [comment] 2017-10-27 09:27
Luca -- are you also having the same issue as Vang from a recent run? Would you be able to provide more details? I'd be keen to fix the underlying issue with CNVkit but am not sure what is happening right now to be able to reproduce.

**Comment by lbeltrame** [comment] 2017-10-27 09:30
No, it's slitghtly different and I think related to the latest changes by @vladsaveliev: it's trying to upload a mosdepth file that does not exist at all (`foo-coverage.thresholds.bed.gz`). Note that I had to update the pipeline during the run (when not running of course) due to bugs that were already fixed in the latest master.

**Comment by biocyberman** [comment] 2017-10-27 10:08
@chapmanb I haven't come back to cnvkit run so I can't give more details now. But essentially it is like `mosdepth`, it adds non-existing files to upload file list. I think this would be an improvement: 

- Check output file existence before putting them to upload list. If expected output files are not produced, throw exception at from the tool wraper (e.g cnvkit.py). 
- Save a list of non-essential missing files in MISSING_OUTPUT.txt and upload to upload target (i.e. 'final').

With this, under normal circumstances, the exception at https://github.com/chapmanb/bcbio-nextgen/blob/master/bcbio/upload/__init__.py#L127 will not be thrown.

**Comment by chapmanb** [comment] 2017-10-27 10:50
Luca -- thanks for the feedback. Vlad, do your recent updates handle the case where a project got run with an older mosdepth (without thresholds), then gets re-run? In this case we probably don't need to regenerate mosdepth outputs but should handle having that file not present throughout.

In general, I'd prefer to tackle the underlying problems in both of these cases rather than making a mechanism to ignore files. For the cnvkit case it is a problem that the cnr file is missing -- that means to me something is problematic with the run and we should debug the cause of that rather than leaving you with incomplete CNVkit output. If we identify and handle the root cause then we can definitely add a case but I prefer to understand and be explicit about what we're ignoring. I agree the check should come at the CNVkit run level here and can try to work more on that with an idea of what is missing.

Thanks again for all the helpful feedback and debugging.

**Comment by lbeltrame** [comment] 2017-10-27 11:42
> Vlad, do your recent updates handle the case where a project got run with an older mosdepth (without thresholds), then gets re-run

I think it's the culprit in my case: mosdepth was run 1 or 2 days before I updated.

**Comment by chapmanb** [comment] 2017-10-31 09:51
Luca -- Vlad sent some fixes to be able to handle the case of having an older mosdepth run without thresholds so hopefully it will work cleanly for you now if you re-run.

Vang -- still happy to work on the initial CNVkit issue if we can identify the underlying problem.

Thanks much for all the discussion and reports.

**Comment by roryk** [comment] 2019-08-10 15:17
Thanks, looks like this got taken care of, but wasn't closed. Closing now.

**Closed by roryk** 2019-08-10 15:17 UTC
