### ISSUE TITLE
Encoding errors with CIVIC svprioritize and IPython distributed tasks

### ISSUE THREAD

**Issue by lbeltrame** [bcbio/bcbio-nextgen#2890] opened 2019-07-26 07:05 UTC
A typical error, which occurs somehow inside bedtools, is like this:

```python
Traceback (most recent call last):
  File "/opt/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/ipythontasks.py", line 52, in _setup_logging
    yield config
  File "/opt/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/ipythontasks.py", line 447, in detect_sv
    return ipython.zip_args(apply(structural.detect_sv, *args))
  File "/opt/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/ipythontasks.py", line 80, in apply
    return object(*args, **kwargs)
  File "/opt/bcbio/anaconda/lib/python3.6/site-packages/bcbio/structural/__init__.py", line 205, in detect_sv
    for svdata in caller_fn(items):
  File "/opt/bcbio/anaconda/lib/python3.6/site-packages/bcbio/structural/cnvkit.py", line 57, in run
    return _cnvkit_by_type(items, background)
  File "/opt/bcbio/anaconda/lib/python3.6/site-packages/bcbio/structural/cnvkit.py", line 67, in _cnvkit_by_type
    return _run_cnvkit_single(items[0])
  File "/opt/bcbio/anaconda/lib/python3.6/site-packages/bcbio/structural/cnvkit.py", line 110, in _run_cnvkit_single
    return _associate_cnvkit_out(ckouts, [data])
  File "/opt/bcbio/anaconda/lib/python3.6/site-packages/bcbio/structural/cnvkit.py", line 90, in _associate_cnvkit_out
    ckout = _add_plots_to_output(ckout, data)
  File "/opt/bcbio/anaconda/lib/python3.6/site-packages/bcbio/structural/cnvkit.py", line 640, in _add_plots_to_output
    scatter = _add_scatter_plot(out, data)
  File "/opt/bcbio/anaconda/lib/python3.6/site-packages/bcbio/structural/cnvkit.py", line 710, in _add_scatter_plot
    priority_bed = plot._prioritize_plot_regions(pybedtools.BedTool(priority_bed), data, os.path.dirname(out_file))
  File "/opt/bcbio/anaconda/lib/python3.6/site-packages/bcbio/structural/plot.py", line 91, in _prioritize_plot_regions
    for r in region_bt:
  File "pybedtools/cbedtools.pyx", line 754, in pybedtools.cbedtools.IntervalIterator.__next__
  File "/opt/bcbio/anaconda/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 749: ordinal not in range(128)
```

Note that this *only* occurs when running distributed. Running local (`-t local`) even with multiprocessing, won't trigger this error. Testing this locally doesn't yield problems either.

**Comment by roryk** [comment] 2019-07-26 17:27
Thanks, I'm guessing this needs to be fixed in bedtools itself, using ascii_decode there might be breaking things. I'm not sure why this is happening not distributed, though. Could you open up an issue on the pybedtools repo? If I was debugging this locally I'd add a line to write out that region_bt to a file so I could look at the actual file. I'm guessing there is some non-ascii character in position 749 in that file. Would you be up for doing that? If you add a line `region_bt.saveas("path-to-save-file")` at the beginning of that function it will write the BED file out so we can inspect what is happening at position 749.

**Comment by roryk** [comment] 2019-08-10 16:07
Hi Luca, if you can dump out the BED file that is broken I can see if I can fix it in pybedtools, are you up for that?

**Comment by lbeltrame** [comment] 2019-08-26 07:32
Sorry for not replying earlier (holidays). As I'm hitting the issue again I'll make sure to attach it here (it's a public BED file for a common library preparation kit, so no issue) once it occurs.

**Comment by lbeltrame** [comment] 2019-08-30 13:50
Well, the issue is that the file is **gzipped**, but it's read as text:

```
$ file broken.bed 
broken.bed: gzip compressed data, extra field
```

I have no idea why this occurs when distributed and not elsewhere.

**Comment by lbeltrame** [comment] 2019-08-30 13:57
Here's the file (I changed the extension or GH would not let me).
[broken.bed.gz](https://github.com/bcbio/bcbio-nextgen/files/3560178/broken.bed.gz)

**Comment by roryk** [comment] 2019-08-30 16:20
Hi Luca,

Here is my guess: some of the nodes have a different locale set which is causing the encoding to default to ascii, which is breaking this parsing. There is a line in the BED file that has non-ascii characters:

```
53:chr3	38138478	38143022	{:support {:url "https://civicdb.org//#/events/genes/3742/summary", :diseases #{"Waldenström's Macroglobulinemia" "Breast Cancer" "Chronic Lymphocytic Leukemia"}, :origin #{"civic"}, :drugs #{"IRAK-1/4 Inhibitor" "Ibrutinib" "Paclitaxel" "IMG-2005-5"}, :variants #{"L265P" "OVEREXPRESSION"}}, :name #{"MYD88"}}
```

I bet if you remove the `ö` this problem won't happen. If you look in the bcbio logs it should tell you which node is failing, and you could see if you can reproduce it specifically on that node. This is something pybedtools should be handling though.

**Comment by lbeltrame** [comment] 2019-09-02 08:48
Your comment put me on the right track, I think. I use it_IT.UTF-8 on the base installation, which is migrated then to all nodes (they inherit the same configuration). In general, all locales are however set with the UTF-8 counterpart (aside Slackware and perhaps Alpine, this is a default in Linux distributions since 10 years ago or so). However, what bcbio does is setting the locale to C:

https://github.com/bcbio/bcbio-nextgen/blob/741877e593fda89a9e825dc8bd25c2046842759b/bcbio/distributed/runfn.py#L29

I'll test by setting it to C.UTF-8 and see if it works.

**Comment by lbeltrame** [comment] 2019-09-02 08:51
And it looks like my hunch is correct:

```
LANG=C LC_ALL=C LC=C ipython
Python 3.6.7 | packaged by conda-forge | (default, Feb 28 2019, 09:07:38) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.7.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import pybedtools                                                                                                                                                                                                                                                     

In [2]: test = pybedtools.BedTool("broken.bed")                                                                                                                                                                                                                               

In [3]: for region in test: 
   ...:     pass 
   ...:                                                                                                                                                                                                                                                                       
---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
<ipython-input-3-195ba94d8731> in <module>
----> 1 for region in test:
      2     pass
      3 

/opt/bcbio/anaconda/lib/python3.6/site-packages/pybedtools/cbedtools.pyx in pybedtools.cbedtools.IntervalIterator.__next__()

/opt/bcbio/anaconda/lib/python3.6/encodings/ascii.py in decode(self, input, final)
     24 class IncrementalDecoder(codecs.IncrementalDecoder):
     25     def decode(self, input, final=False):
---> 26         return codecs.ascii_decode(input, self.errors)[0]
     27 
     28 class StreamWriter(Codec,codecs.StreamWriter):

UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 749: ordinal not in range(128)
```

But then:

```
LANG=C.UTF-8 LC_ALL=C.UTF-8 LC=C.UTF-8 ipython
Python 3.6.7 | packaged by conda-forge | (default, Feb 28 2019, 09:07:38) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.7.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import pybedtools                                                                                                                                                                                                                                                     
^[[A^[[A
In [2]: test = pybedtools.BedTool("broken.bed")                                                                                                                                                                                                                               

In [3]: for region in test: 
   ...:     pass 
   ...:                                                                                                                                                                                                                                                                       

In [4]:     
```

IMO bcbio should fall back to C.UTF-8 and not C.

**Comment by lbeltrame** [comment] 2019-09-02 08:56
Note that Python itself uses UTF-8 for C in 3.7 or later, as shown in [PEP 538](https://www.python.org/dev/peps/pep-0538) so I guess it should be changed already.

**Comment by roryk** [comment] 2019-09-03 17:21
Luca,

Thank you so much, good detective work! It was really helpful to for me to read the PEP. I think you are right and we should switch that to be the default.

**Comment by roryk** [comment] 2019-09-03 17:51
Hm-- C.UTF-8 isn't available on a few different clusters I've looked at, so I think that's not a super great solution.

**Comment by chapmanb** [comment] 2019-09-03 17:59
Luca and Rory -- locale setting is a pain for sure and we tried to fix this earlier for MultiQC: https://github.com/bcbio/bcbio-nextgen/issues/2746 

If we use `utils.locale_export` to set the locale prior to running cnvkit here that might help avoid the machine specific problems. What do y'all think?

**Comment by roryk** [comment] 2019-09-03 18:05
Thanks Brad! Is there a reason we aren't doing this for the generic toplevel locale settings like in ipythontasks.py and what not?

**Comment by chapmanb** [comment] 2019-09-03 18:14
No reason other than being scared of breaking stuff. A lot of the locale setting is pretty system specific so trying to do as little of it as minimally invasively as possible to make stuff work. I've always ended up breaking things whenever changing these so was afraid to try something more global. You might be tougher than me, so totally up to you.

**Comment by roryk** [comment] 2019-09-03 20:22
Gotcha-- this looks like it is from some internal bcbio code, pybedtools is using the locale we set.

**Comment by roryk** [comment] 2019-09-03 22:51
Ok, I swapped it to always use these lookups everywhere it sets the locale, but to use C.UTF-8/UTF8 if it exists instead of picking just the first UTF-capable entry on the locale. It falls back to that first entry if C.UTF-8 doesn't exist. We'd need to set this any time we are opening up and reading any BED files with non-ascii characters with pybedtools, I think. We might have to revert this commit if it does end up breaking things. I also added an entry to the startup log that says which locale we're using. Luca if you could give the fix a shot that would be helpful.

**Closed** 2020-05-29 05:33 UTC
Labels: bug
