### ISSUE TITLE
Invalid VCF input error during freebayes-joint calling

### ISSUE THREAD

**Issue by phu5ion** [bcbio/bcbio-nextgen#2164] opened 2017-11-20 08:31 UTC
Hi,

While attempting to joint-call with freebayes and gatk (tools_on: gvcf), I've met with the following error. Not sure what's the problem here because previously I've tried freebayes joint-calling before without any problems...

[2017-11-20T08:26Z] 2017-11-20 16:26:47 n068.default.domain INFO [bcbio.run.itx] - ##### ERROR MESSAGE: The provided VCF file is malformed at approximately line number 3437: unparsable vcf record with allele T*>C, for input source: /mnt/projects/ngbhs/cirqseq/2017_bcbio/20171120_freebayes_gvcf_trial/gvcf_trial/work/joint/freebayes-joint/T1607_250816/chr6/square/chr6/chr6_29942343_29943743/1607_250816_N-chr6_29942343_29943743-work/recall.vcf.gz
[2017-11-20T08:26Z] 2017-11-20 16:26:47 n068.default.domain INFO [bcbio.run.itx] - ##### ERROR ------------------------------------------------------------------------------------------
[2017-11-20T08:26Z] 2017-11-20 16:26:47 n068.default.domain ERROR [bcbio.run.itx] -
[2017-11-20T08:26Z] java.lang.Exception: Shell command failed: gatk-framework -Xms250m -Xmx2g -XX:+UseSerialGC -Djava.io.tmpdir=/mnt/projects/ngbhs/cirqseq/2017_bcbio/20171120_freebayes_gvcf_trial/gvcf_trial/work/joint/freebayes-joint/T1607_250816/chr6/square/chr6/chr6_29942343_29943743/tmp4455815619931835823 -T CombineVariants -R /mnt/projects/dlho/tancrc/bcbio_pipeline/genomes/Hsapiens/hg38/seq/hg38.fa -L chr6:29942344-29943743 --out /mnt/projects/ngbhs/cirqseq/2017_bcbio/20171120_freebayes_gvcf_trial/gvcf_trial/work/joint/freebayes-joint/T1607_250816/chr6/square/chr6/chr6_29942343_29943743/txtmp8485332214506232831/1607_250816_N-chr6_29942343_29943743.vcf.gz --genotypemergeoption UNSORTED --suppressCommandLineHeader --setKey null -U LENIENT_VCF_PROCESSING --logging_level ERROR --variant /mnt/projects/ngbhs/cirqseq/2017_bcbio/20171120_freebayes_gvcf_trial/gvcf_trial/work/joint/freebayes-joint/T1607_250816/chr6/square/chr6/chr6_29942343_29943743/1607_250816_N-chr6_29942343_29943743-work/recall.vcf.gz --variant /mnt/projects/ngbhs/cirqseq/2017_bcbio/20171120_freebayes_gvcf_trial/gvcf_trial/work/joint/freebayes-joint/T1607_250816/chr6/square/chr6/chr6_29942343_29943743/1607_250816_N-chr6_29942343_29943743-work/existing.vcf.gz
[2017-11-20T08:26Z]                      ##### ERROR ------------------------------------------------------------------------------------------
[2017-11-20T08:26Z]                      ##### ERROR MESSAGE: The provided VCF file is malformed at approximately line number 3437: unparsable vcf record with allele T*>C, for input source: /mnt/projects/ngbhs/cirqseq/2017_bcbio/20171120_freebayes_gvcf_trial/gvcf_trial/work/joint/freebayes-joint/T1607_250816/chr6/square/chr6/chr6_29942343_29943743/1607_250816_N-chr6_29942343_29943743-work/recall.vcf.gz
[2017-11-20T08:26Z]                      ##### ERROR
[2017-11-20T08:26Z]                      ##### ERROR Please do NOT post this error to the GATK forum unless you have really tried to fix it yourself.
[2017-11-20T08:26Z]                      ##### ERROR
[2017-11-20T08:26Z]                      ##### ERROR commonly asked questions https://www.broadinstitute.org/gatk
[2017-11-20T08:26Z]                      ##### ERROR Visit our website and forum for extensive documentation and answers to
[2017-11-20T08:26Z]                      ##### ERROR
[2017-11-20T08:26Z]                      ##### ERROR (or rerun your command with --help) to view allowable command-line arguments for this tool.
[2017-11-20T08:26Z]                      ##### ERROR If the problem is an invalid argument, please check the online documentation guide
[2017-11-20T08:26Z]                      ##### ERROR
[2017-11-20T08:26Z]                      ##### ERROR The error message below tells you what is the problem.
[2017-11-20T08:26Z]                      ##### ERROR This means that one or more arguments or inputs in your command are incorrect.
[2017-11-20T08:26Z]                      ##### ERROR
[2017-11-20T08:26Z]                      ##### ERROR A USER ERROR has occurred (version 3.6-24-g59fd391):
[2017-11-20T08:26Z]                      ##### ERROR ------------------------------------------------------------------------------------------
[2017-11-20T08:26Z]                      DEBUG  2017-11-20 16:26:47     BlockCompressedOutputStream     Using deflater: Deflater
[2017-11-20T08:26Z]                      Picked up _JAVA_OPTIONS: -XX:+UseSerialGC
[2017-11-20T08:26Z]                                bcbio.run.itx/check-run                    itx.clj:  168
[2017-11-20T08:26Z]     bcbio.variation.recall.square/union-variants/fn/fn                 square.clj:  147
[2017-11-20T08:26Z]        bcbio.variation.recall.square/union-variants/fn                 square.clj:  147
[2017-11-20T08:26Z]           bcbio.variation.recall.square/union-variants                 square.clj:  146
[2017-11-20T08:26Z]      bcbio.variation.recall.square/sample-by-region/fn                 square.clj:  175
[2017-11-20T08:26Z]         bcbio.variation.recall.square/sample-by-region                 square.clj:  169
[2017-11-20T08:26Z]    bcbio.variation.recall.square/sample-by-region-prep                 square.clj:  185
[2017-11-20T08:26Z]             bcbio.variation.recall.square/by-region/fn                 square.clj:  226
[2017-11-20T08:26Z]                        clojure.core.reducers/map/fn/fn               reducers.clj:  167
[2017-11-20T08:26Z]                     clojure.core.protocols/iter-reduce              protocols.clj:   49
[2017-11-20T08:26Z]                              clojure.core.protocols/fn              protocols.clj:  112
[2017-11-20T08:26Z]                            clojure.core.protocols/fn/G              protocols.clj:   13
[2017-11-20T08:26Z]                           clojure.core.reducers/reduce               reducers.clj:   79
[2017-11-20T08:26Z]                          clojure.core.reducers/foldvec               reducers.clj:  335
[2017-11-20T08:26Z]                    clojure.core.reducers/foldvec/fc/fn               reducers.clj:  340
[2017-11-20T08:26Z]                       clojure.core.reducers/foldvec/fn               reducers.clj:  345
[2017-11-20T08:26Z]                                  clojure.lang.AFn.call                   AFn.java:   18
[2017-11-20T08:26Z] java.util.concurrent.ForkJoinTask$AdaptedCallable.exec          ForkJoinTask.java: 1424
[2017-11-20T08:26Z]               java.util.concurrent.ForkJoinTask.doExec          ForkJoinTask.java:  289
[2017-11-20T08:26Z]    java.util.concurrent.ForkJoinPool$WorkQueue.runTask          ForkJoinPool.java: 1056
[2017-11-20T08:26Z]            java.util.concurrent.ForkJoinPool.runWorker          ForkJoinPool.java: 1692
[2017-11-20T08:26Z]          java.util.concurrent.ForkJoinWorkerThread.run  ForkJoinWorkerThread.java:  157
[2017-11-20T08:26Z] 2017-11-20 16:26:47 n068.default.domain ERROR [bcbio.run.parallel] -
[2017-11-20T08:26Z] java.lang.RuntimeException: java.lang.RuntimeException: java.lang.Exception: Shell command failed: gatk-framework -Xms250m -Xmx2g -XX:+UseSerialGC -Djava.io.tmpdir=/mnt/projects/ngbhs/cirqseq/2017_bcbio/20171120_freebayes_gvcf_trial/gvcf_trial/work/joint/freebayes-joint/T1607_250816/chr6/square/chr6/chr6_29942343_29943743/tmp4455815619931835823 -T CombineVariants -R /mnt/projects/dlho/tancrc/bcbio_pipeline/genomes/Hsapiens/hg38/seq/hg38.fa -L chr6:29942344-29943743 --out /mnt/projects/ngbhs/cirqseq/2017_bcbio/20171120_freebayes_gvcf_trial/gvcf_trial/work/joint/freebayes-joint/T1607_250816/chr6/square/chr6/chr6_29942343_29943743/txtmp8485332214506232831/1607_250816_N-chr6_29942343_29943743.vcf.gz --genotypemergeoption UNSORTED --suppressCommandLineHeader --setKey null -U LENIENT_VCF_PROCESSING --logging_level ERROR --variant /mnt/projects/ngbhs/cirqseq/2017_bcbio/20171120_freebayes_gvcf_trial/gvcf_trial/work/joint/freebayes-joint/T1607_250816/chr6/square/chr6/chr6_29942343_29943743/1607_250816_N-chr6_29942343_29943743-work/recall.vcf.gz --variant /mnt/projects/ngbhs/cirqseq/2017_bcbio/20171120_freebayes_gvcf_trial/gvcf_trial/work/joint/freebayes-joint/T1607_250816/chr6/square/chr6/chr6_29942343_29943743/1607_250816_N-chr6_29942343_29943743-work/existing.vcf.gz
...
                            ##### ERROR
                            ##### ERROR Please do NOT post this error to the GATK forum unless you have really tried to fix it yourself.
                            ##### ERROR
                            ##### ERROR commonly asked questions https://www.broadinstitute.org/gatk
                            ##### ERROR Visit our website and forum for extensive documentation and answers to
                            ##### ERROR
                            ##### ERROR (or rerun your command with --help) to view allowable command-line arguments for this tool.
                            ##### ERROR If the problem is an invalid argument, please check the online documentation guide
                            ##### ERROR
                            ##### ERROR The error message below tells you what is the problem.
                            ##### ERROR This means that one or more arguments or inputs in your command are incorrect.
                            ##### ERROR
                            ##### ERROR A USER ERROR has occurred (version 3.6-24-g59fd391):
                            ##### ERROR ------------------------------------------------------------------------------------------
                            DEBUG       2017-11-20 16:26:47     BlockCompressedOutputStream     Using deflater: Deflater
                            Picked up _JAVA_OPTIONS: -XX:+UseSerialGC
                               bcbio.run.itx/check-run                    itx.clj:  168
    bcbio.variation.recall.square/union-variants/fn/fn                 square.clj:  147
       bcbio.variation.recall.square/union-variants/fn                 square.clj:  147
          bcbio.variation.recall.square/union-variants                 square.clj:  146
     bcbio.variation.recall.square/sample-by-region/fn                 square.clj:  175
        bcbio.variation.recall.square/sample-by-region                 square.clj:  169
   bcbio.variation.recall.square/sample-by-region-prep                 square.clj:  185
            bcbio.variation.recall.square/by-region/fn                 square.clj:  226
                       clojure.core.reducers/map/fn/fn               reducers.clj:  167
                    clojure.core.protocols/iter-reduce              protocols.clj:   49
                             clojure.core.protocols/fn              protocols.clj:  112
                           clojure.core.protocols/fn/G              protocols.clj:   13
                          clojure.core.reducers/reduce               reducers.clj:   79
                         clojure.core.reducers/foldvec               reducers.clj:  335
                   clojure.core.reducers/foldvec/fc/fn               reducers.clj:  340
                      clojure.core.reducers/foldvec/fn               reducers.clj:  345
                                 clojure.lang.AFn.call                   AFn.java:   18
java.util.concurrent.ForkJoinTask$AdaptedCallable.exec          ForkJoinTask.java: 1424
              java.util.concurrent.ForkJoinTask.doExec          ForkJoinTask.java:  289
   java.util.concurrent.ForkJoinPool$WorkQueue.runTask          ForkJoinPool.java: 1056
           java.util.concurrent.ForkJoinPool.runWorker          ForkJoinPool.java: 1692
         java.util.concurrent.ForkJoinWorkerThread.run  ForkJoinWorkerThread.java:  157

' returned non-zero exit status 1

FYI: problematic input
chr6    29942582        .       TC      T*>C,<  1       PASS    AB=0,0;ABP=0,0;AC=0,0;AF=0,0;AN=2;AO=0,0;CIGAR=1M2I1M,1X;DP=382;DPB=382;DPRA=0,0;EPP=0,0;EPPR=12.1533;GTI=0;LEN=2,1;MEANALT=0,0;MQM=0,0;MQMR=57.8395;NS=1;NUMALT=2;ODDS=531.397;PAIRED=0,0;PAIREDR=0.944737;PAO=0,0;PQA=0,0;PQR=0;PRO=0;QA=0,0;QR=12192;RO=380;RPL=0,0;RPP=0,0;RPPR=3.37602;RPR=0,0;RUN=1,1;SAF=0,0;SAP=0,0;SAR=0,0;SRF=190;SRP=3.0103;SRR=190;TYPE=ins,snp;technology.illumina=0,0     GT:GQ:DP:AD:RO:QR:AO:QA:GL      0/0:148.72:382:380,0,0:380:12192:0,0:0,0:0,-114.391,-1092,-114.391,-1092,-1092

Hmm, I've never seen an allele like this before, is it due to the gVCF format specifications? If so, how do I output gVCF for freebayes using the bcbio pipeline?
Thanks!

**Comment by chapmanb** [comment] 2017-11-20 18:15
Thanks for the report and sorry about the issue. I'm not sure what is going on with that allele, it looks like a potentially problematic output from FreeBayes for that region and I'm not sure what it is meant to represent. My suggestion for debugging would be to try to isolate, from `log/bcbio-nextgen-commands.log` the command that's generating that allele so we can reduce to a smaller test case that demonstrates the problem. We could then raise an issue with the FreeBayes team to see if we can identify what is happening there and how best to resolve. Thanks much for the help debugging this.

**Comment by phu5ion** [comment] 2017-11-21 06:50
Pardon if I'm wrong but it seems to me to be a problem with the squaring off of variants in bcbio-variation-recall square when outputting in gVCF format, where both variant and non-variants are output. 
In the needcall.vcf.gz, the calls are normal and represented like this. Both the variant (1st row) and non-variant (2nd row) calls are present:
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO
chr6    29942581        .       C       G       93.37   PASS    .
chr6    29942582        .       T       <*>     0       PASS    .

However in the recall.vcf.gz, the calls look like this. It looks to me like the non-variant call have been treated as a variant. The parsing looks odd to me too.
chr6    29942581        .       C       G       1       PASS    AB=0.140625;ABP=433.776;AC=0;AF=0;AN=2;AO=54;CIGAR=1X;DP=384;DPB=384;DPRA=0;EPP=4.45795;EPPR=12.046;GTI=0;LEN=1;MEANALT=2;MQM=59.8333;MQMR=57.5319;NS=1;NUMALT=1;ODDS=76.1559;PAIRED=0.87037;PAIREDR=0.954407;PAO=0;PQA=0;PQR=0;PRO=0;QA=1513;QR=10955;RO=329;RPL=30;RPP=4.45795;RPPR=6.50182;RPR=24;RUN=1;SAF=26;SAP=3.17115;SAR=28;SRF=167;SRP=3.17531;SRR=162;TYPE=snp;technology.illumina=1 GT:GQ:DP:AD:RO:QR:AO:QA:GL      0/0:-0:384:329,54:329:10955:54:1513:-20.9943,0,-864.62
chr6    29942582        .       TC      T*>C,<  1       PASS    AB=0,0;ABP=0,0;AC=0,0;AF=0,0;AN=2;AO=0,0;CIGAR=1M2I1M,1X;DP=382;DPB=382;DPRA=0,0;EPP=0,0;EPPR=12.1533;GTI=0;LEN=2,1;MEANALT=0,0;MQM=0,0;MQMR=57.8395;NS=1;NUMALT=2;ODDS=531.397;PAIRED=0,0;PAIREDR=0.944737;PAO=0,0;PQA=0,0;PQR=0;PRO=0;QA=0,0;QR=12192;RO=380;RPL=0,0;RPP=0,0;RPPR=3.37602;RPR=0,0;RUN=1,1;SAF=0,0;SAP=0,0;SAR=0,0;SRF=190;SRP=3.0103;SRR=190;TYPE=ins,snp;technology.illumina=0,0     GT:GQ:DP:AD:RO:QR:AO:QA:GL      0/0:148.72:382:380,0,0:380:12192:0,0:0,0:0,-114.391,-1092,-114.391,-1092,-1092

**Comment by chapmanb** [comment] 2017-11-21 10:48
Thanks much for digging into this and following up. This is really helpful -- we shouldn't be feeding the gVCF outputs into `needcall` directly so something is problematic about how bcbio processes your setup. Would you be able to share your configuration YAML file for the problem sample? That could hopefully help me reproduce and avoid the issue. Thanks much.

**Comment by phu5ion** [comment] 2017-11-22 00:40
[gvcf_trial.zip](https://github.com/chapmanb/bcbio-nextgen/files/1493492/gvcf_trial.zip)
Hi Brad,

Thanks for looking into this issue. Here you go!

**Comment by chapmanb** [comment] 2017-11-22 02:12
Thanks much for the configuration. I'm unfortunately still having trouble reproducing this with apparently the same configuration locally so am likely missing something in your setup. What version of bcbio are you running? There were previously some issues with specifying both `jointcaller` and `tools_on: [gvcf]` but these should have been resolved in 1.0.6 or the latest development version. Is it possible you're running an older version for these tests? Hope that helps explain the problem.

**Comment by roryk** [comment] 2019-08-10 15:36
Thanks, we couldn't reproduce this and this is stale, so closing. Thank you!

**Closed by roryk** 2019-08-10 15:36 UTC
