### ISSUE TITLE
mutect2 resource and speed

### ISSUE THREAD

**Issue by csardas** [bcbio/bcbio-nextgen#1969] opened 2017-06-09 03:39 UTC
hi all,

I am running somatic variant calling of several tumor-normal paired samples. These samples are 30x paired-end whole genome sequencing.
I followed  [the somatic-variant calling pipeline](https://bcbio-nextgen.readthedocs.io/en/latest/contents/pipelines.html#somatic-with-germline-variants) and used mutect2 as somatic variant caller,  gatk-haplotype as germline variant caller. 

I tried to use 8 cpu for one job, and run 4 jobs parallelly on a 32 CPUs machine. It cost about 60 hours to run the variant calling step of each job and 90 hours for whole pipeline.

In the middle to late stage of variant calling step, I found the system was hanged and cant not create any extra process like ls or top. At the same time the memory usage is low and the process of bcbio_nextgen is still running. Finally I got the result after two days.

After that I tried to run 3 jobs parallelly (using 3 * 8 = 24 CPU) and carefully mange other process to prevent using too much threads.

Is the time and resource cost of Mutect2 make sense and normal?  Is there any practical strategy to run Mutect2 by bcbio?

**Comment by ohofmann** [comment] 2017-06-09 03:55
That does sound reasonable to me -- we tend to run WGS somatic samples at 128 or 256 cores, and the whole pipeline takes 40 or 30 hours, respectively. MuTect2 and VarDict _can_ stall on regions with extremely high coverage but that usually results in no CPU activity, i.e., the process just hangs.

**Comment by chapmanb** [comment] 2017-06-09 13:07
Thanks for starting this discussion. Those speeds do seem reasonable with MuTect2, it can be quite slow especially in repetitive or tricky regions. This doesn't appear to have any dependence of the bcbio usage, which is fairly vanilla, but just on the algorithm itself. We're currently working on integrating GATK4 which has an updated version of MuTect2 and will be validation and benchmarking it soon. I'm hoping that provides better and more consistent perfomance.

I haven't seen hanging or other issues, just slow processing on some regions. If you're able to isolate or further define what is going on we'd be happy to debug that more. Hope this helps.

**Comment by hh1985** [comment] 2017-06-09 18:06
Any scatter-gather tweak with mutect2? http://gatkforums.broadinstitute.org/gatk/discussion/9373/optimizing-mutect2-runs-on-whole-genomes

I use mutect2 for panel sequencing. A single job takes 40+ hours.  After splitting the target region by chromosome, a single job takes 6-8 hours.

Hope this helps.

**Comment by chapmanb** [comment] 2017-06-10 09:38
That's exactly right. bcbio splits the input by genomic regions, trying to pick evenly sized regions with breakpoints at positions in the genome missing coverage. It then runs all of the regions in parallel and merges the resulting VCF using a scatter gather approach. The optimizations discussed here would be on top of that existing functionality, and are at the level of improving MuTect2 speed on individual regions. Thanks again for the discussion.

**Comment by hh1985** [comment] 2017-06-10 17:24
Sorry for missing that. I am working on benchmarking different tools, but still new to bcbio.  Then one way I can imagine is to re-implement/optimize mutect2 with C/C++:)

**Comment by lbeltrame** [comment] 2017-06-14 12:30
I can confirm that MuTect 2 is considerably slower than version 1 (but at the Broad are, IIRC, aware of this): these times fit my observations (up to 6-8 hours for WES-level datasets when split by bcbio).

**Comment by hh1985** [comment] 2017-06-19 17:54
Sentieon provides c++ speeding solution for mutect2. They claim 10X faster.

**Comment by chapmanb** [comment] 2017-06-19 18:45
bcbio does support sentieon if you have a license, both tnhaplotyper (their MuTect2-equivalent caller) and tnscope (their custom somatic caller):

https://github.com/chapmanb/bcbio-nextgen/blob/master/bcbio/variation/sentieon.py

You'll need to add a `resources` tag pointing bcbio to the sentieon keyfile or license server: http://bcbio-nextgen.readthedocs.io/en/latest/contents/configuration.html#resources

Hope this helps.

**Comment by roryk** [comment] 2019-08-10 15:39
Thanks, looks like this was answered but not closed, so closing.

**Closed by roryk** 2019-08-10 15:39 UTC
