### ISSUE TITLE
neverending ChIP-Seq with bedops after update to v1.2.4

### ISSUE THREAD

**Issue by LMannarino** [bcbio/bcbio-nextgen#3379] opened 2020-11-24 09:52 UTC
**Version info**
bcbio version v1.2.4

**Issue**

Hi,
I have run a ChIP-Seq analysis with 46 samples with bcbio version 1.2.3, and it took 3 days to finish.

Now, I have upgraded to version v1.2.4 and run another ChIP-Seq with 11 samples and after 6 days it hasn't finished yet. Looking to the work folder and .log file, it seems that it only lacks the last step of making the "consensus".
From the .log file it seems that it is in a never ending loop, since it is keeping going like:

```
[2020-11-24T09:47Z] asami: Merging non-overlapping peaks, iteration 315088.
[2020-11-24T09:47Z] asami: Considering 1 peaks, choosing the highest score for overlapping peaks.
[2020-11-24T09:47Z] asami: Checking if there are peaks left to merge.
[2020-11-24T09:47Z] asami: Adding 0 peaks to consensus peaks.
[2020-11-24T09:47Z] asami: Merging non-overlapping peaks, iteration 315089.
[2020-11-24T09:47Z] asami: Considering 1 peaks, choosing the highest score for overlapping peaks.
[2020-11-24T09:47Z] asami: Checking if there are peaks left to merge.
[2020-11-24T09:47Z] asami: Adding 0 peaks to consensus peaks.
[2020-11-24T09:47Z] asami: Merging non-overlapping peaks, iteration 315090.
[2020-11-24T09:47Z] asami: Considering 1 peaks, choosing the highest score for overlapping peaks.
[2020-11-24T09:47Z] asami: Checking if there are peaks left to merge.
[2020-11-24T09:47Z] asami: Adding 0 peaks to consensus peaks.
[2020-11-24T09:47Z] asami: Merging non-overlapping peaks, iteration 315091.
[2020-11-24T09:47Z] asami: Considering 1 peaks, choosing the highest score for overlapping peaks.
[2020-11-24T09:47Z] asami: Checking if there are peaks left to merge.
[2020-11-24T09:47Z] asami: Adding 0 peaks to consensus peaks.
[2020-11-24T09:47Z] asami: Merging non-overlapping peaks, iteration 315092.
[2020-11-24T09:47Z] asami: Considering 1 peaks, choosing the highest score for overlapping peaks.
[2020-11-24T09:47Z] asami: Checking if there are peaks left to merge.
```
Could it be due to the bedops https://bedops.readthedocs.io/en/latest/content/usage-examples/master-list.html that has been introduced in the latest update for consensus peak calling?

Thank you

@lbeltrame

**Comment by lbeltrame** [comment] 2020-11-26 15:48
Looking at https://github.com/bcbio/bcbio-nextgen/blob/aeccd37ed336a9730edbfa0e47c418d148d42647/bcbio/chipseq/peaks.py#L200

When is that condition becoming false? It looks like it can become an infinite loop.

**Comment by lbeltrame** [comment] 2020-11-27 07:40
I've found out the root cause.

https://github.com/bcbio/bcbio-nextgen/blob/aeccd37ed336a9730edbfa0e47c418d148d42647/bcbio/chipseq/peaks.py#L219

In case we are left with one single, unmergeable record, this will keep having a file with a size (because it contains one line), and even if there are no more items to add (`nitems` on the following lines is zero), the program will enter an infinite loop. This means that we have to exit the loop in case we don't have any more peaks to add.

**Comment by roryk** [comment] 2020-11-30 20:19
Thank you for figuring this out! Sorry for being slow to respond, I've been trying to fix the automated testing before I dealt with more issues. I'll push a fix for this today, working on it now.

**Closed** 2020-12-01 23:33 UTC

**Comment by roryk** [comment] 2020-12-01 23:34
Thanks so much to both of you for figuring out the problem-- sorry for not catching it sooner, we don't do much broad peak ChIP-seq. For the time being I turned off consensus calls for broad peaks. Do either of you have suggestions about a reasonable way to do the consensus calling for broad peaks? I think the bedops consensus method only really makes sense for narrow peaks.

**Comment by LMannarino** [comment] 2020-12-02 08:33
Hi Rory,
thank you for bypassing the problem temporarily. In general, for either narrow or broad peaks, I would suggest the consensus as computed by DiffBind [https://bioconductor.org/packages/release/bioc/html/DiffBind.html](url) with dba.overlap + dba.peakset. Don't know if it can be easily added.
