### ISSUE TITLE
Fresh install fails / conda deepvariant

### ISSUE THREAD

**Issue by PatrickJReed** [bcbio/bcbio-nextgen#2613] opened 2019-01-09 00:08 UTC
Im failing to get bcbio installed on a new google cloud instance.  Is this a conda issue?

ERROR conda.core.link:_execute(507): An error occurred while installing package 'bioconda::deepvariant-0.7.2-py27h5d9141f_1'.
LinkError: post-link script failed for package bioconda::deepvariant-0.7.2-py27h5d9141f_1
running your command again with `-v` will provide additional information
location of failed script: /usr/local/share/bcbio/anaconda/envs/dv/bin/.deepvariant-post-link.sh
==> script messages <==
<None>
Attempting to roll back.
Rolling back transaction: done
LinkError: post-link script failed for package bioconda::deepvariant-0.7.2-py27h5d9141f_1
running your command again with `-v` will provide additional information
location of failed script: /usr/local/share/bcbio/anaconda/envs/dv/bin/.deepvariant-post-link.sh
==> script messages <==
<None>
Fatal error: local() encountered an error (return code 1) while executing '/usr/local/share/bcbio/anaconda/bin/conda install -y -n dv -c conda-forge -c bioconda python=2 'deepvariant''
Aborting.

**Comment by PatrickJReed** [comment] 2019-01-09 00:21
error is reproducible calling conda directly:

sudo /usr/local/share/bcbio/anaconda/bin/conda install -v -y -n dv -c conda-forge -c bioconda python=2 'deepvariant'

Traceback (most recent call last):
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 819, in __call__
    return func(*args, **kwargs)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 78, in _main
    exit_code = do_call(args, p)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/conda/cli/conda_argparse.py", line 77, in do_call
    exit_code = getattr(module, func_name)(args, parser)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/conda/cli/main_install.py", line 11, in execute
    install(args, parser, 'install')
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 253, in install
    handle_txn(unlink_link_transaction, prefix, args, newenv)
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 282, in handle_txn
    unlink_link_transaction.execute()
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/conda/core/link.py", line 228, in execute
    self._execute(tuple(concat(interleave(itervalues(self.prefix_action_groups)))))
  File "/usr/local/share/bcbio/anaconda/lib/python2.7/site-packages/conda/core/link.py", line 526, in _execute
    rollback_excs,
CondaMultiError: post-link script failed for package bioconda::deepvariant-0.7.2-py27h5d9141f_1
running your command again with `-v` will provide additional information
location of failed script: /usr/local/share/bcbio/anaconda/envs/dv/bin/.deepvariant-post-link.sh

**Comment by chapmanb** [comment] 2019-01-09 12:44
Patrick;
Thank you for the detailed report and apologies about the issue. I was able to replicate on GCP machines and it looks like the issue is that Google compute instances have a `/etc/boto.cfg` that gets picked up and conflicts with the conda version (https://github.com/GoogleCloudPlatform/gsutil/issues/516#issuecomment-380639424):
```
$ ./env/bin/gsutil
Traceback (most recent call last):
  File "/mnt/work/tmp/dv/env/share/google-cloud-sdk-218.0.0-1000/platform/gsutil/gsutil", line 22, in <module>
    gsutil.RunMain()
  File "/mnt/work/tmp/dv/env/share/google-cloud-sdk-218.0.0-1000/platform/gsutil/gsutil.py", line 116, in RunMain
    import gslib.__main__
  File "/mnt/work/tmp/dv/env/share/google-cloud-sdk-218.0.0-1000/platform/gsutil/gslib/__main__.py", line 39, in <module>
    import boto
  File "/mnt/work/tmp/dv/env/share/google-cloud-sdk-218.0.0-1000/platform/gsutil/third_party/boto/boto/__init__.py", line 1216, in <module>
    boto.plugin.load_plugins(config)
  File "/mnt/work/tmp/dv/env/share/google-cloud-sdk-218.0.0-1000/platform/gsutil/third_party/boto/boto/plugin.py", line 93, in load_plugins
    _import_module(file)
  File "/mnt/work/tmp/dv/env/share/google-cloud-sdk-218.0.0-1000/platform/gsutil/third_party/boto/boto/plugin.py", line 75, in _import_module
    return imp.load_module(name, file, filename, data)
  File "/usr/lib/python3/dist-packages/google_compute_engine/boto/compute_auth.py", line 19, in <module>
    from google_compute_engine import logger
ImportError: No module named google_compute_engine
$ export BOTO_CONFIG=/ignoreglobal
$ ./env/bin/gsutil
Usage: gsutil [-D] [-DD] [-h header]... [-m] [-o] [-q] [command [opts...] args...]
```
I pushed a workaround to cloudbiolinux to ignore this file which should hopefully fix this. If you remove your cached cloudbiolinux download (`rm -rf tmpbcbio-install`) and re-run it should get the fixed version and hopefully work cleanly to get your install finished.

**Comment by jxshi** [comment] 2019-01-17 09:31
Hi Chapman,

I encountered the same error message when install bcbio-nextgen in a CentOS Linux release 7.2.1511 (Core). I have already tried the solution you mentioned above, but it did not work. 

Can you check for me please? TIA!

Here is the command that I have tried:
```
# 1. Fresh install 
python bcbio_nextgen_install.py /home/zdjzyx01/local/share/bcbio --tooldir=/home/zdjzyx01/local --genomes GRCh37 --aligners bwa --aligners bowtie2

# 2. Run the command to install deepvariant.
/home/zdjzyx01/local/share/bcbio/anaconda/bin/conda install -y -n dv -c conda-forge -c bioconda python=2 'deepvariant'

# 3. Install deepvariant by using conda
conda install -c bioconda deepvariant
```

Here is the error message:
```
ERROR conda.core.link:_execute(507): An error occurred while installing package 'bioconda::deepvariant-0.7.2-py27h5d9141f_1'.
LinkError: post-link script failed for package bioconda::deepvariant-0.7.2-py27h5d9141f_1
running your command again with `-v` will provide additional information
location of failed script: /home/zdjzyx01/local/share/bcbio/anaconda/envs/dv/bin/.deepvariant-post-link.sh
==> script messages <==
<None>

Attempting to roll back.

Rolling back transaction: done

LinkError: post-link script failed for package bioconda::deepvariant-0.7.2-py27h5d9141f_1
running your command again with `-v` will provide additional information
location of failed script: /home/zdjzyx01/local/share/bcbio/anaconda/envs/dv/bin/.deepvariant-post-link.sh
==> script messages <==
<None>




Fatal error: local() encountered an error (return code 1) while executing 'export BOTO_CONFIG=/ignoreglobal && /public/home/zdjzyx01/local/share/bcbio/anaconda/bin/conda install -y -n dv -c conda-forge -c bioconda python=2 'deepvariant''

Aborting.
Traceback (most recent call last):
  File "bcbio_nextgen_install.py", line 287, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "bcbio_nextgen_install.py", line 44, in main
    subprocess.check_call([bcbio, "upgrade"] + _clean_args(sys_argv, args))
  File "/usr/lib64/python2.7/subprocess.py", line 542, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/zdjzyx01/local/share/bcbio/anaconda/bin/bcbio_nextgen.py', 'upgrade', '--tooldir=/home/zdjzyx01/local', '--genomes', 'GRCh37', '--aligners', 'bwa', '--aligners', 'bowtie2', '--data']' returned non-zero exit status 1
```

**Comment by jxshi** [comment] 2019-01-18 01:08
> Patrick;
> Thank you for the detailed report and apologies about the issue. I was able to replicate on GCP machines and it looks like the issue is that Google compute instances have a `/etc/boto.cfg` that gets picked up and conflicts with the conda version ([GoogleCloudPlatform/gsutil#516 (comment)](https://github.com/GoogleCloudPlatform/gsutil/issues/516#issuecomment-380639424)):
> 
> ```
> $ ./env/bin/gsutil
> Traceback (most recent call last):
>   File "/mnt/work/tmp/dv/env/share/google-cloud-sdk-218.0.0-1000/platform/gsutil/gsutil", line 22, in <module>
>     gsutil.RunMain()
>   File "/mnt/work/tmp/dv/env/share/google-cloud-sdk-218.0.0-1000/platform/gsutil/gsutil.py", line 116, in RunMain
>     import gslib.__main__
>   File "/mnt/work/tmp/dv/env/share/google-cloud-sdk-218.0.0-1000/platform/gsutil/gslib/__main__.py", line 39, in <module>
>     import boto
>   File "/mnt/work/tmp/dv/env/share/google-cloud-sdk-218.0.0-1000/platform/gsutil/third_party/boto/boto/__init__.py", line 1216, in <module>
>     boto.plugin.load_plugins(config)
>   File "/mnt/work/tmp/dv/env/share/google-cloud-sdk-218.0.0-1000/platform/gsutil/third_party/boto/boto/plugin.py", line 93, in load_plugins
>     _import_module(file)
>   File "/mnt/work/tmp/dv/env/share/google-cloud-sdk-218.0.0-1000/platform/gsutil/third_party/boto/boto/plugin.py", line 75, in _import_module
>     return imp.load_module(name, file, filename, data)
>   File "/usr/lib/python3/dist-packages/google_compute_engine/boto/compute_auth.py", line 19, in <module>
>     from google_compute_engine import logger
> ImportError: No module named google_compute_engine
> $ export BOTO_CONFIG=/ignoreglobal
> $ ./env/bin/gsutil
> Usage: gsutil [-D] [-DD] [-h header]... [-m] [-o] [-q] [command [opts...] args...]
> ```
> I pushed a workaround to cloudbiolinux to ignore this file which should hopefully fix this. If you remove your cached cloudbiolinux download (`rm -rf tmpbcbio-install`) and re-run it should get the fixed version and hopefully work cleanly to get your install finished.

I encountered the same error message. Can you check for me please? Thanks!

**Comment by chapmanb** [comment] 2019-01-18 19:12
Sorry about the DeepVariant install issues. It appears as if the fix we put in to try and work around existing issues with boto configurations is in place, so there must be something else triggering issues with the download of the DeepVariant model files during the post link step. Unfortunately the tracebacks don't tell us what that is, but running with the `-v` flag might give us more information:
```
export BOTO_CONFIG=/ignoreglobal && /home/zdjzyx01/local/share/bcbio/anaconda/bin/conda install -v -y -n dv -c conda-forge -c bioconda python=2 'deepvariant'
```
Does that provide any useful error messages we could work from? Thanks much for the help debugging this.

**Comment by jxshi** [comment] 2019-01-19 02:36
> export BOTO_CONFIG=/ignoreglobal && /home/zdjzyx01/local/share/bcbio/anaconda/bin/conda install -v -y -n dv -c conda-forge -c bioconda python=2 'deepvariant'

The error message is listed below. Hope this can give you some clue on how to debug. Thank you very much!
```
pyc file failed to compile successfully
python_exe_full_path: /home/zdjzyx01/local/share/bcbio/anaconda/envs/dv/bin/python2.7
py_full_path: /home/zdjzyx01/local/share/bcbio/anaconda/envs/dv/lib/python2.7/site-packages/linecache2/tests/inspect_fodder2.py
pyc_full_path: /home/zdjzyx01/local/share/bcbio/anaconda/envs/dv/lib/python2.7/site-packages/linecache2/tests/inspect_fodder2.pyc
compile rc: 1
compile stdout: Compiling lib/python2.7/site-packages/linecache2/tests/inspect_fodder2.py ...
  File "lib/python2.7/site-packages/linecache2/tests/inspect_fodder2.py", line 102
    def keyworded(*arg1, arg2=1):
                            ^
SyntaxError: invalid syntax


compile stderr:

```

**Comment by chapmanb** [comment] 2019-01-19 12:41
Thanks much for the additional details. Unfortunately, I believe that error is one that gets ignored (https://github.com/testing-cabal/linecache2/issues/12#issuecomment-331760944) and you'll see that even on successful installs, so it's not diagnostic of the underlying issue. We worked on debugging a similar problem (https://github.com/google/deepvariant/issues/137#issuecomment-451711664) and there were other downstream errors that indicated what happened. Would you be able to post the full traceback of the log? When you ran the install manually as above, did it complete or error out in some way? It's possible that you had an intermittent network error previously or something else that is non-reproducible.

Sorry to not know exactly what is happening but hope this helps.

**Comment by jxshi** [comment] 2019-01-19 13:00
> Thanks much for the additional details. Unfortunately, I believe that error is one that gets ignored ([testing-cabal/linecache2#12 (comment)](https://github.com/testing-cabal/linecache2/issues/12#issuecomment-331760944)) and you'll see that even on successful installs, so it's not diagnostic of the underlying issue. We worked on debugging a similar problem ([google/deepvariant#137 (comment)](https://github.com/google/deepvariant/issues/137#issuecomment-451711664)) and there were other downstream errors that indicated what happened. Would you be able to post the full traceback of the log? When you ran the install manually as above, did it complete or error out in some way? It's possible that you had an intermittent network error previously or something else that is non-reproducible.
> 
> Sorry to not know exactly what is happening but hope this helps.

I think you are right. It might be  intermittent network error. I tried to run the command several times, and it finally worked.

Thank you for you timely reply! Have a nice day!

Best regards,

Jianxiang

**Comment by slagtermaarten** [comment] 2019-02-18 12:03
Hi Chapman,
I'm also experiencing this on Ubuntu 16.04 LTS.
Retrying multiple times did not solve the issue, nor did manually installing DeepVariant. Do you have any  other suggestions? 
TIA! Maarten

```
Traceback (most recent call last):
  File "/DATA/resources/bcbio/anaconda/bin/bcbio_nextgen.py", line 221, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/DATA/resources/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 89, in upgrade_bcbio
    upgrade_thirdparty_tools(args, REMOTES)
  File "/DATA/resources/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 521, in upgrade_thirdparty_tools
    cbl_deploy.deploy(s)
  File "/DATA/resources/bcbio/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 63, in deploy
    _setup_vm(options, vm_launcher, actions)
  File "/DATA/resources/bcbio/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 109, in _setup_vm
    configure_instance(options, actions)
  File "/DATA/resources/bcbio/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 258, in configure_instance
    install_biolinux(options)
  File "/DATA/resources/bcbio/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 282, in install_biolinux
    _perform_install(target=target, flavor=flavor, more_custom_add=options.get("custom_add", None))
  File "/DATA/resources/bcbio/tmpbcbio-install/cloudbiolinux/fabfile.py", line 120, in _perform_install
    install_conda(flavor=flavor, automated=True)
  File "/DATA/resources/bcbio/tmpbcbio-install/cloudbiolinux/fabfile.py", line 321, in install_conda
    conda.install_packages(env, to_install=pkg_install)
  File "/DATA/resources/bcbio/tmpbcbio-install/cloudbiolinux/cloudbio/package/conda.py", line 33, in install_packages
    install_in(conda_bin, env.system_install, config_file.base, packages)
  File "/DATA/resources/bcbio/tmpbcbio-install/cloudbiolinux/cloudbio/package/conda.py", line 88, in install_in
    "{py_version} {pkgs_str}".format(**locals()), shell=True)
  File "/DATA/resources/bcbio/anaconda/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'export BOTO_CONFIG=/ignoreglobal && /DATA/resources/bcbio/anaconda/bin/conda install -y -n dv -c conda-forge -c bioconda python=2 'deepvariant'' returned non-zero exit status 1
Traceback (most recent call last):
  File "bcbio_nextgen_install.py", line 287, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "bcbio_nextgen_install.py", line 44, in main
    subprocess.check_call([bcbio, "upgrade"] + _clean_args(sys_argv, args))
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/DATA/resources/bcbio/anaconda/bin/bcbio_nextgen.py', 'upgrade', '--tooldir=/DATA/resources/bcbio/bcbcio_tools', '--genomes', 'GRCh37', '--aligners', 'bwa', '--aligners', 'bowtie2', '--data']' returned non-zero exit status 1
```

**Comment by jxshi** [comment] 2019-02-18 15:04
> Hi Chapman,
> I'm also experiencing this on Ubuntu 16.04 LTS.
> Retrying multiple times did not solve the issue, nor did manually installing DeepVariant. Do you have any other suggestions?
> TIA! Maarten
> 
> ```
> Traceback (most recent call last):
>   File "/DATA/resources/bcbio/anaconda/bin/bcbio_nextgen.py", line 221, in <module>
>     install.upgrade_bcbio(kwargs["args"])
>   File "/DATA/resources/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 89, in upgrade_bcbio
>     upgrade_thirdparty_tools(args, REMOTES)
>   File "/DATA/resources/bcbio/anaconda/lib/python2.7/site-packages/bcbio/install.py", line 521, in upgrade_thirdparty_tools
>     cbl_deploy.deploy(s)
>   File "/DATA/resources/bcbio/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 63, in deploy
>     _setup_vm(options, vm_launcher, actions)
>   File "/DATA/resources/bcbio/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 109, in _setup_vm
>     configure_instance(options, actions)
>   File "/DATA/resources/bcbio/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 258, in configure_instance
>     install_biolinux(options)
>   File "/DATA/resources/bcbio/tmpbcbio-install/cloudbiolinux/cloudbio/deploy/__init__.py", line 282, in install_biolinux
>     _perform_install(target=target, flavor=flavor, more_custom_add=options.get("custom_add", None))
>   File "/DATA/resources/bcbio/tmpbcbio-install/cloudbiolinux/fabfile.py", line 120, in _perform_install
>     install_conda(flavor=flavor, automated=True)
>   File "/DATA/resources/bcbio/tmpbcbio-install/cloudbiolinux/fabfile.py", line 321, in install_conda
>     conda.install_packages(env, to_install=pkg_install)
>   File "/DATA/resources/bcbio/tmpbcbio-install/cloudbiolinux/cloudbio/package/conda.py", line 33, in install_packages
>     install_in(conda_bin, env.system_install, config_file.base, packages)
>   File "/DATA/resources/bcbio/tmpbcbio-install/cloudbiolinux/cloudbio/package/conda.py", line 88, in install_in
>     "{py_version} {pkgs_str}".format(**locals()), shell=True)
>   File "/DATA/resources/bcbio/anaconda/lib/python2.7/subprocess.py", line 190, in check_call
>     raise CalledProcessError(retcode, cmd)
> subprocess.CalledProcessError: Command 'export BOTO_CONFIG=/ignoreglobal && /DATA/resources/bcbio/anaconda/bin/conda install -y -n dv -c conda-forge -c bioconda python=2 'deepvariant'' returned non-zero exit status 1
> Traceback (most recent call last):
>   File "bcbio_nextgen_install.py", line 287, in <module>
>     main(parser.parse_args(), sys.argv[1:])
>   File "bcbio_nextgen_install.py", line 44, in main
>     subprocess.check_call([bcbio, "upgrade"] + _clean_args(sys_argv, args))
>   File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
>     raise CalledProcessError(retcode, cmd)
> subprocess.CalledProcessError: Command '['/DATA/resources/bcbio/anaconda/bin/bcbio_nextgen.py', 'upgrade', '--tooldir=/DATA/resources/bcbio/bcbcio_tools', '--genomes', 'GRCh37', '--aligners', 'bwa', '--aligners', 'bowtie2', '--data']' returned non-zero exit status 1
> ```

Hi Maarten,

I tried the following command several times and it finally worked for me. You can give it a try. 
```
export BOTO_CONFIG=/ignoreglobal && /home/zdjzyx01/local/share/bcbio/anaconda/bin/conda install -v -y -n dv -c conda-forge -c bioconda python=2 'deepvariant' 
```

Good luck!

Best,
Jianxiang

**Comment by slagtermaarten** [comment] 2019-02-20 13:10
Thanks Jianxiang! Unfortunately, that command did not solve my problem, I must have tried at least 10 times by now. I find the script's suggestion to include -v flag a bit weird as it's already in there? 
Thanks again.

```
Traceback (most recent call last):
  File "/DATA/resources/bcbio/anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 1002, in __call__
    return func(*args, **kwargs)
  File "/DATA/resources/bcbio/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 84, in _main
    exit_code = do_call(args, p)
  File "/DATA/resources/bcbio/anaconda/lib/python2.7/site-packages/conda/cli/conda_argparse.py", line 82, in do_call
    exit_code = getattr(module, func_name)(args, parser)
  File "/DATA/resources/bcbio/anaconda/lib/python2.7/site-packages/conda/cli/main_install.py", line 20, in execute
    install(args, parser, 'install')
  File "/DATA/resources/bcbio/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 271, in install
    handle_txn(unlink_link_transaction, prefix, args, newenv)
  File "/DATA/resources/bcbio/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 300, in handle_txn
    unlink_link_transaction.execute()
  File "/DATA/resources/bcbio/anaconda/lib/python2.7/site-packages/conda/core/link.py", line 241, in execute
    self._execute(tuple(concat(interleave(itervalues(self.prefix_action_groups)))))
  File "/DATA/resources/bcbio/anaconda/lib/python2.7/site-packages/conda/core/link.py", line 562, in _execute
    rollback_excs,
CondaMultiError: post-link script failed for package bioconda::deepvariant-0.7.2-py27h5d9141f_1
running your command again with `-v` will provide additional information
location of failed script: /DATA/resources/bcbio/anaconda/envs/dv/bin/.deepvariant-post-link.sh
==> script messages <==
<None>

~ cat /DATA/resources/bcbio/anaconda/envs/dv/bin/.deepvariant-post-link.sh
cat: /DATA/resources/bcbio/anaconda/envs/dv/bin/.deepvariant-post-link.sh: No such file or directory
```

**Comment by chapmanb** [comment] 2019-02-21 11:03
Sorry about the continued problems with this. Unfortunately the error message is not giving us much to go on. This is the script that we're trying to run to download the DeepVariant trained models:

https://github.com/bioconda/bioconda-recipes/blob/master/recipes/deepvariant/post-link.sh

If you could try running that manually, after adding `PREFIX=/DATA/resources/bcbio/anaconda/envs/dv` to the top of the file, it might give us some additional information to help figure out what is going wrong. Sorry again about the problems and thanks for the help debugging.

**Comment by slagtermaarten** [comment] 2019-02-21 18:59
Hi Rob, thanks for getting back to me. If you don't mind, what values
should I assign to
PKG_NAME, PKG_VERSION and PKG_BUILDNUM? The script complains about not
knowing PKG_NAME.
Thanks for developing and maintaining bcbio!

**Comment by slagtermaarten** [comment] 2019-02-21 19:33
Using arbitrary values for the aforementioned variables, the script complained that gsutil doesn't exist - it's nowhere to be found in the dv environment dir (/DATA/resources/bcbio/anaconda/envs/dv in my case)

**Comment by chapmanb** [comment] 2019-02-22 11:03
Maarten;
Thanks for following up and checking. That is strange that there is no `gsutil` in `/DATA/resources/bcbio/anaconda/envs/dv/bin`. It's a dependency of the deepvariant conda package and should be there. Could you try running:
```
/DATA/resources/bcbio/anaconda/bin/conda install -n dv -c conda-forge google-cloud-sdk
```
to install it inside that environment? Hopefully this will get it running and your analysis finished.

**Comment by slagtermaarten** [comment] 2019-02-28 09:26
Sorry for getting back to you so late! I either did not receive or did not notice a notification email from github about your post.

I installed gsutils the way you suggested and then had to change ownership of some config files (`sudo chown $(whoami) -R $HOME/.gsutil`) in order to run `post-link.sh` without sudo. Below is the version of `post-link.sh` I ran (I picked some arbitrary values for lack of something more informed). After this, I could successfully install bcbio. Thanks so much! 

```
#!/bin/bash
set -eu -o pipefail

PREFIX=/DATA/resources/bcbio/anaconda/envs/dv

MODEL_VERSION="0.7.2"
PKG_NAME="deepvariant"
PKG_VERSION="arbitrary"
PKG_BUILDNUM="14"

GSUTIL=$PREFIX/bin/gsutil
for MODEL_TYPE in wgs wes
do
        MODEL_NAME="DeepVariant-inception_v3-${MODEL_VERSION}+data-${MODEL_TYPE}_standard"
        GSREF="gs://deepvariant/models/DeepVariant/$MODEL_VERSION/$MODEL_NAME"
        OUTDIR=$PREFIX/share/$PKG_NAME-$PKG_VERSION-$PKG_BUILDNUM/models/DeepVariant/$MODEL_VERSION/$MODEL_NAME

        mkdir -p $OUTDIR
        $GSUTIL cp $GSREF/* $OUTDIR/
done
```

**Comment by chapmanb** [comment] 2019-02-28 19:13
Maarten;
Thanks for following up. I'm glad things worked and appreciate you letting us know the fix. It looks like even though gsutil won't need credentials for these public files:

https://download.huihoo.com/google/gdgdevkit/DVD1/developers.google.com/storage/docs/gsutil/addlhelp/AccessingPublicDataWithoutCredentials.html

It might practically try to look them up and was running into permissions issues. I'm not sure about a workaround for this now, but hopefully it won't hit too many people going forward. Thanks again.

**Comment by hmyh1202** [comment] 2019-04-10 06:50
[python27]$conda install --use-local deepvariant-0.7.2-py27h5d9141f_1.tar.bz2

Downloading and Extracting Packages
################################################################################################################# | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: \ ERROR conda.core.link:_execute_post_link_actions(658): An error occurred while installing package '<unknown>::deepvariant-0.7.2-py27h5d9141f_1'.
LinkError: post-link script failed for package <unknown>::deepvariant-0.7.2-py27h5d9141f_1
running your command again with `-v` will provide additional information
location of failed script: anaconda3/envs/python27/bin/.deepvariant-post-link.sh
==> script messages <==
<None>

Attempting to roll back.
                                                                                                                       failed
ERROR conda.core.link:_execute(568): An error occurred while installing package '<unknown>::deepvariant-0.7.2-py27h5d9141f_1'.
LinkError: post-link script failed for package <unknown>::deepvariant-0.7.2-py27h5d9141f_1
running your command again with `-v` will provide additional information
location of failed script: anaconda3/envs/python27/bin/.deepvariant-post-link.sh
==> script messages <==
<None>

Attempting to roll back.

Rolling back transaction: done

LinkError: post-link script failed for package <unknown>::deepvariant-0.7.2-py27h5d9141f_1
running your command again with `-v` will provide additional information
location of failed script: /anaconda3/envs/python27/bin/.deepvariant-post-link.sh
==> script messages <==
<None>

**Comment by dormeight** [comment] 2019-04-16 01:40
Hi Chapman, I encountered the same problem with deepvariant when I tried to start a fresh installation, I wonder if it is possible to ignore the deepvariant  package without destroying the whole installation.  I don't use this package, but the error occurs, the installation rolls back.    I just want to get other packages to work normally.

**Comment by roryk** [comment] 2019-04-16 17:40
@naumenko-sa do any of these work around get you moving?

**Comment by naumenko-sa** [comment] 2019-04-18 03:03
@roryk thanks, the installation went well after a couple of trials. deepvariant and models are installed. My issue most probably was because of another (old) gsutil in the PATH.

**Comment by roryk** [comment] 2019-04-18 15:10
Thanks for following up-- maybe that is why mine had this problem too!

**Closed** 2019-07-11 03:56 UTC

**Comment by bballew** [comment] 2019-10-18 03:00
Any updates on a programmatic fix for this?  The requirement to manually run `post-link.sh`, change file ownership, and attempt the installation several times really makes it difficult to use this conda package in a snakemake workflow that uses the `--use-conda` flag to create isolated conda environments on a per-rule basis.

**Comment by chapmanb** [comment] 2019-10-18 10:07
Bari;
Sorry about the automation issues with the deepvariant conda install. We're not sure of a way to completely isolate gsutil from the external environment and there are a number of underlying causes of the failure discussed in this thread: external boto configurations, permissions issues with the configuration directory, and intermittent network issues. Most of those are hard to automate. Do you know what is blocking your installs so you can isolate and see if we can avoid? Thanks for the help debugging.

**Comment by djb17** [comment] 2021-02-18 06:50
Hello,

Trying to figure out why the installation is failing right after conda finishes downloading the models with multiple iterations with above alternative approaches.

```
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
ERROR conda.core.link:_execute(700): An error occurred while installing package 'bioconda::deepvariant-1.0.0-py36hf5a246b_0'.
Rolling back transaction: done

LinkError: post-link script failed for package bioconda::deepvariant-1.0.0-py36hf5a246b_0
location of failed script: /storage/bcbio/anaconda/envs/dv/bin/.deepvariant-post-link.sh
==> script messages <==
<None>
==> script output <==
stdout: 
stderr: Copying gs://deepvariant/models/DeepVariant/0.10.0/DeepVariant-inception_v3-0.10.0+data-wgs_standard/model.ckpt.data-00000-of-00001...
WARNING: Found no hashes to validate object downloaded to /storage/bcbio/anaconda/envs/dv/share/deepvariant-1.0.0-0/models/DeepVariant/0.10.0/DeepVariant-inception_v3-0.10.0+data-wgs_standard/model.ckpt.data-00000-of-00001. Integrity cannot be assured witho
ut hashes.
Copying gs://deepvariant/models/DeepVariant/0.10.0/DeepVariant-inception_v3-0.10.0+data-wgs_standard/model.ckpt.index...
WARNING: Found no hashes to validate object downloaded to /storage/bcbio/anaconda/envs/dv/share/deepvariant-1.0.0-0/models/DeepVariant/0.10.0/DeepVariant-inception_v3-0.10.0+data-wgs_standard/model.ckpt.index. Integrity cannot be assured without hashes.
Copying gs://deepvariant/models/DeepVariant/0.10.0/DeepVariant-inception_v3-0.10.0+data-wgs_standard/model.ckpt.meta...
WARNING: Found no hashes to validate object downloaded to /storage/bcbio/anaconda/envs/dv/share/deepvariant-1.0.0-0/models/DeepVariant/0.10.0/DeepVariant-inception_v3-0.10.0+data-wgs_standard/model.ckpt.meta. Integrity cannot be assured without hashes.
| [3 files][357.9 MiB/357.9 MiB]                                                
Operation completed over 3 objects/357.9 MiB. 
Traceback (most recent call last):
  File "/storage/bcbio/anaconda/envs/dv/bin/../share/google-cloud-sdk-328.0.0-0/bin/bootstrapping/gsutil.py", line 133, in <module>
    exceptions.HandleError(e, 'gsutil')
  File "/storage/bcbio/anaconda/envs/dv/share/google-cloud-sdk-328.0.0-0/lib/googlecloudsdk/calliope/exceptions.py", line 551, in HandleError
    core_exceptions.reraise(exc)
  File "/storage/bcbio/anaconda/envs/dv/share/google-cloud-sdk-328.0.0-0/lib/googlecloudsdk/core/exceptions.py", line 146, in reraise
    six.reraise(type(exc_value), exc_value, tb)
  File "/storage/bcbio/anaconda/envs/dv/share/google-cloud-sdk-328.0.0-0/lib/third_party/six/__init__.py", line 693, in reraise
    raise value
  File "/storage/bcbio/anaconda/envs/dv/bin/../share/google-cloud-sdk-328.0.0-0/bin/bootstrapping/gsutil.py", line 131, in <module>
    main()
  File "/storage/bcbio/anaconda/envs/dv/bin/../share/google-cloud-sdk-328.0.0-0/bin/bootstrapping/gsutil.py", line 112, in main
    bootstrapping.ExecutePythonTool('platform/gsutil', 'gsutil', *args)
  File "/storage/bcbio/anaconda/envs/dv/share/google-cloud-sdk-328.0.0-0/bin/bootstrapping/bootstrapping.py", line 115, in ExecutePythonTool
    _FullPath(tool_dir, exec_name), *args, python=py_path))
  File "/storage/bcbio/anaconda/envs/dv/share/google-cloud-sdk-328.0.0-0/bin/bootstrapping/bootstrapping.py", line 205, in _ExecuteTool
    execution_utils.Exec(args + sys.argv[1:], env=_GetToolEnv())
  File "/storage/bcbio/anaconda/envs/dv/share/google-cloud-sdk-328.0.0-0/lib/googlecloudsdk/core/execution_utils.py", line 372, in Exec
    **extra_popen_kwargs)
  File "/storage/bcbio/anaconda/envs/dv/lib/python3.6/contextlib.py", line 88, in __exit__
    next(self.gen)
  File "/storage/bcbio/anaconda/envs/dv/share/google-cloud-sdk-328.0.0-0/lib/googlecloudsdk/core/execution_utils.py", line 270, in _ReplaceSignal
    signal.signal(signo, old_handler)
  File "/storage/bcbio/anaconda/envs/dv/lib/python3.6/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))

TypeError: signal handler must be signal.SIG_IGN, signal.SIG_DFL, or a callable object

return code: 1

()
```
