### ISSUE TITLE
TypeError: unsupported operand type(s) for +: 'bool' and 'list'

### ISSUE THREAD

**Issue by gis-nlsim** [bcbio/bcbio-nextgen#3094] opened 2020-02-17 01:05 UTC
Greetings,

Seeking you assistance in this issue that I'm facing:

I'm having bcbio break on all my samples because the application is trying to add bool and list.
This appears to happen after hla_typing. The following are my yaml file configuration, and the error

I have had this issue in both v1.0.7 and v1.1.19 installations. 

Thanks in advance.

**My yaml file:**
```
# SNV + SV calling
---
details:
- algorithm:
    platform: illumina
    quality_format: standard
    aligner: bwa
    save_diskspace: true
    tools_off: [fastqc]
    bam_clean: false
    bam_sort: false
    mark_duplicates: true
    recalibrate: false
    realign: false
    variant_regions: None
    remove_lcr: false
    variantcaller:
      somatic: [freebayes,vardict,varscan,strelka2,mutect2]
      germline: false
    ensemble:
      numpass: 2
    svcaller: [cnvkit]
    indelcaller: false
  analysis: variant2
  description: PATIENTID-N
  files: NORMAL_BAM
  genome_build: GRCh37
  metadata:
    batch: PATIENTID
    phenotype: normal
fc_date: 'xxxx-xx-xx'
fc_name: PATIENTID
upload:
  dir: ../bcbio_final
```

**The error is as follows**
```
[2020-02-15T22:35Z] Correcting for GC bias...
[2020-02-15T22:35Z] Correcting for density bias...
[2020-02-15T22:35Z] Processing antitarget: xxxx
[2020-02-15T22:35Z] Keeping 9080 of 9506 bins
[2020-02-15T22:35Z] Correcting for GC bias...
[2020-02-15T22:35Z] Correcting for RepeatMasker bias...
[2020-02-15T22:35Z] Targets are 1.65 x more variable than antitargets
[2020-02-15T22:35Z] Wrote /path/to/workdir/bcbiotx/tmp73io28ro/xxxx-T-normalized.cnr with 630950 regions
[2020-02-15T22:35Z] Timing: hla typing
Traceback (most recent call last):
  File "/xxxxx/bcbio/v1.1.9/anaconda/bin/bcbio_nextgen.py", line 245, in <module>
    main(**kwargs)
  File "/xxxxx/bcbio/v1.1.9/anaconda/bin/bcbio_nextgen.py", line 46, in main
    run_main(**kwargs)
  File "/xxxxx/bcbio/v1.1.9/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 50, in run_main
    fc_dir, run_info_yaml)
  File "/xxxxx/bcbio/v1.1.9/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 91, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/xxxxx/bcbio/v1.1.9/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 150, in variant2pipeline
    multiplier=region.get_max_counts(samples), max_multicore=1) as run_parallel:
  File "/xxxxx/bcbio/v1.1.9/anaconda/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/xxxxx/bcbio/v1.1.9/anaconda/lib/python3.6/site-packages/bcbio/distributed/prun.py", line 43, in start
    max_multicore=max_multicore)
  File "/xxxxx/bcbio/v1.1.9/anaconda/lib/python3.6/site-packages/bcbio/distributed/resources.py", line 175, in calculate
    progs = _get_resource_programs(parallel.get("progs", []), algs)
  File "/xxxxx/bcbio/v1.1.9/anaconda/lib/python3.6/site-packages/bcbio/distributed/resources.py", line 32, in _get_resource_programs
    if fn(algs):
  File "/xxxxx/bcbio/v1.1.9/anaconda/lib/python3.6/site-packages/bcbio/distributed/resources.py", line 59, in run
    vcs = reduce(operator.add, vcs.values())
TypeError: unsupported operand type(s) for +: 'bool' and 'list'
```

**Comment by chapmanb** [comment] 2020-02-19 02:14
Thanks much for the report and apologies about the issue. I believe the problem is this line in the configuration:
```
germline: false
```
That's meant to be a list or left blank. If you make it an empty list:
```
germline: []
```
or just remove it, hopefully all will run cleanly. Hope this gets your analysis working.

**Comment by gis-nlsim** [comment] 2020-02-19 02:24
Thank you so much for your help!

Regards,
Sim Ngak Leng
Senior Bioinformatics Specialist
Computational & Systems Biology 3

Genome Institute of Singapore
Agency for Science, Technology and Research
60 Biopolis Street, Genome, #03-01, Singapore 138672
D +65 6808 8013  T +65 6808 8000  E simngl@gis.a-star.edu.sg<mailto:simngl@gis.a-star.edu.sg>  W www.a-star.edu.sg/gis<http://www.a-star.edu.sg/gis>
[a-star-logo]

**Comment by naumenko-sa** [comment] 2020-02-19 19:55
Thanks, Brad! Closing for now. 
@gis-nlsim Let us know if you see any other issues!

**Closed by naumenko-sa** 2020-02-19 19:55 UTC
