### ISSUE TITLE
No VEP annotation with `effects: vep`

### ISSUE THREAD

**Issue by FedericoComoglio** [bcbio/bcbio-nextgen#2960] opened 2019-09-30 09:07 UTC
Hi everyone,

after upgrading `bcbio` to the lastest `-u development` (upgrading both tools and data, VEP build 97), our germline variant calling pipeline completes without errors. However, we noticed that the output VCF files no longer contain VEP annotations. No `*-vepeffects-annotated.vcf.gz` file is generated (only `*-annotated.vcf.gz` is present). The `bcbio-nextgen-debug.log` contains no call to the Ensembl variant effect predictor (in contrast to previous runs where VEP annotations were correctly returned).

In the config file, we tested both `effects: vep` and `effects: [vep]` (as a list) with no success (both return no VEP annotation).

A perhaps unrelated observation worth mentioning is that we noticed `data/genomes/Hsapiens/hg38/vep/homo_sapiens_merged/` build 96 contains a significantly larger number of files than build 97 (16,167 vs 11,769). We assume `bcbio` always uses the latest build for annotation.

It would be great if you could look into this issue. Please let us know if we can be of help.
Thanks a lot in advance,

Federico

**Comment by naumenko-sa** [comment] 2019-10-02 18:22
Hi @FedericoComoglio !

Thanks for reporting the issue! I'm upgrading VEP to reproduce it.
Are you sure that your upgrade of VEP
```bcbio_nextgen.py upgrade -u skip --genomes hg38 --datatarget vep```
finished successfully?

Sergey

**Comment by FedericoComoglio** [comment] 2019-10-02 19:20
Hi Sergey,

the upgrade completed successfully as far as I can tell. Let me know if you suggest I should re-run it at the end.

Thanks,
Federico

**Comment by FedericoComoglio** [comment] 2019-10-03 09:06
Hi @naumenko-sa, 

I ran a quick test. I deleted the VEP files (for build 97) from the current bcbio installation and upgraded with 

```
bcbio_nextgen.py upgrade -u skip --genomes hg38 --datatarget vep
```

The download completed successfully, and the number of files we obtain is exactly the same as before. 
Hope this helps.

Thank you!
Federico

**Comment by naumenko-sa** [comment] 2019-10-06 03:11
Hi @FedericoComoglio !

Sorry for being so slow. My installation attempt of vep cache has even failed. I figured out, why - we have many VEP caches for many genomes and versions, bcbio upgrades all of them automatically (which is a convenient feature, not a bug), one of the old ones failed, so it has not even started to download b97 for hg38. Now I'm sure I'm installing build 97 for hg38, ETA is 10h - quite slow from here to Ensembl.

In the meanwhile, could you please
1) make sure which vep you are using (hopefully, no other VEPs on your system?)
```which vep```

2) check  vep version:
```vep```

3) test your vep from the command line with a small vcf file? 
I.e. take your vep command line from bcbio-nextgen-commands.log and adapt the command line to your path, or modify this example https://github.com/naumenko-sa/cre/blob/master/cre.vep.sh. I.e. to check whether vep works at all in your system.

4) Upload your config.yaml and bcbio-nextgen-commands.log somewhere.

In the meanwhile Ensembl released build 98, we'll discuss it next week and most probably upgrade to it. 

Sergey

**Comment by FedericoComoglio** [comment] 2019-10-07 07:37
Hi Sergey,

thanks a lot for looking into this. Yes, I experienced the same when upgrading, no worries.
I also looked more into the issue, and it seems our VEP installation is incomplete. Simply running `./vep --help` returns

```
Can't locate DBI.pm in @INC (you may need to install the DBI module) (@INC contains: /mnt/data/anaconda/share/ensembl-vep-97.4-0/modules /mnt/data/anaconda/share/ensembl-vep-97.4-0 /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.26.2 /usr/local/share/perl/5.26.2 /usr/lib/x86_64-linux-gnu/perl5/5.26 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.26 /usr/share/perl/5.26 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /mnt/data/anaconda/share/ensembl-vep-97.4-0/Bio/EnsEMBL/DBSQL/DBConnection.pm line 74.
BEGIN failed--compilation aborted at /mnt/data/anaconda/share/ensembl-vep-97.4-0/Bio/EnsEMBL/DBSQL/DBConnection.pm line 74.
Compilation failed in require at /mnt/data/anaconda/share/ensembl-vep-97.4-0/Bio/EnsEMBL/DBSQL/DBAdaptor.pm line 69.
BEGIN failed--compilation aborted at /mnt/data/anaconda/share/ensembl-vep-97.4-0/Bio/EnsEMBL/DBSQL/DBAdaptor.pm line 69.
Compilation failed in require at /mnt/data/anaconda/share/ensembl-vep-97.4-0/Bio/EnsEMBL/Registry.pm line 137.
BEGIN failed--compilation aborted at /mnt/data/anaconda/share/ensembl-vep-97.4-0/Bio/EnsEMBL/Registry.pm line 137.
Compilation failed in require at /mnt/data/anaconda/share/ensembl-vep-97.4-0/modules/Bio/EnsEMBL/VEP/BaseVEP.pm line 58.
BEGIN failed--compilation aborted at /mnt/data/anaconda/share/ensembl-vep-97.4-0/modules/Bio/EnsEMBL/VEP/BaseVEP.pm line 58.
Compilation failed in require at /usr/share/perl/5.26/base.pm line 136.
	...propagated at /usr/share/perl/5.26/base.pm line 158.
BEGIN failed--compilation aborted at /mnt/data/anaconda/share/ensembl-vep-97.4-0/modules/Bio/EnsEMBL/VEP/BaseRunner.pm line 56.
Compilation failed in require at /usr/share/perl/5.26/base.pm line 136.
	...propagated at /usr/share/perl/5.26/base.pm line 158.
BEGIN failed--compilation aborted at /mnt/data/anaconda/share/ensembl-vep-97.4-0/modules/Bio/EnsEMBL/VEP/Runner.pm line 71.
Compilation failed in require at /mnt/tools/bin/vep line 20.
BEGIN failed--compilation aborted at /mnt/tools/bin/vep line 20.
```

**Comment by naumenko-sa** [comment] 2019-10-09 04:21
Hi @FedericoComoglio !

So maybe you'd need to fix vep script first (program), 
and the issue is here rather than in the vep cache (data)?

Make sure that bcbio's perl comes first in your PATH, before the system perl

```
which perl
/n/app/bcbio/dev/anaconda/bin/perl
vep
Possible precedence issue with control flow operator at /n/app/bcbio/dev/anaconda/lib/site_perl/5.26.2/Bio/DB/IndexedBase.pm line 805.
#----------------------------------#
# ENSEMBL VARIANT EFFECT PREDICTOR #
#----------------------------------#

Versions:
  ensembl              : 97.378db18
  ensembl-funcgen      : 97.24f4d3c
  ensembl-io           : 97.dc917e1
  ensembl-variation    : 97.26a059c
  ensembl-vep          : 97.3

Help: dev@ensembl.org , helpdesk@ensembl.org
Twitter: @ensembl

http://www.ensembl.org/info/docs/tools/vep/script/index.html

Usage:
./vep [--cache|--offline|--database] [arguments]

Basic options
=============

--help                 Display this message and quit

-i | --input_file      Input file
-o | --output_file     Output file
--force_overwrite      Force overwriting of output file
--species [species]    Species to use [default: "human"]
                       
--everything           Shortcut switch to turn on commonly used options. See web
                       documentation for details [default: off]                       
--fork [num_forks]     Use forking to improve script runtime

For full option documentation see:
http://www.ensembl.org/info/docs/tools/vep/script/vep_options.html
```
When it is system perl, I see an error similar to yours:

```
bash-4.2$ which perl
/bin/perl
bash-4.2$ vep
Can't locate Bio/PrimarySeqI.pm in @INC (@INC contains: /n/app/bcbio/dev/anaconda/share/ensembl-vep-97.3-0/modules /n/app/bcbio/dev/anaconda/share/ensembl-vep-97.3-0 /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /n/app/bcbio/dev/anaconda/share/ensembl-vep-97.3-0/Bio/EnsEMBL/Slice.pm line 75.
BEGIN failed--compilation aborted at /n/app/bcbio/dev/anaconda/share/ensembl-vep-97.3-0/Bio/EnsEMBL/Slice.pm line 75.
Compilation failed in require at /n/app/bcbio/dev/anaconda/share/ensembl-vep-97.3-0/Bio/EnsEMBL/Feature.pm line 84.
BEGIN failed--compilation aborted at /n/app/bcbio/dev/anaconda/share/ensembl-vep-97.3-0/Bio/EnsEMBL/Feature.pm line 84.
Compilation failed in require at /n/app/bcbio/dev/anaconda/share/ensembl-vep-97.3-0/Bio/EnsEMBL/Variation/BaseVariationFeature.pm line 58.
BEGIN failed--compilation aborted at /n/app/bcbio/dev/anaconda/share/ensembl-vep-97.3-0/Bio/EnsEMBL/Variation/BaseVariationFeature.pm line 58.
Compilation failed in require at /n/app/bcbio/dev/anaconda/share/ensembl-vep-97.3-0/Bio/EnsEMBL/Variation/VariationFeature.pm line 97.
BEGIN failed--compilation aborted at /n/app/bcbio/dev/anaconda/share/ensembl-vep-97.3-0/Bio/EnsEMBL/Variation/VariationFeature.pm line 97.
Compilation failed in require at /n/app/bcbio/dev/anaconda/share/ensembl-vep-97.3-0/Bio/EnsEMBL/Variation/DBSQL/VariationFeatureAdaptor.pm line 89.
BEGIN failed--compilation aborted at /n/app/bcbio/dev/anaconda/share/ensembl-vep-97.3-0/Bio/EnsEMBL/Variation/DBSQL/VariationFeatureAdaptor.pm line 89.
Compilation failed in require at /n/app/bcbio/dev/anaconda/share/ensembl-vep-97.3-0/modules/Bio/EnsEMBL/VEP/BaseVEP.pm line 59.
BEGIN failed--compilation aborted at /n/app/bcbio/dev/anaconda/share/ensembl-vep-97.3-0/modules/Bio/EnsEMBL/VEP/BaseVEP.pm line 59.
Compilation failed in require at (eval 3) line 2.
	...propagated at /usr/share/perl5/base.pm line 84.
BEGIN failed--compilation aborted at /n/app/bcbio/dev/anaconda/share/ensembl-vep-97.3-0/modules/Bio/EnsEMBL/VEP/BaseRunner.pm line 56.
Compilation failed in require at (eval 2) line 2.
	...propagated at /usr/share/perl5/base.pm line 84.
BEGIN failed--compilation aborted at /n/app/bcbio/dev/anaconda/share/ensembl-vep-97.3-0/modules/Bio/EnsEMBL/VEP/Runner.pm line 71.
Compilation failed in require at /n/app/bcbio/tools/bin/vep line 20.
BEGIN failed--compilation aborted at /n/app/bcbio/tools/bin/vep line 20.
```

Let me know, if this helps at all. My VEP cache is still installing.

Sergey

**Comment by FedericoComoglio** [comment] 2019-10-09 07:51
Hi @naumenko-sa, spot on. This makes perfect sense.

Executing `vep` using bcbio's `perl` works.

```
/mnt/data/anaconda/bin/perl /mnt/tools/bin/vep
Possible precedence issue with control flow operator at /mnt/data/anaconda/lib/site_perl/5.26.2/Bio/DB/IndexedBase.pm line 805.
#----------------------------------#
# ENSEMBL VARIANT EFFECT PREDICTOR #
#----------------------------------#

Versions:
  ensembl              : 97.378db18
  ensembl-funcgen      : 97.24f4d3c
  ensembl-io           : 97.dc917e1
  ensembl-variation    : 97.26a059c
  ensembl-vep          : 97.4

Help: dev@ensembl.org , helpdesk@ensembl.org
Twitter: @ensembl

http://www.ensembl.org/info/docs/tools/vep/script/index.html

Usage:
./vep [--cache|--offline|--database] [arguments]

[...]
```

Not suprisingly, the system perl has indeed precedence in `PATH`. I should have realized this. Let me fix this and test your solution.

Thanks a lot!

**Comment by FedericoComoglio** [comment] 2019-10-29 08:09
Hi everyone,

@naumenko-sa I am sorry to reopen this issue but we jumped to conclusions a little too quickly. The fix above resulted in the successful completion of our runs. However, no VEP annotated VCF was generated and no call to variant effect predictor can be found in the log files. The fact that we got no error message/warning about this misled us, and we only had time later last week to look more into the output.

Could we try to figure out where the issue might be again?

Thank you so much!
Federico

**Comment by FedericoComoglio** [comment] 2019-11-07 11:53
Hi, do you have any update on this issue? We are stuck, and it would be nice to try out a few things to fix it. Let me know!

Thank you so much!

**Comment by naumenko-sa** [comment] 2020-01-15 18:57
Hi @FedericoComoglio !

Sorry, I missed you comment on this.
Have you resolved the issues in your bcbio installation?

I've just ran:
```
details:
- algorithm:
    effects: vep
    effects_transcripts: all
    tools_on:
    - gemini
    - vep_splicesite_annotations
    - noalt_calling
    aligner: bwa
    realign: false
    recalibrate: false
    mark_duplicates: true
    save_diskspace: true
    variantcaller: gatk-haplotype
  analysis: variant2
  description: 'test'
  files:
  - /n/data1/cores/bcbio/naumenko/issue_2960_vep/input/test_1.fq.gz
  - /n/data1/cores/bcbio/naumenko/issue_2960_vep/input/test_2.fq.gz
  genome_build: hg38
resources:
  default:
    cores: 7
    jvm_opts:
    - -Xms750m
    - -Xmx7000m
    memory: 7G
upload:
  dir: ../final
```

and got a `final/project/test-gatkhaplotype-annotated-decomposed.vcf.gz` having CSQ field from VEP98.

Let me know if you still have issues.

Sergey

**Comment by naumenko-sa** [comment] 2020-05-17 15:47
closing, feel free to re-open if it does not work.

**Closed by naumenko-sa** 2020-05-17 15:47 UTC
