### ISSUE TITLE
Samtools variant call error

### ISSUE THREAD

**Issue by sysbiocoder** [bcbio/bcbio-nextgen#3525] opened 2021-08-30 12:39 UTC
**Version info**
- bcbio version (`bcbio_nextgen.py --version`):
- OS name and version (`lsb_release -ds`):

**To Reproduce**
Exact bcbio command you have used:
```
bcbio_nextgen.py ../config/calling.yaml -n 36

```
Your sample configuration file:
```
upload:
  dir: ../final
details:
  - files: [NA12878_S14_R1_001.fastq.gz, NA12878_S14_R2_001.fastq.gz]
    description: NA12878
    metadata:
      sex: female
      batch: batch1
    analysis: variant2
    genome_build: hg38
    algorithm:
      aligner: bwa
      tools_on: true
      mark_duplicates: true
      variantcaller: [samtools]    
      remove_lcr: true
      quality_format: Standard
      coverage_interval: regional
      recalibrate: false
      merge_bamprep: true
      variant_regions: Exome_plus_RefSeq_Gencode_targets_hg38_plus10.bed
      clinical_reporting: true
```

**Observed behavior**
Error message or bcbio output:
```

```/opt/bcbio/stable/anaconda/bin/bcftools mpileup -f /opt/bcbio/stable/genomes/Hsapiens/hg38/seq/hg38.fa -d 8000 -a DP -a AD -R /home/hg3810bp/config/samtools/chrY/batch1-chrY_57082132_57227415-regions-nolcr.bed /home/hg3810bp/config/align/NA12878/NA12878-sort.bam | /opt/bcbio/stable/anaconda/bin/bcftools call -v -m - | awk -F$'\t' -v OFS='\t' '{if ($0 !~ /^#/) gsub(/[KMRYSWBVHDXkmryswbvhdx]/, "N", $4) } \
 {print}' | awk -F$'\t' -v OFS='\t' '{if ($0 !~ /^#/) gsub(/[KMRYSWBVHDXkmryswbvhdx]/, "N", $5) } {print}' | vt normalize -n -q -r /opt/bcbio/stable/genomes/Hsapiens/hg38/seq/hg38.fa - | sed 's/VCFv4.2/VCFv4.1/' | \
 sed 's/,Version=3>/>/' | sed 's/,Version="3">/>/' | sed 's/Number=R/Number=./' | bgzip -c > /home/hg3810bp/config/bcbiotx/tmpvbk7wqdr/batch1-chrY_57082132_57227415.vcf.gz


Failed to open -: unknown file type
[bcf_ordered_reader.cpp:49 BCFOrderedReader] Not a VCF/BCF file: -
```

**Expected behavior**

**Log files**
[bcbio-nextgen.log.issue3525.txt](https://github.com/bcbio/bcbio-nextgen/files/7108052/bcbio-nextgen.log.issue3525.txt)

**Comment by naumenko-sa** [comment] 2021-09-03 19:14
Hi @sysbiocoder !

1. What is your bcbio version?
2. Have you tried to re-run the failed bcbio run (just in case it is a filesystem error)?
3. Could you check the coverage in chrY_57082132_57227415 region?

Sergey

**Comment by sysbiocoder** [comment] 2021-09-06 12:15
Hi Sergey,
Thanks for replying me. 
1. Current bcbio version is 1.2.9a, 
2.   It  works when I donot filter lcr_regions although the problematic region is included. I have tried removing this region from the bed file and filter lcr regions then it runs completely without error. It donot work when filter lcr_regions on including the problematic region.
3.I checked for coverage and  I am not able to find it as the region is missing in bam file. 
Is that the cause of error. Earlier I was using version 1.2.3 for the same files, It didnot produce any error. Now I am trying to run it in a new server to reproduce result. Please suggest me if I need to downgrade to version 1.2.3 or I am missing something?

Other version comparisons under variation that are different in 2 installations
old version
ensembl: homo_sapiens_merged_vep_96_GRCh38
purecn_mappability: missing
af_only_gnomad.vcf.gz: missing
simple_repeat: missing
version: 37
New version
ensembl: homo_sapiens_merged_vep_100_GRCh38
purecn_mappability: GCA_000001405.15_GRCh38_no_alt_analysis_set_100.bw
 version: 45
af_only_gnomad.vcf.gz
simple_repeat

**Comment by naumenko-sa** [comment] 2021-09-17 22:45
Hi @sysbiocoder !

Thanks for the follow up! So, the issue is when `remove_lcr: true` the region `chrY_57082132_57227415` is included in the bed file, and bcbio is of the latest version.

I've noticed that `chrY_57082132_57227415` is exactly in the end of chrY in hg38:
https://genome.ucsc.edu/cgi-bin/hgTracks?chromInfoPage=
So maybe it is a boundary effect bug?

You may try to use another interval in the bed file, like chrY_57082132_57227000

Please don't downgrade to 1.2.3 - that might bring some bugs unsolved at the time.

Sergey

**Comment by naumenko-sa** [comment] 2021-11-25 22:15
closing, feel free to re-open if there is still an issue!

**Closed by naumenko-sa** 2021-11-25 22:15 UTC
