### ISSUE TITLE
joint-genotyping for SVs

### ISSUE THREAD

**Issue by brentp** [bcbio/bcbio-nextgen#1483] opened 2016-07-20 19:46 UTC
I believe I have my yaml set up correctly, with the same batch for all samples; I was expecting to get a single, multi-sample SV-VCF out but I get many single-sample VCFs.

Is this by design or did I do something wrong?

I think @cc2qe has a new version of svtyper in the works that will work much faster with many samples.

**Comment by chapmanb** [comment] 2016-07-20 20:00
Brent;
Is this for SV variant calling with lumpy? We call variants together with lumpy in a batch but genotype separately, so this is the current expected behavior.

It's done this way because of speed issues with svtyper. The current logic is here:

https://github.com/chapmanb/bcbio-nextgen/blob/02fe5913ce6016295b3c52b796470e77d88cdff1/bcbio/structural/lumpy.py#L127

and we don't genotype breakends by default because of similar speed issues. If either of these are improved now it would be great to revisit.

**Comment by brentp** [comment] 2016-07-26 21:27
Hi Brad, 
yes, this is for SV calling with lumpy.
a number of questions.

1. How are the samples batched? We'd like to be able to batch by family_id from the ped. (Or I guess I could just specify the family_id as the batch variable in the yaml).

2. Yes, I believe the svtyper is much faster, but it could be a config option to request the joint-genotyping. If I were to implement that in bcbio-nextgen, how/where would put that in the yaml?

3. I'd like the lumpy caller to use cnvkit calls as input if they are available. That is just added to lumpyexpress. Could I make it the default that if the yaml specifies: [cnvkit, lumpy] then lumpy will use the cnvkit calls as input?

I haven't looked at how to actually implement this, just getting the pieces together with lumpyexpress et al, but would like to have a look ASAP.

**Comment by chapmanb** [comment] 2016-07-27 13:52
Brent;
Thanks for all this, happy to help with more specifics as this moves forward. Tackling your questions:

1. If you're using templating to build your bcbio configuration (http://bcbio-nextgen.readthedocs.io/en/latest/contents/configuration.html#automated-sample-configuration) and have a `ped` file in the CSV file, it will read the family_id from the PED and assign it automatically to batch, so should do what you need in building the YAML.
2. I'd suggest adding `tools_on: [sv-joint-genotype]` as the option to turn it on. We already have a `bnd-genotype` target for lumpy now (http://bcbio-nextgen.readthedocs.io/en/latest/contents/configuration.html#post-processing).
3. That sounds perfect. As long as there is no significant downside happy to have it just do this.

Thanks for working on this, let us know how we can help.

**Comment by brentp** [comment] 2016-08-18 16:52
so I have updated lumpy to support some of what I need to do this in bcbio, it looks like the lumpy dependency is handled by brew via cloudbiolinux, is that correct? or can I just update the bioconda recipe.

Also, I assume when running lumpy, I can just check in the "final" (upload) directory if the appropriate cnvkit file exists and use that as the depth argument to lumpy. Is there an example of how to do that?

I'll also need to run `lumpy/scripts/cnvantor_to_bedpes.py` how would I find that?

**Comment by brentp** [comment] 2016-08-19 16:54
@chapmanb @roryk pointers?

**Comment by roryk** [comment] 2016-08-19 17:04
Hi Brent,

To run `cnvantor_to_bedpes.py`, if it gets installed as a script it should be findable using the config_utils.get_program call:

```
cnvantor_path = config_utils.get_program("cnvantor_to_bedpes.py", data)
```

I'm not sure off the top of my head how to look at the upload directory though.

**Comment by roryk** [comment] 2016-08-19 17:07
Lumpy looks like it is via the `conda` package so just updating the bioconda recipe works. I think we're off homebrew completely.

**Comment by chapmanb** [comment] 2016-08-19 17:15
Brent;
Rory is right on -- we use the conda package for lumpy so just need to get that up to date with your latest improvements. We use bioconda for all dependencies now.

For finding the lumpy scripts, it's going to be a bit trickier since they're in a shared script directory. I'd suggest changing the recipe to symlink the ones you need into the `bin` directory alongside lumpy so they're generally available. I can push the lumpy bioconda changes if that would help.

We'll need to do some re-working to make CNVkit available to lumpy. Right now all of the structural variant callers run in parallel so CNVkit isn't guaranteed to run before lumpy. We'll need to fix that to guarantee CNVkit happens first, then you can use the `sv` keyword in the world object to pull out the CNVkit calls (`variantcaller == "cnvkit"`):

https://github.com/chapmanb/bcbio-nextgen/blob/master/bcbio/heterogeneity/__init__.py#L19

Hope this helps with direction, happy to work with you on expanding bcbio to support this.

**Comment by brentp** [comment] 2016-08-19 17:27
thanks guys. I have updated the lumpy recipe here: https://github.com/bioconda/bioconda-recipes/pull/2183
let me know if it needs anything else. With that change cnvnator_to_bedpes should be on $PATH, right?

I'm looking into the bcbio changes now.

**Comment by brentp** [comment] 2016-08-19 19:54
I have made a start to this here: https://github.com/brentp/bcbio-nextgen/tree/lumpy-cnvkit

**Comment by chapmanb** [comment] 2016-08-21 10:04
Brent -- thanks much for all the details and getting started on this. I pushed improvements that implement most of the infrastructure for this: ensuring CNVkit gets run first, calling `cnvanator_to_bedpe.py` and passing the resulting deletion and duplication files to the lumpyexpress run command as `previous_evidence`. This still needs two tweaks I'm not sure how to do:

- How do you determine breakpoint size for `cnvanator_to_bedpe.py`?
- How do deletions/duplications get combined prior to passing to lumpyexpress `-d`? Concatenation or something else?

Hopefully this is a good start for making this possible. Thanks again for heading this up.

**Comment by brentp** [comment] 2016-08-21 14:06
Great! Thanks Brad. For you questions, 

1. use the default in the script. Lumpy will use reads in the window deteremined by +/- size around breakpoint
2. I believe that you pass the dels and dups comma-delimited to lumpyexpress  via:
```
        -d $SAMPLE,$DEL,$SAMPLE:$DUP
```
@ryanlayer, can you verify? 
These will be given a weight of 4 by my new changes to lumpyexpress.

**Comment by chapmanb** [comment] 2016-08-22 09:50
Brent and Ryan -- thanks for looking at this. For the two questions:

1. `cnvanator_to_bedpes.py` doesn't have a default for breakpoint_size. Happy for any suggestions about the logic for best choosing this.
2. I implemented `-d` with multiple files per sample if present (and non-empty).

I'll try to run on some test sets but it would be great if you could take it for a spin and report any issues. Thanks for the help integrating this.

**Comment by brentp** [comment] 2016-08-23 17:09
For 1. cnvnator takes a window size that determines the granularity of the copy-number. If there is something similar for cnvkit (maybe `--average-size` ?), then use that.

I will run on some of our samples as it is now in master and get back to you.

**Comment by chapmanb** [comment] 2016-08-23 19:23
Brent -- great to hear, I used 250 which is the `--average-size` default in CNVkit for binning, so hopefully this is a reasonable setting. Thanks for testing this and let me know if you run into any problems or would like tweaks.

**Comment by roryk** [comment] 2019-08-10 17:34
Thanks, looks like this got implemented and is all good.

**Closed by roryk** 2019-08-10 17:34 UTC
