### ISSUE TITLE
Scanner Error when attempting to install genomes

### ISSUE THREAD

**Issue by gis-nlsim** [bcbio/bcbio-nextgen#3180] opened 2020-04-11 11:49 UTC
Hi,
I've installed bcbio without adding any genomes, and now when I tried to add a genome using upgrade, I encountered a yaml.scanner.ScannerError: mapping values are not allowed here error.

[xxx@n111 tools]$ bcbio_nextgen.py upgrade -u stable --tools --data --genomes hg38
Upgrading bcbio
Traceback (most recent call last):
  File "/mnt/projects/xxx/wgs/tools/bcbio/anaconda/bin/bcbio_nextgen.py", line 228, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/mnt/projects/xxx/wgs/tools/bcbio/anaconda/lib/python3.6/site-packages/bcbio/install.py", line 70, in upgrade_bcbio
    _update_conda_packages()
  File "/mnt/projects/xxx/wgs/tools/bcbio/anaconda/lib/python3.6/site-packages/bcbio/install.py", line 285, in _update_conda_packages
    channels = _get_conda_channels(conda_bin)
  File "/mnt/projects/xxx/wgs/tools/bcbio/anaconda/lib/python3.6/site-packages/bcbio/install.py", line 268, in _get_conda_channels
    config = yaml.safe_load(subprocess.check_output([conda_bin, "config", "--show"]))
  File "/mnt/projects/xxx/wgs/tools/bcbio/anaconda/lib/python3.6/site-packages/yaml/__init__.py", line 162, in safe_load
    return load(stream, SafeLoader)
  File "/mnt/projects/xxx/wgs/tools/bcbio/anaconda/lib/python3.6/site-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/mnt/projects/xxx/wgs/tools/bcbio/anaconda/lib/python3.6/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/mnt/projects/xxx/wgs/tools/bcbio/anaconda/lib/python3.6/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/mnt/projects/xxx/wgs/tools/bcbio/anaconda/lib/python3.6/site-packages/yaml/composer.py", line 58, in compose_document
    self.get_event()
  File "/mnt/projects/xxx/wgs/tools/bcbio/anaconda/lib/python3.6/site-packages/yaml/parser.py", line 118, in get_event
    self.current_event = self.state()
  File "/mnt/projects/xxx/wgs/tools/bcbio/anaconda/lib/python3.6/site-packages/yaml/parser.py", line 193, in parse_document_end
    token = self.peek_token()
  File "/mnt/projects/xxx/wgs/tools/bcbio/anaconda/lib/python3.6/site-packages/yaml/scanner.py", line 129, in peek_token
    self.fetch_more_tokens()
  File "/mnt/projects/xxx/wgs/tools/bcbio/anaconda/lib/python3.6/site-packages/yaml/scanner.py", line 223, in fetch_more_tokens
    return self.fetch_value()
  File "/mnt/projects/xxx/wgs/tools/bcbio/anaconda/lib/python3.6/site-packages/yaml/scanner.py", line 579, in fetch_value
    self.get_mark())
yaml.scanner.ScannerError: mapping values are not allowed here
  in "<byte string>", line 19, column 15:
            GitHub:  https://github.com/QuantStack ...

**Comment by naumenko-sa** [comment] 2020-04-11 19:30
Hi @gis-nlsim !

Sorry about the issues.

It seems that the error is when it updates bcbio to the latest stable `upgrade bcbio`.
What is your bcbio_nextgen version? There was a short lived version which had an installer issue.

Could you please update to 1.2.3 (install from scratch since you don't have data)?

Sergey

**Comment by gis-nlsim** [comment] 2020-04-11 21:38
Thank you for your reply; the bcbio version is v1.2.3. Should I wait for v1.2.4 instead?

[xxx@n111 tools]$ bcbio_nextgen.py --version
1.2.3
[xxx@n111 tools]$

Regards,
N L Sim

**Comment by naumenko-sa** [comment] 2020-04-13 18:27
Hi @gis-nlsim!

No, v1.2.3 should be fine, let us debug.

1. How did you install bcbio?

2. What happens if you run `bcbio_nextgen.py upgrade -u skip --genomes hg38 --aligners bwa`
(skipping the upgrade of code and tools and upgrading only hg38 bwa index).

Sergey

**Comment by naumenko-sa** [comment] 2020-04-13 19:08
I now can reproduce with 1.2.3.

- `bcbio_nextgen.py upgrade -u stable` gives this error
- `bcbio_nextgen.py upgrade -u skip --genomes hg38 aligners bwa`  passes ok

So @gis-nlsim  you may upgrade data while we are fixing this error.

**Comment by naumenko-sa** [comment] 2020-04-13 19:28
I see, why:
we started using mamba here
https://github.com/bcbio/bcbio-nextgen/blob/master/bcbio/install.py#L282
but mamba is not supporting `mamba config --show`
https://github.com/bcbio/bcbio-nextgen/blob/master/bcbio/install.py#L268

**Comment by naumenko-sa** [comment] 2020-04-13 21:10
pushed a fix, can you please try 
`bcbio_nextgen.py upgrade -u development` 
or install from scratch? 

Also attn @mjsteinbaugh

**Comment by gis-nlsim** [comment] 2020-04-14 00:16
Thank you.

I did try yesterday around 3pm (Singapore time) but it’s still giving me the QuantStack error. I’ll try again with development.

yaml.scanner.ScannerError: mapping values are not allowed here
  in "<byte string>", line 19, column 15:
            GitHub:  https://github.com/QuantStack ...

**Comment by mjsteinbaugh** [comment] 2020-04-14 00:42
@naumenko-sa Sure I'll try it tomorrow morning

**Comment by mjsteinbaugh** [comment] 2020-04-14 13:42
@naumenko-sa Just tried clean installing the development version, and that's working for me on Ubuntu 18.

**Comment by naumenko-sa** [comment] 2020-04-14 15:43
thanks @mjsteinbaugh!
closing for now @gis-nlsim please feel free to re-open if you see more issues.

**Closed by naumenko-sa** 2020-04-14 15:43 UTC

**Comment by gis-nlsim** [comment] 2020-04-15 12:55
Sorry, I tried using the -u development option, but it seems to hit another error:

My command:
/mnt/projects/simngl/wgs/tools/bcbio/v1.2.2/anaconda/bin/bcbio_nextgen.py upgrade -u development --tools --data --genomes hg38

Error in gdd-run.sh as below:


URL transformed to HTTPS due to an HSTS policy
--2020-04-15 10:21:38--  https://ftp.ncbi.nih.gov/snp/archive/b153/VCF/GCF_000001405.38.gz.tbi
Resolving ftp.ncbi.nih.gov (ftp.ncbi.nih.gov)... 130.14.250.10, 2607:f220:41e:250::12
Connecting to ftp.ncbi.nih.gov (ftp.ncbi.nih.gov)|130.14.250.10|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2998587 (2.9M) [application/x-gzip]
Saving to: ‘variation/dbsnp-153-orig.vcf.gz.tbi’

variation/dbsnp-153-orig.vc 100%[==========================================>]   2.86M   244KB/s    in 13s

2020-04-15 10:21:56 (225 KB/s) - ‘variation/dbsnp-153-orig.vcf.gz.tbi’ saved [2998587/2998587]

bcftoolsbcftools: : error while loading shared librarieserror while loading shared libraries: : libopenblas.so.0libopenblas.so.0: : cannot open shared object filecannot open shared object file: : No such file or directoryNo\
such file or directory

tbx_index_build failed: variation/dbsnp-153.vcf.gz
Traceback (most recent call last):
  File "/mnt/projects/simngl/wgs/tools/bcbio/v1.2.2/anaconda/bin/bcbio_nextgen.py", line 228, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/mnt/projects/simngl/wgs/tools/bcbio/v1.2.2/anaconda/lib/python3.6/site-packages/bcbio/install.py", line 107, in upgrade_bcbio
    upgrade_bcbio_data(args, REMOTES)
  File "/mnt/projects/simngl/wgs/tools/bcbio/v1.2.2/anaconda/lib/python3.6/site-packages/bcbio/install.py", line 377, in upgrade_bcbio_data
    cbl_genomes.install_data_local(genome_opts, tooldir, data_dir, galaxy_home, tool_data_table_conf_file,
  File "/mnt/projects/simngl/wgs/tools/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 354, in install_data_local
    _prep_genomes(env, genomes, genome_indexes, ready_approaches, data_filedir)
  File "/mnt/projects/simngl/wgs/tools/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 480, in _prep_genomes
    retrieve_fn(env, manager, gid, idx)
  File "/mnt/projects/simngl/wgs/tools/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 875, in _install_with_ggd
    ggd.install_recipe(os.getcwd(), env.system_install, recipe_file, gid)
  File "/mnt/projects/simngl/wgs/tools/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/ggd.py", line 30, in install_recipe
    recipe["recipe"]["full"]["recipe_type"], system_install)
  File "/mnt/projects/simngl/wgs/tools/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/ggd.py", line 62, in _run_recipe
    subprocess.check_output(["bash", run_file])
  File "/mnt/projects/simngl/wgs/tools/bcbio/v1.2.2/anaconda/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/mnt/projects/simngl/wgs/tools/bcbio/v1.2.2/anaconda/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['bash', '/mnt/projects/simngl/wgs/tools/bcbio/v1.2.2/genomes/Hsapiens/hg38/txtmp/ggd-run.sh']' returned non-zero exit status 1.

**Comment by gis-nlsim** [comment] 2020-04-21 03:04
Greetings,

I’m still getting the ggd-run.sh error.
(I re-ran the following commands on 17th April 2020)

wget --no-check-certificate -c https://raw.githubusercontent.com/bcbio/bcbio-nextgen/master/scripts/bcbio_nextgen_install.py
python ./bcbio_nextgen_install.py /mnt/projects/simngl/wgs/tools/bcbio/v1.2.3 --tooldir=/mnt/projects/simngl/wgs/tools/bcbio/v1.2.3/tools --aligners bwa --genomes hg38 --genomes GRCh37 --genomes mm10


Writing to .
Could not read: https://gist.githubusercontent.com/matthdsm/f833aedd2d67e28013ff1d171c70f4ee/raw/442a45ed3ddc6e85c66c5e58e0fa78e16a0821c8/refseq2ucsc.tsv
[E::bcf_hdr_read] Input is not detected as bcf or vcf format
bcftools: bgzf.c:982: bgzf_read: Assertion `fp->is_write == 0' failed.
/mnt/projects/simngl/wgs/tools/bcbio/v1.2.3/genomes/Hsapiens/hg38/txtmp/ggd-run.sh: line 14: 30726 Exit 255                bcftools annotate -Ou --rename-chrs $remap_url variation/dbsnp-$build-orig.vcf.gz
     30727 Aborted                 (core dumped) | bcftools sort -m 1G -Oz -T . -o variation/dbsnp-$build.vcf.gz
tbx_index_build failed: variation/dbsnp-153.vcf.gz
Traceback (most recent call last):
  File "/mnt/projects/simngl/wgs/tools/bcbio/v1.2.3/anaconda/bin/bcbio_nextgen.py", line 228, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/mnt/projects/simngl/wgs/tools/bcbio/v1.2.3/anaconda/lib/python3.6/site-packages/bcbio/install.py", line 107, in upgrade_bcbio
    upgrade_bcbio_data(args, REMOTES)
  File "/mnt/projects/simngl/wgs/tools/bcbio/v1.2.3/anaconda/lib/python3.6/site-packages/bcbio/install.py", line 377, in upgrade_bcbio_data
    args.cores, ["ggd", "s3", "raw"])
  File "/mnt/projects/simngl/wgs/tools/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 354, in install_data_local
    _prep_genomes(env, genomes, genome_indexes, ready_approaches, data_filedir)
  File "/mnt/projects/simngl/wgs/tools/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 480, in _prep_genomes
    retrieve_fn(env, manager, gid, idx)
  File "/mnt/projects/simngl/wgs/tools/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 875, in _install_with_ggd
    ggd.install_recipe(os.getcwd(), env.system_install, recipe_file, gid)
  File "/mnt/projects/simngl/wgs/tools/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/ggd.py", line 30, in install_recipe
    recipe["recipe"]["full"]["recipe_type"], system_install)
  File "/mnt/projects/simngl/wgs/tools/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/ggd.py", line 62, in _run_recipe
    subprocess.check_output(["bash", run_file])
  File "/mnt/projects/simngl/wgs/tools/bcbio/v1.2.3/anaconda/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/mnt/projects/simngl/wgs/tools/bcbio/v1.2.3/anaconda/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['bash', '/mnt/projects/simngl/wgs/tools/bcbio/v1.2.3/genomes/Hsapiens/hg38/txtmp/ggd-run.sh']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "./bcbio_nextgen_install.py", line 315, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "./bcbio_nextgen_install.py", line 49, in main
    subprocess.check_call([bcbio, "upgrade"] + _clean_args(sys_argv, args))
  File "/mnt/projects/simngl/wgs/tools/anaconda3/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/mnt/projects/simngl/wgs/tools/bcbio/v1.2.3/anaconda/bin/bcbio_nextgen.py', 'upgrade', '--tooldir=/mnt/projects/simngl/wgs/tools/bcbio/v1.2.3/tools', '--aligners', 'b\
wa', '--genomes', 'hg38', '--genomes', 'GRCh37', '--genomes', 'mm10', '--data']' returned non-zero exit status 1.


From: SIM Ngak Leng <Sim_Ngak_Leng@gis.a-star.edu.sg>
Date: Wednesday, 15 April 2020 at 8:55 PM
To: bcbio/bcbio-nextgen <reply@reply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: Re: [bcbio/bcbio-nextgen] Scanner Error when attempting to install genomes (#3180)

Sorry, I tried using the -u development option, but it seems to hit another error:

My command:
/mnt/projects/simngl/wgs/tools/bcbio/v1.2.2/anaconda/bin/bcbio_nextgen.py upgrade -u development --tools --data --genomes hg38

Error in gdd-run.sh as below:


URL transformed to HTTPS due to an HSTS policy
--2020-04-15 10:21:38--  https://ftp.ncbi.nih.gov/snp/archive/b153/VCF/GCF_000001405.38.gz.tbi
Resolving ftp.ncbi.nih.gov (ftp.ncbi.nih.gov)... 130.14.250.10, 2607:f220:41e:250::12
Connecting to ftp.ncbi.nih.gov (ftp.ncbi.nih.gov)|130.14.250.10|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2998587 (2.9M) [application/x-gzip]
Saving to: ‘variation/dbsnp-153-orig.vcf.gz.tbi’

variation/dbsnp-153-orig.vc 100%[==========================================>]   2.86M   244KB/s    in 13s

2020-04-15 10:21:56 (225 KB/s) - ‘variation/dbsnp-153-orig.vcf.gz.tbi’ saved [2998587/2998587]

bcftoolsbcftools: : error while loading shared librarieserror while loading shared libraries: : libopenblas.so.0libopenblas.so.0: : cannot open shared object filecannot open shared object file: : No such file or directoryNo\
such file or directory

tbx_index_build failed: variation/dbsnp-153.vcf.gz
Traceback (most recent call last):
  File "/mnt/projects/simngl/wgs/tools/bcbio/v1.2.2/anaconda/bin/bcbio_nextgen.py", line 228, in <module>
    install.upgrade_bcbio(kwargs["args"])
  File "/mnt/projects/simngl/wgs/tools/bcbio/v1.2.2/anaconda/lib/python3.6/site-packages/bcbio/install.py", line 107, in upgrade_bcbio
    upgrade_bcbio_data(args, REMOTES)
  File "/mnt/projects/simngl/wgs/tools/bcbio/v1.2.2/anaconda/lib/python3.6/site-packages/bcbio/install.py", line 377, in upgrade_bcbio_data
    cbl_genomes.install_data_local(genome_opts, tooldir, data_dir, galaxy_home, tool_data_table_conf_file,
  File "/mnt/projects/simngl/wgs/tools/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 354, in install_data_local
    _prep_genomes(env, genomes, genome_indexes, ready_approaches, data_filedir)
  File "/mnt/projects/simngl/wgs/tools/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 480, in _prep_genomes
    retrieve_fn(env, manager, gid, idx)
  File "/mnt/projects/simngl/wgs/tools/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/genomes.py", line 875, in _install_with_ggd
    ggd.install_recipe(os.getcwd(), env.system_install, recipe_file, gid)
  File "/mnt/projects/simngl/wgs/tools/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/ggd.py", line 30, in install_recipe
    recipe["recipe"]["full"]["recipe_type"], system_install)
  File "/mnt/projects/simngl/wgs/tools/tmpbcbio-install/cloudbiolinux/cloudbio/biodata/ggd.py", line 62, in _run_recipe
    subprocess.check_output(["bash", run_file])
  File "/mnt/projects/simngl/wgs/tools/bcbio/v1.2.2/anaconda/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/mnt/projects/simngl/wgs/tools/bcbio/v1.2.2/anaconda/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['bash', '/mnt/projects/simngl/wgs/tools/bcbio/v1.2.2/genomes/Hsapiens/hg38/txtmp/ggd-run.sh']' returned non-zero exit status 1.

**Comment by naumenko-sa** [comment] 2020-04-25 03:41
I think here you hit the time when github was down recently.
The file is available now:
https://gist.githubusercontent.com/matthdsm/f833aedd2d67e28013ff1d171c70f4ee/raw/442a45ed3ddc6e85c66c5e58e0fa78e16a0821c8/refseq2ucsc.tsv
Please try again.
