### ISSUE TITLE
error with 1000G_omni2.5.vcf.gz.tbi

### ISSUE THREAD

**Issue by dauss75** [bcbio/bcbio-nextgen#2645] opened 2019-01-24 00:57 UTC
With ipython, I ran 17 samples with mutect2 and vardict for somatic calling and provided the 1000G_omni2.5.vcf.gz in the yaml file as:

background: /isilon/RnD/tool-data/bcbio-data/genomes/Hsapiens/GRCh37/variation/1000G_omni2.5.vcf.gz

The jobs are completed and I have final output files, but I find errors in the bcbio-nextgen.log shown below:

Traceback (most recent call last):
  File "/isilon/RnD/tool-data/bcbio-data/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 23, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/isilon/RnD/tool-data/bcbio-data/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 103, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; /isilon/RnD/tool-data/bcbio-data/anaconda/bin/tabix -f -p vcf /isilon/sjung_tmp/multi-sample-test/TMB-Dynamic_Range/322_solid_fastq/QIAseq-120518/mutect2-vardict/run/bcbiotx/tmpthKrK9/1000G_omni2.5.vcf.gz
tbx_index_build failed: /isilon/sjung_tmp/multi-sample-test/TMB-Dynamic_Range/322_solid_fastq/QIAseq-120518/mutect2-vardict/run/bcbiotx/tmpthKrK9/1000G_omni2.5.vcf.gz
' returned non-zero exit status 1

Then, I checked the files which are in place:
-rwxrwx--- 1 sequencer sequencer 52967946 Jan 23 16:21 1000G_omni2.5.vcf.gz
-rwxrwx--- 1 sequencer sequencer  1508786 Jan 23 16:21 1000G_omni2.5.vcf.gz.tbi

Any thoughts on the errors?

Also, I think 1000G_omni2.5.vcf.gz can be found in bcbio. Could you let me know how to add this in yaml instead of the way I did?

Many thanks!
Segun

**Comment by chapmanb** [comment] 2019-01-24 10:56
Segun;
Thanks much for the report and details. The traceback tells us that bcbio is trying to index the file and failing because the run user doesn't have permissions, but I'm not sure where that initiates from to help avoid doing this. Is there a longer traceback that shows us where the call come from? Alternatively, could you run with `-n 1` which might give a cleaner traceback if you're running your real analysis in parallel?

Regarding the practical issues, do you find that doing this helps with variant calling? We haven't used the omni files in this way with MuTect2 as a panel of normal; if it's helping we could certainly make it easier to specify and use. VarDict doesn't use a background panel of normals, so it won't feed into that.

Thanks for this discussion and help debugging.

**Comment by dauss75** [comment] 2019-01-24 21:25
Thanks Brad for the quick reply.

I was experimenting a bit with one sample only and then extended back to 27 samples.  One sample test went fine, but not the 27 samples.  

I first checked the permission issue in which there was no problem.   Then, I was tracking down where the error occured; however, I could not find the temp directory under bcbiotx. I was maxing out the available resources (head node is part of the compute nodes) in our cluster and was suspecting this may be due to a communication issue between the head node and compute nodes with lack of compute resources in head node.  So lowered the requested cpus numbers to 128 and it seems the errors are gone.  Still, I am not sure what was the exact problem thou.

RE the omni file with mutect2, we don't have normal samples to create a panel of normal so my workaround to make mutect work was to use the omni file as background/reference. 

Thanks again for your help.  I don't know if you want to dig a bit more to troubleshoot the exact problem. Otherwise, we can close it.

**Comment by chapmanb** [comment] 2019-01-26 16:20
Segun;
Thank you for the follow up. If you're able to reproduce at any point I'd be happy to dig more with a full traceback showing the initial source of the error. For now I'll close this but can re-open later with more details if it comes back.

Definitely let us know if omni is useful as a background for tumor-only calling. We typically use VarDict and variant prioritization for tumor only calling but would definitely have interest in knowing if a general non-related background VCF will help improve specificity.

Thanks again.

**Closed by chapmanb** 2019-01-26 16:20 UTC
