### ISSUE TITLE
Freebayes 1.0 support for gVCF

### ISSUE THREAD

**Issue by NeillGibson** [bcbio/bcbio-nextgen#1134] opened 2015-12-03 13:22 UTC
Hi, 

What are your thoughts on using the gVCF support of the new Freebayes 1.0 version in BCBio? 

I am not sure if it's stable enough yet but support for gVCF is being build into the new Freebayes releases:
https://github.com/ekg/freebayes/commits/master

I am just wondering what your thoughts are on using gVCF outputted by Freebayes in BCBio and if you did or are planning any integration tests / validations against NA12878 or other truth sets? 

Best Regards,

Neill

**Comment by chapmanb** [comment] 2015-12-03 15:48
Neill;
It would be great to support gVCF based merging for joint calling, but as you mention it's still a little early to switch over. The current version of FreeBayes has some issues with memory usage on non-gVCF output (https://github.com/ekg/freebayes/issues/225) so we've been sticking with an older version without gVCF support. 

Once that is in place we'd need to put together a gVCF joint calling approach. I'm not aware of a ready to run freely available implementation right now, but am watching the GLnexus project (https://github.com/dnanexus-rnd/GLnexus) and hoping to use it when ready.

Once those parts are in place we'd definitely look to include it, do validation testing and deprecate our recalling based joint calling approach. Sorry to not have anything immediate planned but hope this helps for future thoughts.

**Comment by NeillGibson** [comment] 2015-12-04 09:34
Hi Brad, 

Thank you for the information and you thoughts on this. We have a set of samples and are considering if it is worth waiting for Freebayes gVCF to become stable and a good gVCF merging / genotype calling solution to arise. 

Sounds like we will have another look at this in January and otherwise just go ahead with the existing joined calling approach.

**Comment by chapmanb** [comment] 2015-12-05 12:16
Neill;
Thanks for the additional details, that makes good sense. We'll definitely migrate to this approach as soon as tools are available. If GATK is an option for you, the HaplotypeCaller based gVCF calling and merging strategy works right now in bcbio. Hope this helps.

**Comment by NeillGibson** [comment] 2016-03-01 12:39
Hi @chapmanb . Is there any new information about Freebayes and gVCF merging? 

I was hoping that some progress would materialize in the last 3 month but it seems that merging of freebayes gVCF output is still some more months off?

**Comment by chapmanb** [comment] 2016-03-01 14:31
Neill;
3 months goes fast. Apologies, not much movement has happened on this. We're still watching GLnexus and it has steady development work but no ready to run releases. gVCF support in FreeBayes has stabilized so we could switch there but we were planning to do it all at one time to avoid too many sets of changes. Sorry to not have anything more definite -- this and variant graph calling with vg are the two things we're waiting patiently for.

**Comment by NeillGibson** [comment] 2016-03-02 15:14
Hi Brad. Thank you for the information. 
Good to hear that gVCF output of Freebayes has stabilized. It indeed makes sense to wait for GLNexus to also release a stable gVCF merger. Let's see what happens in the coming months.

**Comment by chapmanb** [comment] 2016-03-09 19:51
Neill;
As a small step towards the FreeBayes gVCF joint calling goal, I validated FreeBayes 1.0.2 and it looks good, so updated the version included with bcbio installs:

http://imgur.com/a/GXR5O

The latest development also includes some fixes to avoid post-filtering reference block calls (which have qualities of zero so were getting tossed out. If you add:
```
resources:
  freebayes:
    options: [--gvcf, --gvcf-chunk, '50000']
```
to the top level of a sample YAML file, you can get FreeBayes to output gVCF now. This doesn't yet have any type of downstream combining but at least gets this part of the process enabled.

**Comment by NeillGibson** [comment] 2016-03-10 18:41
Thank you brad. Now it's just waiting for a gVCF combing solution to arise.

**Comment by NeillGibson** [comment] 2016-11-21 08:58
Hi @chapmanb.   Do you know if a tool has become available for joint genotyping of Freebayes gVCF files? Or is close to becoming available?

Otherwise I am kind of missing the point of the effort that went in to having Freebayes create these gVCF files in the first place. 

I am also wondering what the difference is between the GATK gVCF and FreeBayes gVCF?
If these would be almost the same it would surely be easier to develop a common gVCF merging tool / approach.  (drop in replacement for GATK CombineGVCFs + GenotypeGVCFs)

Would there be a way to speed up the development of a Freebayes gVCF joint genotyping tool? 
I understand the Freebayes gVCF functionality was funded by an organization that wanted to see this functionality happening. So maybe the same is possible for a Freebayes  joint genotyping tool?

**Comment by chapmanb** [comment] 2016-11-21 19:31
Neill;
I believe GLnexus is getting to the point it could be incorporated and tested. Maybe @mlin can confirm or deny that. DNAnexus had been driving the gVCF adoption in FreeBayes for this reason and have been working consistently on GLnexus. GATK and FreeBayes gVCF aren't very equivalent in terms of representation and I believe it would take some work to be able to map them between each other. From my side I'm happy to starting trying to explore this as I know people have been running into the limitations of the current FreeBayes joint calling approaches. Hope this helps for context and background.

**Comment by NeillGibson** [comment] 2016-11-23 11:28
Hi Brad. Thank you very much for the background information.  We are currently running into the limits of joint calling with Freebayes for some species.  Being able to run the faster Freebayes v1.1.0 buys us some time but eventually we really need Freebayes gVCF joint calling. 

It would be very nice if @mlin could provide some sort of timeline for getting to a stable  / production release of the GLnexus.

**Comment by roryk** [comment] 2019-08-10 17:35
Closing this as the issue is pretty old-- please reopen if this is something you'd like to be able to do still.

**Closed by roryk** 2019-08-10 17:35 UTC
