### ISSUE TITLE
manta SV   bcftools view Error : subset called for sample that does not exist in header

### ISSUE THREAD

**Issue by apastore** [bcbio/bcbio-nextgen#1954] opened 2017-05-26 00:04 UTC
Hi Brad, 

I receive this error message at the end of manta SV analysis. all Tumor sample run clean, and this one is a paired normal to multiple tumor samples. Do you have any Idea on what is triggering this?

Thanks!

[2017-05-25T13:23Z] gpu-2-13.local: Run manta SV analysis
[2017-05-25T13:23Z] gpu-2-13.local: Error: subset called for sample that does not exist in header: "FFPEPOOLEDNORMAL_F". Use "--force-samples" to ignore this error.
[2017-05-25T13:23Z] gpu-2-13.local: Uncaught exception occurred
Traceback (most recent call last):
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 22, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 102, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; bcftools view -s FFPEPOOLEDNORMAL_F -O z -o /cbio/ski/abdelwao/nobackup/pastore/install/bcbio-vm/data/project/christian/YA/bcbiotx/tmpYnTlaI/somaticSV-FFPEPOOLEDNORMAL_F.vcf.gz /cbio/ski/abdelwao/nobackup/pastore/install/bcbio-vm/data/project/christian/YA/Project_4998/work/structural/AY-testly-023-T/manta/results/variants/somaticSV.vcf.gz
Error: subset called for sample that does not exist in header: "FFPEPOOLEDNORMAL_F". Use "--force-samples" to ignore this error.
' returned non-zero exit status 255
[2017-05-25T13:23Z] gpu-2-13.local: Unexpected error
Traceback (most recent call last):
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 50, in _setup_logging
    yield config
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/ipythontasks.py", line 386, in detect_sv
    return ipython.zip_args(apply(structural.detect_sv, *args))
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/__init__.py", line 191, in detect_sv
    for svdata in caller_fn(items):
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/manta.py", line 30, in run
    sample_file = _select_sample(data, variant_file, work_dir)
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/structural/manta.py", line 72, in _select_sample
    do.run(cmd.format(**locals()), "Run manta SV analysis")
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 22, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 102, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; bcftools view -s FFPEPOOLEDNORMAL_F -O z -o /cbio/ski/abdelwao/nobackup/pastore/install/bcbio-vm/data/project/christian/YA/bcbiotx/tmpYnTlaI/somaticSV-FFPEPOOLEDNORMAL_F.vcf.gz /cbio/ski/abdelwao/nobackup/pastore/install/bcbio-vm/data/project/christian/YA/Project_4998/work/structural/AY-testly-023-T/manta/results/variants/somaticSV.vcf.gz
Error: subset called for sample that does not exist in header: "FFPEPOOLEDNORMAL_F". Use "--force-samples" to ignore this error.
' returned non-zero exit status 255

**Comment by chapmanb** [comment] 2017-05-26 00:50
Sorry about the manta issues and thanks for the detailed report. What version of bcbio are you seeing this error with? There were some issues fixed for complicated tumor/normal batching cases in the 1.0.3 release which I hoped addressed these issues. Is it possible you're running with an older version? Hope this helps explain it.

**Comment by apastore** [comment] 2017-05-26 00:53
I was  on 1.0.4 and I have repudiate and still got the same error. ( all the tumor normal pair works, but the issue is on normal shared between multiples tumors samples).
Thanks for your support!


bcbio_nextgen.py --version
1.0.4a0

**Comment by chapmanb** [comment] 2017-05-26 01:44
Sorry that you're still having issues with the development version. Would you be able to share your sample YAML file (privately via e-mail is fine)? This would help identify the setup and see if I can reproduce the problem with a set of smaller test files. Thanks much for helping debug.

**Comment by apastore** [comment] 2017-05-26 01:47
Sure! thanks you so much for your help!

**Comment by apastore** [comment] 2017-05-26 02:05
I have removed manta, and I get get this error message even if the FFPEPOOLEDNORMAL_F-prioritize.tsv was generated 

[2017-05-26T01:39Z] gpu-1-15.local: Uncaught exception occurred
Traceback (most recent call last):
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 22, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/cbio/ski/abdelwao/home/pastore/nobackup/bcbio/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 102, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; { echo 'caller	sample	chrom	start	end	svtype	lof	annotation	split_read_support	paired_support_PE	paired_support_PR'; cat /cbio/ski/abdelwao/nobackup/pastore/install/bcbio-vm/data/project/christian/YA/Project_4998/work/structural/FFPEPOOLEDNORMAL_F/prioritize/FFPEPOOLEDNORMAL_F-lumpy-prioritize.tsv /cbio/ski/abdelwao/nobackup/pastore/install/bcbio-vm/data/project/christian/YA/Project_4998/work/structural/FFPEPOOLEDNORMAL_F/prioritize/FFPEPOOLEDNORMAL_F-lumpy-prioritize.tsv /cbio/ski/abdelwao/nobackup/pastore/install/bcbio-vm/data/project/christian/YA/Project_4998/work/structural/FFPEPOOLEDNORMAL_F/prioritize/FFPEPOOLEDNORMAL_F-lumpy-prioritize.tsv /cbio/ski/abdelwao/nobackup/pastore/install/bcbio-vm/data/project/christian/YA/Project_4998/work/structural/FFPEPOOLEDNORMAL_F/prioritize/FFPEPOOLEDNORMAL_F-lumpy-prioritize.tsv /cbio/ski/abdelwao/nobackup/pastore/install/bcbio-vm/data/project/christian/YA/Project_4998/work/structural/FFPEPOOLEDNORMAL_F/prioritize/FFPEPOOLEDNORMAL_F-lumpy-prioritize.tsv /cbio/ski/abdelwao/nobackup/pastore/install/bcbio-vm/data/project/christian/YA/Project_4998/work/structural/FFPEPOOLEDNORMAL_F/prioritize/FFPEPOOLEDNORMAL_F-lumpy-prioritize.tsv /cbio/ski/abdelwao/nobackup/pastore/install/bcbio-vm/data/project/christian/YA/Project_4998/work/structural/FFPEPOOLEDNORMAL_F/prioritize/FFPEPOOLEDNORMAL_F-lumpy-prioritize.tsv /cbio/ski/abdelwao/nobackup/pastore/install/bcbio-vm/data/project/christian/YA/Project_4998/work/structural/FFPEPOOLEDNORMAL_F/prioritize/FFPEPOOLEDNORMAL_F-lumpy-prioritize.tsv /cbio/ski/abdelwao/nobackup/pastore/install/bcbio-vm/data/project/christian/YA/Project_4998/work/structural/FFPEPOOLEDNORMAL_F/prioritize/FFPEPOOLEDNORMAL_F-lumpy-prioritize.tsv /cbio/ski/abdelwao/nobackup/pastore/install/bcbio-vm/data/project/christian/YA/Project_4998/work/structural/FFPEPOOLEDNORMAL_F/prioritize/FFPEPOOLEDNORMAL_F-lumpy-prioritize.tsv /cbio/ski/abdelwao/nobackup/pastore/install/bcbio-vm/data/project/christian/YA/Project_4998/work/structural/FFPEPOOLEDNORMAL_F/prioritize/FFPEPOOLEDNORMAL_F-lumpy-prioritize.tsv /cbio/ski/abdelwao/nobackup/pastore/install/bcbio-vm/data/project/christian/YA/Project_4998/work/structural/FFPEPOOLEDNORMAL_F/prioritize/FFPEPOOLEDNORMAL_F-lumpy-prioritize.tsv /cbio/ski/abdelwao/nobackup/pastore/install/bcbio-vm/data/project/christian/YA/Project_4998/work/structural/FFPEPOOLEDNORMAL_F/prioritize/FFPEPOOLEDNORMAL_F-lumpy-prioritize.tsv /cbio/ski/abdelwao/nobackup/pastore/install/bcbio-vm/data/project/christian/YA/Project_4998/work/structural/FFPEPOOLEDNORMAL_F/prioritize/FFPEPOOLEDNORMAL_F-lumpy-prioritize.tsv /cbio/ski/abdelwao/nobackup/pastore/install/bcbio-vm/data/project/christian/YA/Project_4998/work/structural/FFPEPOOLEDNORMAL_F/prioritize/FFPEPOOLEDNORMAL_F-lumpy-prioritize.tsv /cbio/ski/abdelwao/nobackup/pastore/install/bcbio-vm/data/project/christian/YA/Project_4998/work/structural/FFPEPOOLEDNORMAL_F/prioritize/FFPEPOOLEDNORMAL_F-lumpy-prioritize.tsv /cbio/ski/abdelwao/nobackup/pastore/install/bcbio-vm/data/project/christian/YA/Project_4998/work/structural/FFPEPOOLEDNORMAL_F/prioritize/FFPEPOOLEDNORMAL_F-lumpy-prioritize.tsv /cbio/ski/abdelwao/nobackup/pastore/install/bcbio-vm/data/project/christian/YA/Project_4998/work/structural/FFPEPOOLEDNORMAL_F/prioritize/FFPEPOOLEDNORMAL_F-lumpy-prioritize.tsv /cbio/ski/abdelwao/nobackup/pastore/install/bcbio-vm/data/project/christian/YA/Project_4998/work/structural/FFPEPOOLEDNORMAL_F/prioritize/FFPEPOOLEDNORMAL_F-lumpy-prioritize.tsv /cbio/ski/abdelwao/nobackup/pastore/install/bcbio-vm/data/project/christian/YA/Project_4998/work/structural/FFPEPOOLEDNORMAL_F/prioritize/FFPEPOOLEDNORMAL_F-lumpy-prioritize.tsv /cbio/ski/abdelwao/nobackup/pastore/install/bcbio-vm/data/project/christian/YA/Project_4998/work/structural/FFPEPOOLEDNORMAL_F/prioritize/FFPEPOOLEDNORMAL_F-lumpy-prioritize.tsv /cbio/ski/abdelwao/nobackup/pastore/install/bcbio-vm/data/project/christian/YA/Project_4998/work/structural/FFPEPOOLEDNORMAL_F/prioritize/FFPEPOOLEDNORMAL_F-lumpy-prioritize.tsv /cbio/ski/abdelwao/nobackup/pastore/install/bcbio-vm/data/project/christian/YA/Project_4998/work/structural/FFPEPOOLEDNORMAL_F/prioritize/FFPEPOOLEDNORMAL_F-lumpy-prioritize.tsv /cbio/ski/abdelwao/nobackup/pastore/install/bcbio-vm/data/project/christian/YA/Project_4998/work/structural/FFPEPOOLEDNORMAL_F/prioritize/FFPEPOOLEDNORMAL_F-lumpy-prioritize.tsv /cbio/ski/abdelwao/nobackup/pastore/install/bcbio-vm/data/project/christian/YA/Project_4998/work/structural/FFPEPOOLEDNORMAL_F/prioritize/FFPEPOOLEDNORMAL_F-lumpy-prioritize.tsv /cbio/ski/abdelwao/nobackup/pastore/install/bcbio-vm/data/project/christian/YA/Project_4998/work/structural/FFPEPOOLEDNORMAL_F/prioritize/FFPEPOOLEDNORMAL_F-lumpy-prioritize.tsv | sort -V -k3,3 -k4,4n; } > /cbio/ski/abdelwao/nobackup/pastore/install/bcbio-vm/data/project/christian/YA/bcbiotx/tmpfSp5FY/FFPEPOOLEDNORMAL_F-prioritize.tsv
sort: cannot create temporary file in `/scratch/8585137.hal-sched1.local': No such file or directory
cat: write error: Broken pipe
' returned non-zero exit status 2


FFPEPOOLEDNORMAL_F$ ls 
May 23 11:47 cnvkit
May 25 21:05 ..
May 25 21:39 prioritize
May 25 21:50 .
May 25 21:50 validate

**Comment by chapmanb** [comment] 2017-05-26 13:21
For the temporary directory error you're seeing, it appears as if `$TMPDIR` is set to a non-existant directory on your work machine.  sort uses that by default, which appears to trigger the issue. I pushed a fix to the latest development version to explicitly set the sort temporary directory to the current bcbio temporary directory, which I hope will resolve the issue.

**Comment by apastore** [comment] 2017-05-26 13:51
Thanks !
I am submit a job from the head node that at some point invoke bcbio run with ipyhton from this. The $TMPDIR that bcbio was trying to write was the TMPDIR of my initial job and not the one for the bcbio job itself. 

I do not know if this is due to some internal configuration of our cluster, but I see this also with other nested job script. 


Thanks!

**Comment by roryk** [comment] 2019-08-10 18:10
Thanks, looks like this is from a pretty old version of bcbio which might not have this issue anymore since we haven't seen any reports of it recently. Closing. Thanks!

**Closed by roryk** 2019-08-10 18:10 UTC
