### ISSUE TITLE
installer can run through w/o error and symlinks lead to nowhere

### ISSUE THREAD

**Issue by lento2002** [bcbio/bcbio-nextgen#2740] opened 2019-04-03 10:48 UTC
Tried the following and /usr/local symlink pointed to no actual binary in /mnt/fsx/share/bcbio.  Very confused at this point, any help greatly appreciated.

python bcbio_nextgen_install.py /mnt/fsx/share/bcbio --tooldir=/usr/local --genomes GRCh37 --aligners bwa --aligners bowtie2 

....
[root@ip-10-0-0-44 bin]# ls bcbio*
bcbio-prioritize  bcbio-variation  bcbio-variation-recall
[root@ip-10-0-0-44 bin]# 

[root@ip-10-0-0-44 bin]# pwd
/mnt/fsx/share/bcbio/anaconda/bin
[root@ip-10-0-0-44 bin]# 

[root@ip-10-0-0-44 bin]# ls -l bcbio_nextgen.py 
lrwxrwxrwx 1 root root 50 Apr  3 07:24 bcbio_nextgen.py -> /mnt/fsx/share/bcbio/anaconda/bin/bcbio_nextgen.py
[root@ip-10-0-0-44 bin]# 

[root@ip-10-0-0-44 bin]# pwd
/usr/local/bin
[root@ip-10-0-0-44 bin]#

**Comment by roryk** [comment] 2019-04-03 12:44
It looks like your installation didn't finish successfully. Do you have the log file from the installation?

**Comment by roryk** [comment] 2019-04-03 12:46
Oh I see, there is no bcbio script. You'll need to re-install bcbio with `conda install bcbio-nextgen` which will fix this. This has been happening recently due to some dependencies in bioconda, the bcbio package itself gets uninstalled during initial installation.

**Comment by chapmanb** [comment] 2019-04-03 15:56
Sorry about this issue. Rory is exactly right, this has been happening with 1.1.3 upgrades and installs, although I hope is fixed with the new 1.1.4 release which came out just after you tried your install/upgrade. Hopefully the workaround will fix it and keep things working cleanly going forward.

**Comment by rdocking** [comment] 2019-04-03 17:28
Was just about to add a similar issue. The suggested fix works for me! Saw this during an upgrade yesterday:

```
The following packages will be REMOVED:

  bcbio-nextgen-1.1.3-py27_0
```

And worked around as suggested:

```
[2019-04-03 10:16:10]{rdocking@clingen01}/projects/karsanlab/software/linux-x86_64-centos6/bcbio-stable/> data/anaconda/bin/conda install bcbio-nextgen

...

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    bcbio-nextgen-1.1.4        |           py27_0         2.1 MB  bioconda
    ------------------------------------------------------------
                                           Total:         2.1 MB

The following NEW packages will be INSTALLED:

  bcbio-nextgen      bioconda/linux-64::bcbio-nextgen-1.1.4-py27_0
```

**Comment by roryk** [comment] 2019-04-03 17:30
Great, thanks for reporting back that worked. I ran into it too when I made a fresh install.

**Comment by lento2002** [comment] 2019-04-04 00:45
Ok thanks.  Am not getting the following.  I can see the python file on the target side of the symlink atleast.  Greatly appreciate any insight here.  Thanks!

[root@ip-10-0-0-44 bin]# python bcbio_nextgen.py
Traceback (most recent call last):
  File "bcbio_nextgen.py", line 34, in <module>
    from bcbio.setpath import prepend_bcbiopath
ImportError: No module named bcbio.setpath
[root@ip-10-0-0-44 bin]#

**Comment by chapmanb** [comment] 2019-04-04 01:32
Sorry about the continued issues here. If you just run `bcbio_nextgen.py` do you still see this error? It looks like you're calling it with a potentially system `python` which might be pointed at some different python than the bcbio install, causing that error. Hope this explains what is happening and things are working a bit cleaner. We appreciate the help debugging, I know there are a lot of changes with the new release moving to python 3.

**Comment by lento2002** [comment] 2019-04-04 01:45
Not a problem, appreciate the help.  If I run just bcbio_nextgen.py . I still see the error, yes.

[root@ip-10-0-0-44 ~]# python -V
Python 2.7.5
[root@ip-10-0-0-44 ~]# bcbio_nextgen.py
Traceback (most recent call last):
  File "/usr/local/bin/bcbio_nextgen.py", line 34, in <module>
    from bcbio.setpath import prepend_bcbiopath
ModuleNotFoundError: No module named 'bcbio'
[root@ip-10-0-0-44 ~]#

**Comment by chapmanb** [comment] 2019-04-04 02:44
Thanks for confirming. I believe the issue is that it installed a 2.7 version of bcbio and we should have python3 with the new install. Could you try:
```
data/anaconda/bin/conda install -c conda-forge -c bioconda bcbio-nextgen python=3
```
to ensure you get the correct python 3 version. I hope that will get everything cleaned up so you're able to re-run upgrades, and things will now be stable with python 3 only going forward. Thank you again for the help debugging.

**Comment by lento2002** [comment] 2019-04-04 02:57
ok tried that, got perhaps closer...?
[root@ip-10-0-0-44 bin]# /mnt/fsx/share/bcbio/anaconda/bin/conda install -c conda-forge -c bioconda bcbio-nextgen python=3                                     |
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory                                            |
[y/N]:

**Comment by lento2002** [comment] 2019-04-04 04:25
ok, nevermind this ended up working in my environment.  Thanks!  Now I'll try a run hopefully w/o that sqllite issue now that /usr/local is on the headnode

[root@ip-10-0-0-44 centos]# conda install -c conda-forge -c bioconda bcbio-nextgen python=3
Collecting package metadata: done
Solving environment: done

## Package Plan ##

  environment location: /mnt/fsx/share/bcbio/anaconda

  added / updated specs:
    - bcbio-nextgen
    - python=3


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    bcbio-nextgen-1.1.4        |           py36_0         2.1 MB  bioconda
    ------------------------------------------------------------
                                           Total:         2.1 MB

The following NEW packages will be INSTALLED:

  bcbio-nextgen      bioconda/linux-64::bcbio-nextgen-1.1.4-py36_0


Proceed ([y]/n)? y


Downloading and Extracting Packages
bcbio-nextgen-1.1.4  | 2.1 MB    | ######################################################################################################################################################################## | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
[root@ip-10-0-0-44 centos]# bcbio_nextgen.py -v
1.1.4
[root@ip-10-0-0-44 centos]#

**Comment by gabeng** [comment] 2019-04-10 15:06
Brad,
just downloaded the latest docker image from quay.io bcbio-vc-1.1.5a-ba1ed4f and ran a simple command:

```
root@ip-172-31-14-246:/# bcbio_nextgen.py -v
Traceback (most recent call last):
  File "/usr/local/bin/bcbio_nextgen.py", line 34, in <module>
    from bcbio.setpath import prepend_bcbiopath
ModuleNotFoundError: No module named 'bcbio'
```
So this issue is also present in the docker image?

**Comment by chapmanb** [comment] 2019-04-11 10:04
Ben;
Apologies for the broken Docker image. I've been working on this the past couple of days and trying to fix issues with the Docker build. The underlying problem with Docker is that we first end up with a python 3.7 version of bcbio, and then subsequent installs swap over to python 3.6. This results in the scripts being in place but the code being under 3.7 and not getting found. Ideally the solver would swap the installed packages and it happens for most things but not bcbio for some reason.

I'm working right now on rebuilding with fixes for this within conda and will get a new, hopefully working, Docker image built today for testing and use. Thanks again.

**Comment by gabeng** [comment] 2019-04-11 11:22
Brad,
thanks for the heads up. I sympathize with you and hope that you can solve this quickly. Sorry that I am of no help here. Looking forward to the new image.

**Comment by chapmanb** [comment] 2019-04-11 16:44
Ben;
Thanks again for the patience. The latest bcbio images on quay.io now should have this problem fixed and work cleanly. Please let us know if you run into any problems.

**Comment by chapmanb** [comment] 2019-04-11 16:45
Ben;
Thanks again for the patience. The latest bcbio images on quay.io now should have this problem fixed and work cleanly. Please let us know if you run into any problems.

**Comment by chapmanb** [comment] 2019-04-11 16:46
Ben;
Thanks again for the patience. The latest bcbio images on quay.io now should have this problem fixed and work cleanly. Please let us know if you run into any problems.

**Closed** 2019-08-10 16:11 UTC
