### ISSUE TITLE
RNA-seq pipeline fails with BAM files as input (ValueError: Sequence and quality captions differ.)

### ISSUE THREAD

**Issue by amizeranschi** [bcbio/bcbio-nextgen#2013] opened 2017-07-20 12:31 UTC
Hello,

I used BAM files as input (created previously from Bcbio, using star as an aligner) for an RNA-seq protocol, using the following template:

details:
  - analysis: RNA-seq
    description: 'RNA-seq_BY-4742'
    metadata:
        batch:
        panel:
    genome_build: sacCer3_RNA
    resources:
        default:
            memory: 5G
            cores: 8
    jvm_opts: ["-Xms8000m", "-Xmx10000m"]
    algorithm:
        mark_duplicates: false
        variant_regions: ../config/variant_regions.bed
        variantcaller: gatk-haplotype
        quality_format: Standard
        strandedness: firststrand

I am getting the following error:

**[2017-07-20T11:40Z] multiprocessing: run_salmon_index**
[2017-07-20T11:40Z] Extracting genomic sequences of /mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio/genomes/Scerevisiae/sacCer3_RNA/rnaseq/ref-transcripts.gtf.
[2017-07-20T11:40Z] Reading the annotation file: /mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio/genomes/Scerevisiae/sacCer3_RNA/rnaseq/ref-transcripts.gtf
Traceback (most recent call last):
  File "/storage/brno3-cerit/home/amizeranschi/bcbio/anaconda/bin/bcbio_nextgen.py", line 234, in <module>
    main(**kwargs)
  File "/storage/brno3-cerit/home/amizeranschi/bcbio/anaconda/bin/bcbio_nextgen.py", line 43, in main
    run_main(**kwargs)
  File "/mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 42, in run_main
    fc_dir, run_info_yaml)
  File "/mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 86, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 255, in rnaseqpipeline
    samples = rnaseq.quantitate_expression_parallel(samples, run_parallel)
  File "/mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio/anaconda/lib/python2.7/site-packages/bcbio/pipeline/rnaseq.py", line 112, in quantitate_expression_parallel
    samples = run_parallel("run_salmon_index", [samples])
  File "/mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1)(joblib.delayed(fn)(x) for x in items):
  File "/mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 804, in __call__
    while self.dispatch_one_batch(iterator):
  File "/mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 662, in dispatch_one_batch
    self._dispatch(tasks)
  File "/mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 570, in _dispatch
    job = ImmediateComputeBatch(batch)
  File "/mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 183, in __init__
    self.results = batch()
  File "/mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 72, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 50, in wrapper
    return apply(f, *args, **kwargs)
  File "/mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 57, in run_salmon_index
    return salmon.run_salmon_index(*args)
  File "/mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio/anaconda/lib/python2.7/site-packages/bcbio/rnaseq/salmon.py", line 121, in run_salmon_index
    salmon_index(gtf_file, fasta_file, data, salmon_dir)
  File "/mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio/anaconda/lib/python2.7/site-packages/bcbio/rnaseq/salmon.py", line 140, in salmon_index
    readlength = bam.fastq.estimate_read_length(files[0])
  File "/mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio/anaconda/lib/python2.7/site-packages/bcbio/bam/fastq.py", line 250, in estimate_read_length
    read = in_handle.next()
  File "/mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio/anaconda/lib/python2.7/site-packages/Bio/SeqIO/__init__.py", line 600, in parse
    for r in i:
  File "/mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio/anaconda/lib/python2.7/site-packages/Bio/SeqIO/QualityIO.py", line 1031, in FastqPhredIterator
    for title_line, seq_string, quality_string in FastqGeneralIterator(handle):
  File "/mnt/storage-brno3-cerit/nfs4/home/amizeranschi/bcbio/anaconda/lib/python2.7/site-packages/Bio/SeqIO/QualityIO.py", line 920, in FastqGeneralIterator
    raise ValueError("Sequence and quality captions differ.")
**ValueError: Sequence and quality captions differ.**

How can I get the pipeline to run successfully using BAM files, without having to redo the alignments all over again from the original FASTQ files?

**Comment by roryk** [comment] 2017-07-20 14:42
Sorry about the problem. I think I know what is wrong, but I want to make sure. Do you think you could send me a snippet of the BAM file so I can fix this? If you do:

```bash
samtools view -h yourfile | head -5000 > yourfile.sam
```

and send that along I'll work on a fix.

**Comment by amizeranschi** [comment] 2017-07-21 10:43
OK. Here's the first 5000 lines from one of the BAM files, with a TXT extension so that I can upload it here on GitHub. 

[sample.sam.txt](https://github.com/chapmanb/bcbio-nextgen/files/1164833/sample.sam.txt)

I've had a similar problem with pre-made BAM files in the variant calling pipeline. I solved it there by asking Bcbio to fix read groups (bam_clean: fixrg) because I filtered multi-mapping and duplicate reads from the BAM files before using them in Bcbio. I did this filtering here as well so I tried adding bam_clean: fixrg to see if this helps, but it didn't. I still get the same error as before.

**Comment by roryk** [comment] 2017-07-27 17:49
Thanks-- sorry for the delay in getting to this-- I can't reproduce this problem from the top of the file, is there a way you could send the whole BAM file? Could this file have been truncated?

Something is wrong with the FASTQ file that gets generated from the original alignments-- this error is because the header on the read is different than the one in the quality string. There should be a directory in the work directory called fastq_convert, that has the FASTQ files in it. We look at the top 1000 reads of the FASTQ file to try to estimate the read length, so the top 4000 lines in the file that is failing should have an error in it.

**Comment by naumenko-sa** [comment] 2018-04-18 16:25
Hi @roryk !

I've got the same error in a similar case: running gatk-haplotype in RNA-seq analysis with bam input and no alignment (bam generated with STAR in bcbio RNA-seq). 

```
details:
- algorithm:
    aligner: false
    variantcaller: gatk-haplotype
  analysis: RNA-seq
```
The last command is 
```
gffread -g ...
```

The error reported:
```
Converting /hpf/largeprojects/ccmbio/naumenko/tools/bcbio/genomes/Hsapiens/GRCh37/rnaseq/ref-transcripts.gtf to FASTA format.
Traceback (most recent call last):
....
....
  File "/hpf/largeprojects/ccmbio/naumenko/tools/bcbio/anaconda/lib/python2.7/site-packages/Bio/SeqIO/__init__.py", line 600, in parse
    for r in i:
  File "/hpf/largeprojects/ccmbio/naumenko/tools/bcbio/anaconda/lib/python2.7/site-packages/Bio/SeqIO/QualityIO.py", line 1031, in FastqPhredIterator
    for title_line, seq_string, quality_string in FastqGeneralIterator(handle):
  File "/hpf/largeprojects/ccmbio/naumenko/tools/bcbio/anaconda/lib/python2.7/site-packages/Bio/SeqIO/QualityIO.py", line 920, in FastqGeneralIterator
    raise ValueError("Sequence and quality captions differ.")
ValueError: Sequence and quality captions differ.
```

Would it be possible to fix the problem?

Thanks!
Sergey

**Comment by roryk** [comment] 2019-08-10 15:00
Thanks, I know this wasn't fixed, but we also don't have something to check against, so closing this. We can re-open it if we run into it and actually fix it, sorry for not responding.

**Closed by roryk** 2019-08-10 15:00 UTC
