### ISSUE TITLE
Error at RNA-Seq pipeline

### ISSUE THREAD

**Issue by kokyriakidis** [bcbio/bcbio-nextgen#3377] opened 2020-11-16 20:11 UTC
Hey @roryk !

I get the following error while runnig RNA-Seq pipeline:

```

[2020-11-16T20:06Z] Resource requests: cufflinks, samtools; memory: 4.00, 4.00; cores: 28, 28
[2020-11-16T20:06Z] Configuring 1 jobs to run, using 28 cores each with 112.1g of memory reserved for each job
[2020-11-16T20:06Z] Timing: disambiguation
[2020-11-16T20:06Z] Timing: transcript assembly
[2020-11-16T20:06Z] Timing: estimate expression (threaded)
[2020-11-16T20:06Z] multiprocessing: generate_transcript_counts
[2020-11-16T20:06Z] multiprocessing: run_salmon_index
[2020-11-16T20:06Z] Transcriptome index for /data/kokyriakidis/rnaparkinson/PRJNA283498/work/inputs/transcriptome/hg38.fa detected, skipping building.
Traceback (most recent call last):
  File "/data/software/rnaseq/tools/bin/bcbio_nextgen.py", line 245, in <module>
    main(**kwargs)
  File "/data/software/rnaseq/tools/bin/bcbio_nextgen.py", line 46, in main
[2020-11-16T20:06Z] multiprocessing: run_salmon_bam
    run_main(**kwargs)
  File "/data/software/rnaseq/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 50, in run_main
    fc_dir, run_info_yaml)
  File "/data/software/rnaseq/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 91, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/data/software/rnaseq/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 257, in rnaseqpipeline
    samples = rnaseq.quantitate_expression_parallel(samples, run_parallel)
  File "/data/software/rnaseq/anaconda/lib/python3.6/site-packages/bcbio/pipeline/rnaseq.py", line 241, in quantitate_expression_parallel
    samples = run_parallel("run_salmon_bam", samples)
  File "/data/software/rnaseq/anaconda/lib/python3.6/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/data/software/rnaseq/anaconda/lib/python3.6/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1, backend="multiprocessing")(joblib.delayed(fn)(*x) for x in items):
  File "/data/software/rnaseq/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 1048, in __call__
    if self.dispatch_one_batch(iterator):
  File "/data/software/rnaseq/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 866, in dispatch_one_batch
    self._dispatch(tasks)
  File "/data/software/rnaseq/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 784, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/data/software/rnaseq/anaconda/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 208, in apply_async
    result = ImmediateResult(func)
  File "/data/software/rnaseq/anaconda/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 572, in __init__
    self.results = batch()
  File "/data/software/rnaseq/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 263, in __call__
    for func, args, kwargs in self.items]
  File "/data/software/rnaseq/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 263, in <listcomp>
    for func, args, kwargs in self.items]
  File "/data/software/rnaseq/anaconda/lib/python3.6/site-packages/bcbio/utils.py", line 55, in wrapper
    return f(*args, **kwargs)
  File "/data/software/rnaseq/anaconda/lib/python3.6/site-packages/bcbio/distributed/multitasks.py", line 76, in run_salmon_bam
    return salmon.run_salmon_bam(*args)
  File "/data/software/rnaseq/anaconda/lib/python3.6/site-packages/bcbio/rnaseq/salmon.py", line 30, in run_salmon_bam
    data = dd.update_summary_qc(data, "salmon", base=dd.get_salmon_fraglen_file(data))
  File "/data/software/rnaseq/anaconda/lib/python3.6/site-packages/bcbio/pipeline/datadict.py", line 393, in update_summary_qc
    base = tz.first(files)
  File "/data/software/rnaseq/anaconda/lib/python3.6/site-packages/toolz/itertoolz.py", line 376, in first
    return next(iter(seq))
StopIteration
root@genome-assembly-1:/data/kokyriakidis/rnaparkinson/PRJNA283498/work#
```

My config file is:

```
---
details:
  - analysis: RNA-seq
    genome_build: hg38
    algorithm:
      aligner: star
      strandedness: unstranded
      quantify_genome_alignments: true
upload:
  dir: ../final
```

bcbio version 1.2.4

The last commands from the log are:

```
[2020-11-16T19:50Z] gffread -g /data/software/rnaseq/genomes/Hsapiens/hg38/seq/hg38.fa -w /data/kokyriakidis/rnaparkinson/PRJNA283498/work/bcbiotx/tmp6ot1mf22/hg38.fa.tmp /data/software/rnaseq/genomes/Hsapiens/hg38/rnaseq/ref-transcripts.gtf
[2020-11-16T19:51Z] /data/software/rnaseq/galaxy/../anaconda/bin/salmon index --keepDuplicates -k 31 -p 28 -i /data/kokyriakidis/rnaparkinson/PRJNA283498/work/bcbiotx/tmpuuzhprs2/hg38 -t /data/kokyriakidis/rnaparkinson/PRJNA283498/work/inputs/transcriptome/hg38.fa
[2020-11-16T19:53Z] /data/software/rnaseq/galaxy/../anaconda/bin/salmon quant -l IU -p 28 -t /data/kokyriakidis/rnaparkinson/PRJNA283498/work/inputs/transcriptome/hg38.fa -o /data/kokyriakidis/rnaparkinson/PRJNA283498/work/bcbiotx/tmpsl_x3h30/C_0024 -a /data/kokyriakidis/rnaparkinson/PRJNA283498/work/align/C_0024/C_0024_star/C_0024.transcriptome.bam --numBootstraps 30
```

Any thoughts?

**Comment by kokyriakidis** [comment] 2020-11-18 08:58
It looks like it was a memory issue. I increased memory per core.

**Comment by kokyriakidis** [comment] 2020-11-18 09:30
The issue continues. i changed it to 16G and 8 cores.

```
[2020-11-18T09:29Z] [2020-11-18 11:29:07.779] [jointLog] [info] Finished Bootstrapping
[2020-11-18T09:29Z] Freeing memory used by read queue . . .
[2020-11-18T09:29Z] Joined parsing thread . . . "/data/kokyriakidis/rnaparkinson/PRJNA283498/work/align/C_0024/C_0024_star/C_0024.transcriptome.bam"
[2020-11-18T09:29Z] Closed all files . . .
[2020-11-18T09:29Z] Emptied frag queue. . .
[2020-11-18T09:29Z] Emptied Alignemnt Group Pool. .
[2020-11-18T09:29Z] Emptied Alignment Group Queue. . . done
Traceback (most recent call last):
  File "/data/software/rnaseq/tools/bin/bcbio_nextgen.py", line 245, in <module>
    main(**kwargs)
  File "/data/software/rnaseq/tools/bin/bcbio_nextgen.py", line 46, in main
    run_main(**kwargs)
  File "/data/software/rnaseq/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 50, in run_main
    fc_dir, run_info_yaml)
  File "/data/software/rnaseq/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 91, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/data/software/rnaseq/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 257, in rnaseqpipeline
    samples = rnaseq.quantitate_expression_parallel(samples, run_parallel)
  File "/data/software/rnaseq/anaconda/lib/python3.6/site-packages/bcbio/pipeline/rnaseq.py", line 241, in quantitate_expression_parallel
    samples = run_parallel("run_salmon_bam", samples)
  File "/data/software/rnaseq/anaconda/lib/python3.6/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/data/software/rnaseq/anaconda/lib/python3.6/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1, backend="multiprocessing")(joblib.delayed(fn)(*x) for x in items):
  File "/data/software/rnaseq/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 1048, in __call__
    if self.dispatch_one_batch(iterator):
  File "/data/software/rnaseq/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 866, in dispatch_one_batch
    self._dispatch(tasks)
  File "/data/software/rnaseq/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 784, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/data/software/rnaseq/anaconda/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 208, in apply_async
    result = ImmediateResult(func)
  File "/data/software/rnaseq/anaconda/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 572, in __init__
    self.results = batch()
  File "/data/software/rnaseq/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 263, in __call__
    for func, args, kwargs in self.items]
  File "/data/software/rnaseq/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 263, in <listcomp>
    for func, args, kwargs in self.items]
  File "/data/software/rnaseq/anaconda/lib/python3.6/site-packages/bcbio/utils.py", line 59, in wrapper
    return f(*args, **kwargs)
  File "/data/software/rnaseq/anaconda/lib/python3.6/site-packages/bcbio/distributed/multitasks.py", line 76, in run_salmon_bam
    return salmon.run_salmon_bam(*args)
  File "/data/software/rnaseq/anaconda/lib/python3.6/site-packages/bcbio/rnaseq/salmon.py", line 30, in run_salmon_bam
    data = dd.update_summary_qc(data, "salmon", base=dd.get_salmon_fraglen_file(data))
  File "/data/software/rnaseq/anaconda/lib/python3.6/site-packages/bcbio/pipeline/datadict.py", line 393, in update_summary_qc
    base = tz.first(files)
  File "/data/software/rnaseq/anaconda/lib/python3.6/site-packages/toolz/itertoolz.py", line 376, in first
    return next(iter(seq))
StopIteration
```

**Comment by kokyriakidis** [comment] 2020-11-18 16:24
Also the problem is not on the files. I used different dataset without luck. It has something to do with quantify_genome_alignments.

**Comment by kokyriakidis** [comment] 2020-11-20 09:50
Running the last command locally in a terminal finishes just fine:
```
Joined parsing thread . . . "/media/kokyriakidis/PRODUCTION/PARKINSON/PRJNA283498/work/align/C_0024/C_0024_star/C_0024.transcriptome.bam" 
Closed all files . . . 
Emptied frag queue. . . 
Emptied Alignemnt Group Pool. . 
Emptied Alignment Group Queue. . . done
kokyriakidis@XAROS-WORKSTATION:/media/kokyriakidis/PRODUCTION/PARKINSON/PRJNA283498/work$ 
```
So, the "StopIteration" appears when it trys to move to the next sample for some reason

**Comment by kokyriakidis** [comment] 2020-11-20 10:08
When I move the C_0024 folder from `work/bcbiotx/tmpsl_x3h30` to `work/salmon` and try to run bcbio again it doesn't even go on processing

```
2020-11-20T10:06Z] Timing: disambiguation
[2020-11-20T10:06Z] Timing: transcript assembly
[2020-11-20T10:06Z] Timing: estimate expression (threaded)
[2020-11-20T10:06Z] multiprocessing: generate_transcript_counts
[2020-11-20T10:06Z] multiprocessing: run_salmon_index
[2020-11-20T10:06Z] Transcriptome index for /media/kokyriakidis/PRODUCTION/PARKINSON/PRJNA283498/work/inputs/transcriptome/hg38.fa detected, skipping building.
[2020-11-20T10:06Z] multiprocessing: run_salmon_bam
Traceback (most recent call last):
  File "/media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda/bin/bcbio_nextgen.py", line 245, in <module>
    main(**kwargs)
  File "/media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda/bin/bcbio_nextgen.py", line 46, in main
    run_main(**kwargs)
  File "/media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 50, in run_main
    fc_dir, run_info_yaml)
  File "/media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 91, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/main.py", line 257, in rnaseqpipeline
    samples = rnaseq.quantitate_expression_parallel(samples, run_parallel)
  File "/media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/rnaseq.py", line 241, in quantitate_expression_parallel
    samples = run_parallel("run_salmon_bam", samples)
  File "/media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1, backend="multiprocessing")(joblib.delayed(fn)(*x) for x in items):
  File "/media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 1029, in __call__
    if self.dispatch_one_batch(iterator):
  File "/media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 847, in dispatch_one_batch
    self._dispatch(tasks)
  File "/media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 765, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 208, in apply_async
    result = ImmediateResult(func)
  File "/media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 572, in __init__
    self.results = batch()
  File "/media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 253, in __call__
    for func, args, kwargs in self.items]
  File "/media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/joblib/parallel.py", line 253, in <listcomp>
    for func, args, kwargs in self.items]
  File "/media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/bcbio/utils.py", line 59, in wrapper
    return f(*args, **kwargs)
  File "/media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/bcbio/distributed/multitasks.py", line 76, in run_salmon_bam
    return salmon.run_salmon_bam(*args)
  File "/media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/bcbio/rnaseq/salmon.py", line 30, in run_salmon_bam
    data = dd.update_summary_qc(data, "salmon", base=dd.get_salmon_fraglen_file(data))
  File "/media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/bcbio/pipeline/datadict.py", line 393, in update_summary_qc
    base = tz.first(files)
  File "/media/kokyriakidis/RED/BCBIO/RESOURCES/bcbio/anaconda/lib/python3.6/site-packages/toolz/itertoolz.py", line 376, in first
    return next(iter(seq))
StopIteration
kokyriakidis@XAROS-WORKSTATION:/media/kokyriakidis/PRODUCTION/PARKINSON/PRJNA283498/work$ 

```

**Comment by kokyriakidis** [comment] 2020-11-20 10:29
After the locally run salmon command I get these files inside the C_0024 folder:

1) aux_info folder
2) logs folder
3) quant.sf file
4) cmd_info.json file
AND
5) libParams folder WHICH IS EMPTY

is this something related with this change in bcbio?

https://github.com/bcbio/bcbio-nextgen/commit/f8c8f337e0ef63e88b42b03abf23987e58fdae1b#diff-b6f72e309c10b85f7264c75054758dbddc496170253a4f596760cbbcf634398a

**Comment by roryk** [comment] 2020-11-20 13:35
Hi @kokyriakidis,

Thanks, sorry for these problems and for being slow about getting back to you. I agree it's probably from this directory change, let me see if I can reproduce and fix it. Sorry for not catching this when I made the directory change.

**Comment by naumenko-sa** [comment] 2020-12-15 08:13
Hi @kokyriakidis!
We also had a stalled run with a similar issue. I've pushed a fix, please give it a try.
S.

**Comment by kokyriakidis** [comment] 2020-12-17 01:02
Hey @naumenko-sa ,

I get another error now 

```
[2020-12-17T00:56Z] tx2gene file /data/kokyriakidis/rnaparkinson/PRJNA662780/work/inputs/transcriptome/hg38-tx2gene.csv created from /data/software/rnaseq/genomes/Hsapiens/hg38/rnaseq/ref-transcripts.gtf.
[2020-12-17T00:56Z] Combining tx2gene CSV files.
[2020-12-17T00:56Z] Loading tximport.
[2020-12-17T00:56Z] ── Attaching packages ─────────────────────────────────────── tidyverse 1.3.0 ──
[2020-12-17T00:56Z] ✔ ggplot2 3.3.0     ✔ purrr   0.3.4
[2020-12-17T00:56Z] ✔ tibble  3.0.1     ✔ dplyr   0.8.5
[2020-12-17T00:56Z] ✔ tidyr   1.0.2     ✔ stringr 1.4.0
[2020-12-17T00:56Z] ✔ readr   1.3.1     ✔ forcats 0.5.0
[2020-12-17T00:56Z] ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
[2020-12-17T00:56Z] ✖ dplyr::filter() masks stats::filter()
[2020-12-17T00:56Z] ✖ dplyr::lag()    masks stats::lag()
[2020-12-17T00:56Z] Parsed with column specification:
[2020-12-17T00:56Z] cols(
[2020-12-17T00:56Z]   transcript = col_character(),
[2020-12-17T00:56Z]   gene = col_character()
[2020-12-17T00:56Z] )
[2020-12-17T00:56Z] reading in files with read_tsv
[2020-12-17T00:56Z] 1 2 3 4 5 6 7 8 9 10 11 12
[2020-12-17T00:56Z] summarizing abundance
[2020-12-17T00:56Z] summarizing counts
[2020-12-17T00:56Z] summarizing length
[2020-12-17T00:56Z] Loading SummarizedExperiment.
[2020-12-17T00:56Z] Fatal error: cannot open file '/data/software/rnaseq/anaconda/lib/python3.6/site-packages/bcbio/pipeline/../scripts/R/bcbio2se.R': No such file or directory
[2020-12-17T00:56Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/data/software/rnaseq/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 26, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/data/software/rnaseq/anaconda/lib/python3.6/site-packages/bcbio/provenance/do.py", line 106, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail; /data/software/rnaseq/anaconda/bin/Rscript --vanilla /data/software/rnaseq/anaconda/lib/python3.6/site-packages/bcbio/pipeline/../scripts/R/bcbio2se.R /data/kokyriakidis/rnaparkinson/PRJNA662780/work /data/kokyriakidis/rnaparkinson/PRJNA662780/work/bcbiotx/tmpc87mmuse/bcbio-se.rds
Fatal error: cannot open file '/data/software/rnaseq/anaconda/lib/python3.6/site-packages/bcbio/pipeline/../scripts/R/bcbio2se.R': No such file or directory
' returned non-zero exit status 2.
```

**Comment by roryk** [comment] 2020-12-17 15:16
Hi Konstantinos,

Sorry about that, I forgot to add that script to the manifest so it gets installed. I think it should get installed now if you do a `-u development` update.

**Comment by kokyriakidis** [comment] 2020-12-18 09:04
Hi @roryk

I am getting a library error now
```
Error in library(janitor) : there is no package called ‘janitor’
Execution halted
' returned non-zero exit status 1.
```

**Comment by roryk** [comment] 2020-12-18 16:51
Thanks! Sorry about that, you are right about the fix. I just added it to cloudbiolinux so it will get installed automatically.

**Comment by kokyriakidis** [comment] 2020-12-19 21:51
Hey @roryk 

I get this error:
```
Attaching package: ‘janitor’
The following objects are masked from ‘package:stats’:
    chisq.test, fisher.test
Error: '/data/kokyriakidis/rnaparkinson/PRJNA557205/work/metadata.csv' does not exist.
Execution halted
' returned non-zero exit status 1.

```
Is this the proper location of the metadata.csv file?

**Comment by naumenko-sa** [comment] 2021-01-05 05:39
Hi @kokyriakidis !

It was likely because work/metadata.csv was not generated at the time bcbio2se.R script was called.
I've pushed a fix. Please give it a try (upgrade to development) and let us know if that works for you.

SN

**Comment by naumenko-sa** [comment] 2021-02-06 05:01
Thanks everyone! It should work now. Please let us know if you still see that issue in bcbio >=1.2.6!

**Closed by naumenko-sa** 2021-02-06 05:01 UTC
