### ISSUE TITLE
smoove: command not found

### ISSUE THREAD

**Issue by ikeadeshina** [bcbio/bcbio-nextgen#2899] opened 2019-08-12 19:35 UTC
Hi, 

My svcaller run on one WGS sample was stopped with the same error as in the log below. In the process of debugging, I decided to run the Structural variant calling – whole genome NA12878 (50x) example pipeline provided on the bcbio website and got the error below. Is anyone familiar with this issue?

[Issue_Log.txt](https://github.com/bcbio/bcbio-nextgen/files/3494027/Issue_Log.txt)

**Comment by roryk** [comment] 2019-08-12 20:03
Hi @ikeadeshina,

Sorry for the problem, and thanks for opening up the issue and including the log file, that was very helpful!

The problem is this: when we call out to command line tools, we try to find the bcbio-installed tools by checking in locations where bcbio installs the tools and if we can't find the tool in those places, we default to just assuming the tool is on the user's path. But we added this behavior later on in bcbio's development, so we have missed some spots. It looks like you ran into one with `smoove` and we are just assuming it is on your PATH.  I think if you add `/mnt/data/jeremy/programs/bcbio_v2/genomes/anaconda/bin` to your PATH it should pick up `smoove` and continue. I'll also push a fix for this issue so we find the `smoove` executable properly.

**Comment by ikeadeshina** [comment] 2019-08-13 14:02
Hi @roryk, 

Thank you for your prompt response. I tried adding to my PATH as recommended but ran into the same error again. Please see the attached log. 

Looking at the `/mnt/data/jeremy/programs/bcbio_v2/genomes/anaconda/bin` directory, smoove is not there. There's smoother but no smoove. Could this be the source of the error?

[Issue_Log_2.txt](https://github.com/bcbio/bcbio-nextgen/files/3497258/Issue_Log_2.txt)

**Comment by roryk** [comment] 2019-08-13 14:09
Thanks, I see-- `smoove` is supposed to be linked there, but the link might not have worked for some reason. There is also a `/mnt/data/jeremy/programs/bcbio_v2/genomes/anaconda/anaconda/envs/python2/bin` directory-- is `smoove` there? If so, if you add that to your PATH it will work.

We had a bunch of problems with the installation last month due to some stuff shifting in `conda`, so you might be running into an issue with that.

**Comment by ikeadeshina** [comment] 2019-08-13 17:27
Thank you. That seems to have been the solution. 

Unfortunately, the run was stopped again by a similar issue. Please see the attached log, which is a result of using a similar tactic as before...I added `/mnt/data/jeremy/programs/bcbio_v2/tools/bin` to my PATH. This is where I found `run_metasv.py`. I couldn't find it in `/mnt/data/jeremy/programs/bcbio_v2/genomes/anaconda/bin/`, which is likely the reason for the error. Given that adding the correct location to my PATH did not work, what would you recommend?

**Comment by roryk** [comment] 2019-08-14 11:57
Hi @ikeadeshina,

Sorry I think the log didn't get attached. Could you attach the log? Thank you!

**Comment by ikeadeshina** [comment] 2019-08-14 14:59
Sorry about that. Please now see attached. 

[Issue_Log_4.txt](https://github.com/bcbio/bcbio-nextgen/files/3501960/Issue_Log_4.txt)

**Comment by roryk** [comment] 2019-08-14 15:04
Hi @ikeadeshina,

Thanks! This is another program that is in the python2 environment and looks like it is not getting linked, but I'm confused because it does find it, since it is looking in the full path for it.

Does `run_metasv.py` appear here? 

`/mnt/data/jeremy/programs/bcbio_v2/genomes/anaconda/anaconda/envs/python2/bin`

It looks like it is looking for it here, which should be a link to the python2 environment. Is it?

`/mnt/data/jeremy/programs/bcbio_v2/genomes/anaconda/bin/run_metasv.py`

**Comment by ikeadeshina** [comment] 2019-08-14 15:35
Hi @roryk , 

Yes, `run_metasv.py` appears in this directory: `/mnt/data/jeremy/programs/bcbio_v2/genomes/anaconda/envs/python2/bin`. And of course, this has python2. 

And to answer your second question, it looks like there's no python2 environment in `/mnt/data/jeremy/programs/bcbio_v2/genomes/anaconda/bin/` which is where the program is looking for `run_metasv.py` (See screenshot below). 
![Screen Shot 2019-08-14 at 11 27 37 AM](https://user-images.githubusercontent.com/20074316/63034051-a2ef5600-be86-11e9-840c-16b889de6229.png)

**Comment by roryk** [comment] 2019-08-14 15:48
Thanks, sorry I meant there should be a link from:

`/mnt/data/jeremy/programs/bcbio_v2/genomes/anaconda/bin/run_metasv.py`

to

`/mnt/data/jeremy/programs/bcbio_v2/genomes/anaconda/envs/python2/bin/run_metasv.py`

I'm guessing this problem should also be solvable by adding `/mnt/data/jeremy/programs/bcbio_v2/genomes/anaconda/envs/python2/bin` to your path. If you did this already, I bet the link from `/mnt/data/jeremy/programs/bcbio_v2/genomes/anaconda/bin/run_metasv.py` to `/mnt/data/jeremy/programs/bcbio_v2/genomes/anaconda/envs/python2/bin/run_metasv.py` exists, but is broken.

**Comment by ikeadeshina** [comment] 2019-08-14 16:08
Yes I added `/mnt/data/jeremy/programs/bcbio_v2/genomes/anaconda/envs/python2/bin` before realizing I've previously done so. I didn't work anyway and came up with the same error. 

I couldn't find the link from `/mnt/data/jeremy/programs/bcbio_v2/genomes/anaconda/bin/run_metasv.py` to `/mnt/data/jeremy/programs/bcbio_v2/genomes/anaconda/envs/python2/bin/run_metasv.py`

How do you recommend I move forward?

**Comment by roryk** [comment] 2019-08-14 16:15
Thanks-- I think something is messed up with your install where a bunch of these tools are not being linked to the `anaconda/bin/run_metasv.py` directory, but should be. If you set up your path like this:

`export PATH=/mnt/data/jeremy/programs/bcbio_v2/genomes/anaconda/envs/python2/bin/:/mnt/data/jeremy/programs/bcbio_v2/genomes/anaconda/bin/:${PATH}` it should look in the python2 directory first, then the normal bin directory and then on your regular PATH.

Alternatively, you might want to try re-installing bcbio to get these to be linked properly. We had some install issues last month that broke a lot of installations and yours might have been one of them. Sorry for all the problems.

**Comment by ikeadeshina** [comment] 2019-08-16 02:46
Hi @roryk , 

I did as suggested and re-installed but the problem persists. Is it possible to change the command generating the error from `/mnt/data/jeremy/programs/bcbio_v2/genomes/anaconda/bin/run_metasv.py` to `mnt/data/jeremy/programs/bcbio_v2/genomes/anaconda/envs/python2/bin/run_metasv.py`?

**Comment by roryk** [comment] 2019-08-16 14:00
Hi @ikeadeshina,

Sorry, these links should be appearing, and I'm not sure why they are. You can fix it by adding the link in manually: can you link /mnt/data/jeremy/programs/bcbio_v2/genomes/anaconda/bin/run_metasv.py  to /mnt/data/jeremy/programs/bcbio_v2/genomes/anaconda/envs/python2/bin/run_metasv.py like this:

```
ln -s /mnt/data/jeremy/programs/bcbio_v2/genomes/anaconda/envs/python2/bin/run_metasv.py /mnt/data/jeremy/programs/bcbio_v2/genomes/anaconda/bin/run_metasv.py
```

that should get it pointing to the right place.

**Comment by ikeadeshina** [comment] 2019-08-16 15:03
Hi @roryk , 

It appears that it worked to the program moved past that error and into another. Please see the attached log. 

Thank you
[Issue_Log_7.txt](https://github.com/bcbio/bcbio-nextgen/files/3510118/Issue_Log_7.txt)

**Comment by chapmanb** [comment] 2019-08-16 19:10
Sorry about all these issues and thanks for the patience debugging. The latest development has a fix for the problem you're encountering, which is due to not using the python from the isolated python2 environment when running it. If you update with `bcbio_nextgen.py upgrade -u development` and re-run, it should hopefully work correctly for you.

Practically, some of these issues are due to metasv not getting a lot of use and attention in bcbio recently. It can be useful, but can run slowly on some samples so didn't end up getting a lot of use in production because of these runtimes. For summarizing across multiple callers, we have been using `svprioritize` (https://bcbio-nextgen.readthedocs.io/en/latest/contents/configuration.html#structural-variant-calling) with files of regions to prioritize and summarize across. This might be a better direction to explore for your analyses.

Hope this all helps and gets your samples finished.

**Comment by roryk** [comment] 2019-08-21 14:58
Thanks everyone, I think this is probably solved-- please re-open if this didn't solve your problem!

**Closed by roryk** 2019-08-21 14:58 UTC
Labels: bug
