### ISSUE TITLE
Would it possible to add decoys to GRCh37 reference?

### ISSUE THREAD

**Issue by naumenko-sa** [bcbio/bcbio-nextgen#2489] opened 2018-08-17 18:53 UTC
Hello!

Thanks for the great pipeline!
I found a closed issue about decoys in the reference here https://github.com/bcbio/bcbio-nextgen/issues/1234

It is 2018, but still many projects are using grch37 reference and it is problematic to switch them to hg38.
The current reference sequence in bcbio is from 1kg project and does not have decoys and EBV:
http://www.internationalgenome.org/category/grch37/

Would it be possible to add decoy sequences to GRCh37 reference?
File sizes would not increase much: hg38 with decoy is 3112M, GRCh37 without decoy is 3007M.

Adding decoys would remove some FP rare variants, and increase trust in bcbio variant calls for people doing variant interpretation.

I could put some efforts to make it happen, if needed.

Thanks!
Sergey

**Comment by chapmanb** [comment] 2018-08-21 09:51
Sergey;
Thanks for starting this thread. Is using build 38 a solution for your needs? We can't modify the existing hg19 and GRCh37 installs at this point as that would end up breaking runs using the previous approaches since the sequencing dictionaries would be incompatible. We've held off adding decoys in build 37 to avoid this churn and also because I've seen validations where they seem to help and also seem to hurt so the improvements are not unambiguously better. The alt approach in hg38 universally improves resolution of FPs in all our validations, so we've focused instead of supporting build 38 and making it equivalent to build 37 runs.

If you absolutely need to use build 37 with decoys your best approach would be to add as a custom genome to your install:

https://bcbio-nextgen.readthedocs.io/en/latest/contents/configuration.html#adding-custom-genomes

Thanks again for this discussion.

**Comment by naumenko-sa** [comment] 2018-08-21 18:00
Hi Brad, thanks for the explanation.

Unfortunately, moving to hg38 is not an option for now for the particular project I have. My indirect and rough (max) estimate is that decoy allows to reduce FDR in SNPs for WES by 0.4%, from 0.6% to 0.2%.
The benefit is not that dramatic to put a lot of effort into decoy. Do you think that the following 2step approach will work:
1. create custom reference grch37decoy with bwa index and nothing else.
do alignment with custom genome
2. do variant calling with regular grch37 reference using noalt_calling starting with bam produced with step1. Or bcbio will complain about incompatible references in that case?

Sergey

**Comment by chapmanb** [comment] 2018-08-23 10:18
Sergey;
That approach should work, although I'd also suggest using `bam_clean: remove_extracontigs` when restarting with the decoy aligned BAM:

https://bcbio-nextgen.readthedocs.io/en/latest/contents/configuration.html#alignment

This will extract only the standard contigs and avoid any potential issues with GATK or Picard derived tools being unhappy with the reference contig differences. Thanks for coming up with a creative solution and hope this works for you.

**Comment by chapmanb** [comment] 2018-09-18 14:32
Sergey;
Apologies about the issues, we certainly don't want to lose reads here. Do you have a sense of what reads are not present from the initial input file? Do you have the same issue if you turn off realignment (`realign: false`). We're not recommending this step and I wonder if it's doing something different with the decoy sequence. If that doesn't change the outputs, you could also try without recalibration to help determine if we can isolate the step that is dropping reads. Hope this helps with debugging and please let us know what you find.

**Comment by naumenko-sa** [comment] 2018-10-23 14:14
Hi Brad!

I'm still testing where reads disappear when aligning go grch37d5.

Also found another problem: when running variant calling and annotation against grch37 using bam aligned to grch37d5 as input, I'm getting errors related to the reference name (grch37d5), neither bam_clean: remove_extracontigs, nor bam_clean: picard helps to solve it.

When using bam_clean: remove_extracontigs, error is when running manta:
```
[2018-10-19T15:14:06.169761Z] [r1a-25.cm.cluster] [204417_1] [WorkflowRunner] [ERROR] [2018-10-19T15:13:58.793153Z] [r1a-25.cm.cluster] [204417_1] [makeLocusGraph_chromId_007_8_0006] std::exception::what: Split alignment segment maps to an unknown chromosome: 'hs37d5'
[2018-10-19T15:14:06.169859Z] [r1a-25.cm.cluster] [204417_1] [WorkflowRunner] [ERROR] [2018-10-19T15:13:58.901687Z] [r1a-25.cm.cluster] [204417_1] [makeLocusGraph_chromId_017_18_0001] 	local_bam_record: E00386:198:HLNVCCCXY:5:2214:27559:64175/1 tid:pos:strand 17:11463289:+ cigar: 5S47M99S templSize: 0 sa: hs37d5,30281334,+,99S43M9S,9,1; mate_tid:pos:strand -1:35254438:-
```

When using bam_clean: picard, error with gatk PrintReads:
```
October 22, 2018 9:30:29 PM EDT] org.broadinstitute.hellbender.tools.PrintReads done. Elapsed time: 52.40 minutes.
Runtime.totalMemory()=506986496
htsjdk.samtools.SAMException: Exception when processing alignment for BAM index E00386:198:HLNVCCCXY:5:1101:10003:11013 1/2 151b aligned read.
	at htsjdk.samtools.BAMFileWriter.writeAlignment(BAMFileWriter.java:140)
	at htsjdk.samtools.SAMFileWriterImpl.addAlignment(SAMFileWriterImpl.java:199)
	at htsjdk.samtools.AsyncSAMFileWriter.synchronouslyWrite(AsyncSAMFileWriter.java:36)
	at htsjdk.samtools.AsyncSAMFileWriter.synchronouslyWrite(AsyncSAMFileWriter.java:16)
	at htsjdk.samtools.util.AbstractAsyncWriter$WriterRunnable.run(AbstractAsyncWriter.java:123)
	at java.lang.Thread.run(Thread.java:748)
Caused by: htsjdk.samtools.SAMException: Exception creating BAM index for record E00386:198:HLNVCCCXY:5:1101:10003:11013 1/2 151b aligned read.
	at htsjdk.samtools.BAMIndexer.processAlignment(BAMIndexer.java:119)
	at htsjdk.samtools.BAMFileWriter.writeAlignment(BAMFileWriter.java:137)
	... 5 more
Caused by: htsjdk.samtools.SAMException: Unexpected reference -1 when constructing index for 83 for record E00386:198:HLNVCCCXY:5:1101:10003:11013 1/2 151b aligned read.
	at htsjdk.samtools.BAMIndexer$BAMIndexBuilder.processAlignment(BAMIndexer.java:218)
	at htsjdk.samtools.BAMIndexer.processAlignment(BAMIndexer.java:117)
	... 6 more
' returned non-zero exit status 3
```
Do you have any suggestions how to debug 2-step variant calling in grch37 with decoy?

Thanks!
Sergey

**Comment by chapmanb** [comment] 2018-10-23 18:51
Sergey;
Sorry about the issues here with cleaning your decoy BAM file. It looks like the issue is that reads get pulled along from the decoy region `hs37d5` despite our attempts to remove those with `samtools view`. These look like secondary and split reads that map to both a standard contig and the decoy. Apologies, it's quite difficult to get these removals correct and it appears as if manta is especially sensitive to detecting this and failing out. Apparently the variant callers that you used were okay since it got to this point, but it's getting all the downstream tool support correct that's the issue.

Practically, the best approach at this point might be to have your decoy as a separate custom genome build rather than trying to remove the extra contigs as part of bcbio. Is that an option?

 If you want to remove these additional contigs before, you could try using VariantBam (https://github.com/walaj/VariantBam) as it has mate linking:
```
variant in.bam -L decoy_contigs.bed -o out.bam -b
```
It would be useful to know if excluding the problem reads like that and then feeding into bcbio resolves the issue.

Sorry again about all the issue and hope this helps.

**Comment by chapmanb** [comment] 2019-01-07 02:19
Sergey;
Thanks so much for following up on this with these numbers. This is really helpful for folks wanting to investigate decoy sequences on build 37. Do you have a sense for specific regions where the decoy improves calling? Since the comparison includes both decoy and recal/realignment, have you tried separating these to help determine the contribution of each component? It always starts to be a big time sink to include all these stratifications plus drilling into individual differences, but might be worthwhile if you're thinking about this switch.

More generally from a clinical perspective, is there any hope of moving to 38, or is 37 a permanent fixture? I keep hoping for 38, which solves these issues and many more, to be a viable solution.

Thank you again for all this work.

**Comment by naumenko-sa** [comment] 2019-01-10 06:10
Hi Brad!

At the same time I'm creating here an anti-pattern on how one should be doing validation: I decoupled decoy and RR, but upgraded bcbio. In the result I have gatk 4.0.12.0 and VQSR (it looks like it is again on by default, it was on in February 2018, and off during the second half of 2018?).

Anyway, the current results:

Variation|Metric|gatk4.0.7.0,  D1,HF,  decoy,RR|gatk4.0.12.0,  D1,VQSR,  decoy,  no RR|gatk4.0.7.0, D1,HF,no decoy,no RR|gatk4.0.1.2,  D2,VQSR,  no decoy,  no RR|gatk 4.0.7.0,  D2,HF,  no decoy,  noRR
---|---|---|---|---|---|---
---||1|2|3|4|5
SNPs|FDR|0.10%|0.31%|0.40%|0.73%|0.39%
SNPs|FNR|0.12%|0.06%|0.16%|0.08%|0.22%
Indels|FDR|0.99%|0.62%|1.15%|1.26%|1.58%
Indels|FNR|1.29%|5.82%|1.25%|5.85%|2.24%

To chase the decoy effect, I'm rerunning with `tools_off: vqsr`.
For now I might suggest to turn vqsr off by default: it destroys FNR indel statistics (experiments 2 and 4), moving some TP indels to lower tranches. Those who understand tranches could switch VQSR on and get some more indels. Now people who use only PASS variants by default are loosing indels.

Regarding grch38 for clinical labs. I am not even in a clinical lab, so my opinion is one of an observer from the general public. I think that technically it is totally possible to switch to grch38. But the price would be high: to do all the validations (the amount of validation I do is <5% of the clinical lab validation), to create documentation, to train genome analysts in using grch38, to transfer the internal databases of variants, to survive the transitional period when both references will be in use and mistakes might happen, to align Sanger validation of variants found with NGS. VEP, HGMD, Clinvar are supporting grch38 and mostly variants are referred as HGVS (i.e. NM_001035.2:c.3038G>A, which is reference-agnostic, https://www.ncbi.nlm.nih.gov/clinvar/variation/161381/) and journals like AJHG are enforcing usage of HGVS, but most articles in the field assume grch37 as a default (see DDD2018 Nature article, or Cummings2017MendelianRNA-seq from Broad). Given that I can foresee 5% of the problems, the transition to grch38 is not going to happen soon for many clinical labs. grch37 is _de facto_ standard, and 
I think the progress will be happening by reanalyzing unsolved cases in grch38. If that would help to solve them, it might change the status quo.

SN

**Closed** 2020-05-29 03:56 UTC
Labels: enhancement, validation
