### ISSUE TITLE
Platypus VC yields: htsjdk.tribble.TribbleException: Contig chr7 does not have a length field.

### ISSUE THREAD

**Issue by amizeranschi** [bcbio/bcbio-nextgen#2688] opened 2019-02-20 12:12 UTC
Hello, 

I'm running into an error when calling variants with Platypus, using the latest development version of bcbio_nextgen. Attached is an archive with the files required to reproduce this: [platypus-error.tar.gz](https://github.com/bcbio/bcbio-nextgen/files/2884474/platypus-error.tar.gz).

The analysis runs fine with HaplotypeCaller, Strelka2, FreeBayes and Samtools when using the same input files, both as stand-alone variant callers and also in ensemble mode. There is just one strange thing in the ensemble VCF file: the `CALLERS` values include both the names of the variant callers, and also of the joint callers, for example: `CALLERS=gatk-haplotype,strelka2,strelka2-joint,freebayes,samtools,samtools-joint` or `CALLERS=gatk-haplotype,gatk-haplotype-joint,strelka2-joint,freebayes,freebayes-joint,samtools,samtools-joint`. How can this be avoided? Would it make sense to double the value of the `ensemble: / numpass:` argument in the YAML file, because of this?

And this is the error that Platypus runs into:

```
[2019-02-20T11:14Z] GATK: GatherVcfs
[2019-02-20T11:14Z] Using GATK jar /export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/share/gatk4-4.1.0.0-0/gatk-package-4.1.0.0-local.jar
[2019-02-20T11:14Z] Running:
[2019-02-20T11:14Z]     java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -Xms454m -Xmx3181m -XX:+UseSerialGC -Djava.io.tmpdir=/export/home/ncit/external/a.mizeranschi/automated-VC-test/testingVC-merged/work/bcbiotx/tmptAzZBo -jar /export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/share/gatk4-4.1.0.0-0/gatk-package-4.1.0.0-local.jar GatherVcfs -I /export/home/ncit/external/a.mizeranschi/automated-VC-test/testingVC-merged/work/joint/platypus-joint/testingVC/testingVC-joint-files.list -O /export/home/ncit/external/a.mizeranschi/automated-VC-test/testingVC-merged/work/bcbiotx/tmpZVfkX1/testingVC-joint.vcf.gz
[2019-02-20T11:14Z] 13:14:45.631 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/share/gatk4-4.1.0.0-0/gatk-package-4.1.0.0-local.jar!/com/intel/gkl/native/libgkl_compression.so
[2019-02-20T11:14Z] [Wed Feb 20 13:14:45 EET 2019] GatherVcfs  --INPUT /export/home/ncit/external/a.mizeranschi/automated-VC-test/testingVC-merged/work/joint/platypus-joint/testingVC/testingVC-joint-files.list --OUTPUT /export/home/ncit/external/a.mizeranschi/automated-VC-test/testingVC-merged/work/bcbiotx/tmpZVfkX1/testingVC-joint.vcf.gz  --VERBOSITY INFO --QUIET false --VALIDATION_STRINGENCY STRICT --COMPRESSION_LEVEL 2 --MAX_RECORDS_IN_RAM 500000 --CREATE_INDEX true --CREATE_MD5_FILE false --GA4GH_CLIENT_SECRETS client_secrets.json --help false --version false --showHidden false --USE_JDK_DEFLATER false --USE_JDK_INFLATER false
[2019-02-20T11:14Z] INFO	2019-02-20 13:14:47	GatherVcfs	Checking inputs.
[2019-02-20T11:14Z] [Wed Feb 20 13:14:47 EET 2019] picard.vcf.GatherVcfs done. Elapsed time: 0.03 minutes.
[2019-02-20T11:14Z] Runtime.totalMemory()=460259328
[2019-02-20T11:14Z] To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
[2019-02-20T11:14Z] htsjdk.tribble.TribbleException: Contig chr7 does not have a length field.
[2019-02-20T11:14Z] 	at htsjdk.variant.vcf.VCFContigHeaderLine.getSAMSequenceRecord(VCFContigHeaderLine.java:80)
[2019-02-20T11:14Z] 	at htsjdk.variant.vcf.VCFHeader.getSequenceDictionary(VCFHeader.java:206)
[2019-02-20T11:14Z] 	at htsjdk.variant.vcf.VCFFileReader.getSequenceDictionary(VCFFileReader.java:68)
[2019-02-20T11:14Z] 	at picard.vcf.GatherVcfs.doWork(GatherVcfs.java:66)
[2019-02-20T11:14Z] 	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:295)
[2019-02-20T11:14Z] 	at org.broadinstitute.hellbender.cmdline.PicardCommandLineProgramExecutor.instanceMain(PicardCommandLineProgramExecutor.java:25)
[2019-02-20T11:14Z] 	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:162)
[2019-02-20T11:14Z] 	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:205)
[2019-02-20T11:14Z] 	at org.broadinstitute.hellbender.Main.main(Main.java:291)
[2019-02-20T11:14Z] Uncaught exception occurred
Traceback (most recent call last):
  File "/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 26, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 106, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
CalledProcessError: Command 'set -o pipefail; unset JAVA_HOME && export PATH=/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/bin:$PATH && gatk --java-options '-Xms454m -Xmx3181m -XX:+UseSerialGC -Djava.io.tmpdir=/export/home/ncit/external/a.mizeranschi/automated-VC-test/testingVC-merged/work/bcbiotx/tmptAzZBo' GatherVcfs -I /export/home/ncit/external/a.mizeranschi/automated-VC-test/testingVC-merged/work/joint/platypus-joint/testingVC/testingVC-joint-files.list -O /export/home/ncit/external/a.mizeranschi/automated-VC-test/testingVC-merged/work/bcbiotx/tmpZVfkX1/testingVC-joint.vcf.gz
Using GATK jar /export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/share/gatk4-4.1.0.0-0/gatk-package-4.1.0.0-local.jar
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -Xms454m -Xmx3181m -XX:+UseSerialGC -Djava.io.tmpdir=/export/home/ncit/external/a.mizeranschi/automated-VC-test/testingVC-merged/work/bcbiotx/tmptAzZBo -jar /export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/share/gatk4-4.1.0.0-0/gatk-package-4.1.0.0-local.jar GatherVcfs -I /export/home/ncit/external/a.mizeranschi/automated-VC-test/testingVC-merged/work/joint/platypus-joint/testingVC/testingVC-joint-files.list -O /export/home/ncit/external/a.mizeranschi/automated-VC-test/testingVC-merged/work/bcbiotx/tmpZVfkX1/testingVC-joint.vcf.gz
13:14:45.631 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/share/gatk4-4.1.0.0-0/gatk-package-4.1.0.0-local.jar!/com/intel/gkl/native/libgkl_compression.so
[Wed Feb 20 13:14:45 EET 2019] GatherVcfs  --INPUT /export/home/ncit/external/a.mizeranschi/automated-VC-test/testingVC-merged/work/joint/platypus-joint/testingVC/testingVC-joint-files.list --OUTPUT /export/home/ncit/external/a.mizeranschi/automated-VC-test/testingVC-merged/work/bcbiotx/tmpZVfkX1/testingVC-joint.vcf.gz  --VERBOSITY INFO --QUIET false --VALIDATION_STRINGENCY STRICT --COMPRESSION_LEVEL 2 --MAX_RECORDS_IN_RAM 500000 --CREATE_INDEX true --CREATE_MD5_FILE false --GA4GH_CLIENT_SECRETS client_secrets.json --help false --version false --showHidden false --USE_JDK_DEFLATER false --USE_JDK_INFLATER false
INFO	2019-02-20 13:14:47	GatherVcfs	Checking inputs.
[Wed Feb 20 13:14:47 EET 2019] picard.vcf.GatherVcfs done. Elapsed time: 0.03 minutes.
Runtime.totalMemory()=460259328
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
htsjdk.tribble.TribbleException: Contig chr7 does not have a length field.
	at htsjdk.variant.vcf.VCFContigHeaderLine.getSAMSequenceRecord(VCFContigHeaderLine.java:80)
	at htsjdk.variant.vcf.VCFHeader.getSequenceDictionary(VCFHeader.java:206)
	at htsjdk.variant.vcf.VCFFileReader.getSequenceDictionary(VCFFileReader.java:68)
	at picard.vcf.GatherVcfs.doWork(GatherVcfs.java:66)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:295)
	at org.broadinstitute.hellbender.cmdline.PicardCommandLineProgramExecutor.instanceMain(PicardCommandLineProgramExecutor.java:25)
	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:162)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:205)
	at org.broadinstitute.hellbender.Main.main(Main.java:291)
' returned non-zero exit status 3
Traceback (most recent call last):
  File "/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/tools/bin/bcbio_nextgen.py", line 238, in <module>
    main(**kwargs)
  File "/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/tools/bin/bcbio_nextgen.py", line 46, in main
    run_main(**kwargs)
  File "/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 45, in run_main
    fc_dir, run_info_yaml)
  File "/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 89, in _run_toplevel
    for xs in pipeline(config, run_info_yaml, parallel, dirs, samples):
  File "/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/lib/python2.7/site-packages/bcbio/pipeline/main.py", line 162, in variant2pipeline
    samples = joint.square_off(samples, run_parallel)
  File "/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/lib/python2.7/site-packages/bcbio/variation/joint.py", line 142, in square_off
    "vrn_file", ["region", "sam_ref", "config"])
  File "/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/split.py", line 38, in grouped_parallel_split_combine
    parallel_fn(combine_name, combine_args)
  File "/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 28, in run_parallel
    return run_multicore(fn, items, config, parallel=parallel)
  File "/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/multi.py", line 86, in run_multicore
    for data in joblib.Parallel(parallel["num_jobs"], batch_size=1, backend="multiprocessing")(joblib.delayed(fn)(*x) for x in items):
  File "/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 921, in __call__
    if self.dispatch_one_batch(iterator):
  File "/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 759, in dispatch_one_batch
    self._dispatch(tasks)
  File "/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 716, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/lib/python2.7/site-packages/joblib/_parallel_backends.py", line 182, in apply_async
    result = ImmediateResult(func)
  File "/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/lib/python2.7/site-packages/joblib/_parallel_backends.py", line 549, in __init__
    self.results = batch()
  File "/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/lib/python2.7/site-packages/joblib/parallel.py", line 225, in __call__
    for func, args, kwargs in self.items]
  File "/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/lib/python2.7/site-packages/bcbio/utils.py", line 55, in wrapper
    return f(*args, **kwargs)
  File "/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/lib/python2.7/site-packages/bcbio/distributed/multitasks.py", line 292, in concat_variant_files
    return vcfutils.concat_variant_files(*args)
  File "/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/lib/python2.7/site-packages/bcbio/variation/vcfutils.py", line 371, in concat_variant_files
    out_file = _run_concat_variant_files_gatk4(input_file_list, out_file, config)
  File "/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/lib/python2.7/site-packages/bcbio/variation/vcfutils.py", line 394, in _run_concat_variant_files_gatk4
    broad_runner.run_gatk(params)
  File "/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/lib/python2.7/site-packages/bcbio/broad/__init__.py", line 365, in run_gatk
    log_error=log_error)
  File "/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 26, in run
    _do_run(cmd, checks, log_stdout, env=env)
  File "/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/lib/python2.7/site-packages/bcbio/provenance/do.py", line 106, in _do_run
    raise subprocess.CalledProcessError(exitcode, error_msg)
subprocess.CalledProcessError: Command 'set -o pipefail; unset JAVA_HOME && export PATH=/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/bin:$PATH && gatk --java-options '-Xms454m -Xmx3181m -XX:+UseSerialGC -Djava.io.tmpdir=/export/home/ncit/external/a.mizeranschi/automated-VC-test/testingVC-merged/work/bcbiotx/tmptAzZBo' GatherVcfs -I /export/home/ncit/external/a.mizeranschi/automated-VC-test/testingVC-merged/work/joint/platypus-joint/testingVC/testingVC-joint-files.list -O /export/home/ncit/external/a.mizeranschi/automated-VC-test/testingVC-merged/work/bcbiotx/tmpZVfkX1/testingVC-joint.vcf.gz
Using GATK jar /export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/share/gatk4-4.1.0.0-0/gatk-package-4.1.0.0-local.jar
Running:
    java -Dsamjdk.use_async_io_read_samtools=false -Dsamjdk.use_async_io_write_samtools=true -Dsamjdk.use_async_io_write_tribble=false -Dsamjdk.compression_level=2 -Xms454m -Xmx3181m -XX:+UseSerialGC -Djava.io.tmpdir=/export/home/ncit/external/a.mizeranschi/automated-VC-test/testingVC-merged/work/bcbiotx/tmptAzZBo -jar /export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/share/gatk4-4.1.0.0-0/gatk-package-4.1.0.0-local.jar GatherVcfs -I /export/home/ncit/external/a.mizeranschi/automated-VC-test/testingVC-merged/work/joint/platypus-joint/testingVC/testingVC-joint-files.list -O /export/home/ncit/external/a.mizeranschi/automated-VC-test/testingVC-merged/work/bcbiotx/tmpZVfkX1/testingVC-joint.vcf.gz
13:14:45.631 INFO  NativeLibraryLoader - Loading libgkl_compression.so from jar:file:/export/home/ncit/external/a.mizeranschi/bcbio_nextgen/anaconda/share/gatk4-4.1.0.0-0/gatk-package-4.1.0.0-local.jar!/com/intel/gkl/native/libgkl_compression.so
[Wed Feb 20 13:14:45 EET 2019] GatherVcfs  --INPUT /export/home/ncit/external/a.mizeranschi/automated-VC-test/testingVC-merged/work/joint/platypus-joint/testingVC/testingVC-joint-files.list --OUTPUT /export/home/ncit/external/a.mizeranschi/automated-VC-test/testingVC-merged/work/bcbiotx/tmpZVfkX1/testingVC-joint.vcf.gz  --VERBOSITY INFO --QUIET false --VALIDATION_STRINGENCY STRICT --COMPRESSION_LEVEL 2 --MAX_RECORDS_IN_RAM 500000 --CREATE_INDEX true --CREATE_MD5_FILE false --GA4GH_CLIENT_SECRETS client_secrets.json --help false --version false --showHidden false --USE_JDK_DEFLATER false --USE_JDK_INFLATER false
INFO	2019-02-20 13:14:47	GatherVcfs	Checking inputs.
[Wed Feb 20 13:14:47 EET 2019] picard.vcf.GatherVcfs done. Elapsed time: 0.03 minutes.
Runtime.totalMemory()=460259328
To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
htsjdk.tribble.TribbleException: Contig chr7 does not have a length field.
	at htsjdk.variant.vcf.VCFContigHeaderLine.getSAMSequenceRecord(VCFContigHeaderLine.java:80)
	at htsjdk.variant.vcf.VCFHeader.getSequenceDictionary(VCFHeader.java:206)
	at htsjdk.variant.vcf.VCFFileReader.getSequenceDictionary(VCFFileReader.java:68)
	at picard.vcf.GatherVcfs.doWork(GatherVcfs.java:66)
	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:295)
	at org.broadinstitute.hellbender.cmdline.PicardCommandLineProgramExecutor.instanceMain(PicardCommandLineProgramExecutor.java:25)
	at org.broadinstitute.hellbender.Main.runCommandLineProgram(Main.java:162)
	at org.broadinstitute.hellbender.Main.mainEntry(Main.java:205)
	at org.broadinstitute.hellbender.Main.main(Main.java:291)
' returned non-zero exit status 3
```

**Comment by amizeranschi** [comment] 2019-02-20 12:34
And regarding the issue with the VCF flag `CALLERS` mentioned above, why does it sometimes include a variant caller, but not the associated joint caller as well (e.g. freebayes but no freebayes-joint)?

**Comment by chapmanb** [comment] 2019-02-21 10:59
Thanks much for the report and sorry about the issues. Would you be able to share your sample YAML file? I'm not able to replicate this with small test datasets using Platypus. We had a fix for this problem put in place as of bcbio 1.0.5:

https://github.com/bcbio/bcbio-nextgen/commit/da21d30a2b43de5939819d5acd0568474978ac8d#diff-5f7ccb9c81b80e2e2bcafab578536d95

Is is possible you have an older version of bcbio?

Practically, we haven't worked on platypus joint calling in quite a while so I'm not sure if it's the best approach for your data. As mentioned in #2689, we'd currently recommend using GATK4 for joint calling which will hopefully be much more performant and provide good results for larger population calls.

Hope this helps and thanks for the help debugging.

**Comment by amizeranschi** [comment] 2019-02-21 11:13
I'm pretty sure I have the latest (development) version of bcbio, freshly installed two days ago. The sample YAML file and other input files (incl. a variant_regions file) is in the archive I linked earlier: https://github.com/bcbio/bcbio-nextgen/files/2884474/platypus-error.tar.gz

Thanks a lot for your help with this.

**Comment by amizeranschi** [comment] 2019-02-22 09:56
Just in case something strange happened while I installing, I checked the bcbio version and it appears to be the latest one:

```
bcbio_conda list | grep bcbio-nextgen
bcbio-nextgen             1.1.4a0                  pypi_0    pypi
```

**Comment by chapmanb** [comment] 2019-02-22 10:48
Thanks for following up and apologies for missing the configuration input earlier. I tracked down the issue and the problem is that the recalling doesn't also add a correct contig header, and when bcftools merges the existing calls (with a correct header) and the new calls (without contig headers) it creates a bare contig line for chr7 without length. To work around this issue, I pushed a new version of bcbio.variation.recall that will do this correctly for platypus.

I'll update the bioconda packages to use this and follow up here when it's all in place to retry. Thanks again for the report and patience debugging.

**Comment by amizeranschi** [comment] 2019-02-22 13:12
Alright, thanks a lot for looking into this issue. Will update and test again after your notice.

**Closed** 2019-02-23 12:59 UTC

**Comment by chapmanb** [comment] 2019-02-23 13:26
Thanks much for your patience. If you update with `bcbio_nextgen.py upgrade --tools` it will get bcbio-variation-recall 0.2.4 which has a fix for this. You can continue with your previous run, but will need to remove the existing `joint` directories with `platypus-joint` so it can recall using the fixed approach with headers. Hope this gets it working cleanly for you.

**Comment by amizeranschi** [comment] 2019-02-23 17:15
OK, thanks a lot for looking into this. After upgrading, using
```
variantcaller:
    - gatk-haplotype
    - freebayes
    - strelka2
    - platypus
    - samtools
```
with
```
variantcaller: [gatk-haplotype, freebayes, strelka2, platypus, samtools]
```
and
```
ensemble:
        numpass: 3
```

yields
```
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	HG00096	HG00097
chr7	141972804	rs10246939	T	C	268.20	PASS	AC=3;AF=0.75;AN=4;BaseQRankSum=-0.871;CALLERS=gatk-haplotype,freebayes,platypus,samtools,strelka2;ClippingRankSum=-0.016;DP=15;ExcessHet=3.0103;FS=2.522;MLEAC=2;MLEAF=0.5;MMQ=60,60;MQ=60;MQ0=0;MQRankSum=0;QD=17.88;ReadPosRankSum=-2.032;SOR=1.27	GT:AD:DP:GQ:PL	1/1:0,2:2:6:64,6,0	0/1:6,7:13:99:217,0,188
chr7	141972905	rs1726866	G	A	203	PASS	AC=1;AF=0.25;AN=4;BaseQRankSum=-0.353;CALLERS=gatk-haplotype,freebayes,platypus,samtools,strelka2;ClippingRankSum=1.568;DP=21;ExcessHet=3.0103;FS=2.236;MLEAC=1;MLEAF=0.25;MMQ=60,60;MQ=60;MQ0=0;MQRankSum=0;QD=11.94;ReadPosRankSum=-0.273;SOR=0.233	GT:AD:DP:GQ:PL	0/0:4,0:4:12:0,12,193	0/1:11,6:17:99:211,0,428
chr7	141973545	rs713598	C	G	281	PASS	AC=3;AF=0.75;AN=4;BaseQRankSum=-0.09;CALLERS=gatk-haplotype,freebayes,platypus,samtools,strelka2;ClippingRankSum=-0.795;DP=18;ExcessHet=3.0103;FS=0;MLEAC=3;MLEAF=0.75;MMQ=60,60;MQ=60;MQ0=0;MQRankSum=0;QD=15.61;ReadPosRankSum=0.579;SOR=0.693	GT:AD:DP:GQ:PL	1/1:0,4:4:12:171,12,0	0/1:10,4:14:99:124,0,396
```

Thanks a  lot for looking into this!

**Comment by chapmanb** [comment] 2019-02-24 11:13
Glad it's now running cleanly for you with the update. What issue are you worried about with the ensemble output you posted?

**Comment by amizeranschi** [comment] 2019-02-24 12:23
There's no issue with the output I posted, it's exactly what I had expected. Sorry for the confusion and thanks again for your help.
