### ISSUE TITLE
vcfanno and gemini don't work in RNA-seq analysis?

### ISSUE THREAD

**Issue by naumenko-sa** [bcbio/bcbio-nextgen#2511] opened 2018-09-13 16:21 UTC
Hello, bcbio developers and users!

Thanks for the great pipeline!
I've read in the history that it is now possible to use vcfanno in RNA-seq analysis.

When trying this:
```
details:
- algorithm:
    aligner: star
    tools_off:
    - gatk4
    tools_on:
    - bcbiornaseq
    - gemini
    variantcaller: gatk-haplotype
    vcfanno:
    - /home/naumenko/cre/cre.vcfanno.conf
  analysis: RNA-seq
  description: 181_121141J
  files:
  - /hpf/largeprojects/ccmbio/amahalanabis/181/input/181_121141J_1.fq.gz
  - /hpf/largeprojects/ccmbio/amahalanabis/181/input/181_121141J_2.fq.gz
  genome_build: GRCh37
  metadata:
    batch: 181
fc_name: '181'
resources:
  default:
    cores: 2
    jvm_opts:
    - -Xms750m
    - -Xmx7000m
    memory: 15G
upload:
  dir: ../final
```

vcf file is not annotated and there is no gemini database.

Should I specify parameters differently in RNA-seq analysis, or this functionality is not available in RNA-seq?

Thanks!
Sergey

**Comment by matthdsm** [comment] 2018-09-14 10:39
Hi Brad,

I'm having the same issue, but with the standard pipeline, annotations seem to be okay, but no gemini db is created.

Cheers
M

**Comment by chapmanb** [comment] 2018-09-14 17:14
Sergey -- thanks much for the report. bcbio doesn't currently try to create gemini databases for RNA-seq variant call pipelines, so this is not yet supported. However, it should run vcfanno with your custom input configuration (`/home/naumenko/cre/cre.vcfanno.conf`). When you specify your own vcfanno this overrides the defaults which include a gemini and rnaseq editing annotation: https://github.com/bcbio/bcbio-nextgen/blob/8436b2e6cdb143ef98849e33c24dffb9c17e57da/bcbio/variation/vcfanno.py#L89

Does this running of only your input configuration match what you're seeing? More generally, would you prefer different behavior here when you specify your own vcfanno inputs? Also, would it be possible to move the custom annotations you're doing into something bcbio could support? We're going to have problems supporting arbitrary vcfanno inputs and files with CWL as we move towards that and trying to think how to phase this support out.

Matthias, would it be possible to see your configuration so we can figure out what is going on? `tools_on: [gemini]` should build gemini databases and you should be running vcfanno either way, so I'm not sure how to reproduce/debug.

Thanks much.

**Comment by naumenko-sa** [comment] 2018-09-14 17:56
Hi Brad!

Thanks for the quick response!

I see, bcbio was trying to find this config in 
```.../bcbio/genomes/Hsapiens/GRCh37/config/vcfanno```

My custom config file is not using any annotation sources outside of bcbio - just gnomad_exome, and gnomad_genome provided by bcbio. So I can put my config in the proper folder, and it should work.

I'd propose the flexible approach, if possible: to allow users having their custom vcfanno configs (because it is easier to store them in the repo rather than in bcbio folder), but those config should use only bcbio annotation sources - there is more than enough data for any annotation.

Are vep annotation also available in RNA-seq?

Sergey

**Comment by chapmanb** [comment] 2018-09-14 18:34
Sergey;
Thanks for following up on this. What do you think about including your custom annotation file as a standard choice distributed with bcbio? Then it'll be installed and managed within the standard vcfanno config directory. It should be able to find your conf file outside of this, but longer term in CWL we won't be able to support these custom inputs so I'd like to build up a set of useful community annotations and have them supported in bcbio.

We also haven't added effects prediction with snpEff into RNA-seq outside of CWL runs, as the idea was to migrate this there. Is effects prediction useful right now in standard pipelines?

Thanks again for all the discussion and feedback.

**Comment by matthdsm** [comment] 2018-09-17 05:48
Hi Brad,

I'm using the following config:
```
#bcbio-nextgen v1.1.0a
---
#include an experiment name here
fc_name: v1.1.0a_test
upload:
  dir: ../final
globals:
  analysis_regions: /ref/variant_regions/RefSeqExomeAndPanels_20171003.bed
  coverage_regions: /ref/variant_regions/RefSeqExomeAndPanels_20171003.bed
resources:
  tmp:
    dir: /tmp/bcbio
details:
  - analysis: variant2
    genome_build: hg38
    description: NA12878K12
    algorithm:
      aligner: bwa
      save_diskspace: true
      coverage_interval: regional
      coverage: coverage_regions
      mark_duplicates: true
      recalibrate: false
      realign: false
      variantcaller: gatk-haplotype
      variant_regions: analysis_regions
      jointcaller: gatk-haplotype-joint
      effects: vep
      effects_transcripts: all
      vcfanno: [eog,dbscsnv,dbnsfp]
      validate: giab-NA12878/truth_small_variants.vcf.gz
      validate_regions: /ref/NA12878_truth_regions.bed
      tools_on:
        - vep_splicesite_annotations
        - gemini
        - coverage_perbase
    files: [../input/NA12878K12_R1.fastq.gz,../input/NA12878K12_R2.fastq.gz]
```

I suppose the config is allright? All the annotations seem to be in place, but no db's are created.

Thanks for the help, and Sergey, sorry for hijacking your issue ;) 
Cheers
M

**Comment by chapmanb** [comment] 2018-09-17 10:18
Matthias;
Thanks for passing along the configuration. I believe the issue is that you have a custom `vcfanno` that does not include `gemini`, so it doesn't annotate with gemini and thus wouldn't build the database. I pushed a fix that checks for this case and adds the `gemini` request to `vcfanno` if it's missing, which seems to resolve the problem on my local tests. Manually adding it to your configuration should work as well. Hope this helps.

**Comment by matthdsm** [comment] 2018-09-17 10:29
Hi Brad,

Is this something that's changed recently? We've been using the same config since v1.0.5 (without the call to `gemini` in the vcfanno config, and I've never had this issue before.

To be clear, we don't want/need the annotations associated with the `gemini` config (since those are all included in the VEP annotations), we just need the db's.

Thanks for the fix, I'll give it a try right away.
Cheers
M

**Comment by chapmanb** [comment] 2018-09-17 13:58
Matthias;
We did completely rework gemini and vcfanno for this upcoming release so that might have triggered the change. Sorry about the issues but hopefully the updated version will do the right thing now. I thought more about this and after considering your and Sergey's issues made the defaults happen even if a custom vcfanno is there. The gemini usage has been simplified to use less input files (even for build 37) and so hopefully is useful to you for your created databases. Please let me know if you have any issues with the updates.

**Comment by naumenko-sa** [comment] 2018-09-17 15:00
Hi Matthias - you are welcome, it is a related issue!

Brad:
I'm absolutely fine to include my config in bcbio defaults:
https://github.com/naumenko-sa/cre/blob/master/cre.vcfanno.conf
A couple of potential issues: 
- I have a variation symlink in the gemini directory referencing grch37/variation, it fixed a bug in one of previous releases, not needed now.
- I normalized gnomad_genome and I am using it, otherwise some variants are not assigned with correct population frequencies.

Should I just submit a merge request?

Regarding VEP annotation for RNA-seq. Yes, ideally, I'd need VEP and vcfanno for RNA-seq variant calling - the same as for WES/WGS small variants. But that is not a big issue - I'm using vrn option to annotate variants after RNA-seq pipeline finishes.

Sergey

**Comment by matthdsm** [comment] 2018-09-18 11:16
Hi Brad,

I've updated bcbio to the latest commit, but still no dice. I've got an attempt to create a db, but vcf2db seems to stuble over some values.

I've added the entire log dir [here](https://github.com/bcbio/bcbio-nextgen/files/2392388/log.tar.gz)
 for completeness.

Cheers
M

**Comment by chapmanb** [comment] 2018-09-21 18:39
Sergey -- thanks for the link to this. I can work to incorporate but this will take a few steps on my end: as I'm still not sure how to handle the gnomad normalization. As you mention in #2503 it would be best to pre-normalize these, but then we need to provide them all as downloads which adds a lot to our download costs since they're large files. Do you feel like the entire gnomad genome files provide a lot of value over ExAC or potentially a subset of the full gnomad genome to part of the genome? I'm trying to find a way to usefully provide this without the large download and preparation costs.

Thanks again for sharing this.

**Comment by chapmanb** [comment] 2018-09-21 18:48
Matthias;
Thanks much for sharing the log files for GEMINI. It looks like bcbio is running vcf2db but it's complaining about one of the inputs, causing it to fail:
```
sqlalchemy.exc.StatementError: (exceptions.ValueError) could not convert string to float
```
You have a lot of annotations being loaded here so it's not easy for me to track down from just the error message which is triggering this but I see a few potential causes where we have float scores represented as comma separated strings:
```
FATHMM_score 0.05,0.05,1.34
mutationtaster_score 0.994711,0.994711,0.965808
provean_score -2.09,-2.03,-2.68
```
I'm not 100% sure where these come from -- maybe VEP or dbNSFP? If you look at your input VCF, is it possible to identify if some of these are labeled as single floats but end up as these comma separated strings?

Sorry to not be able to identify the issue for definite but hope this helps in tracking it down.

**Comment by matthdsm** [comment] 2018-09-24 08:58
Hi Brad,

The issue seems to come from `vcf2db` as you said. All fields from dbNSFP are annotated as `string` types, but `vcf2db` tries to make floats out of them, essentially ignoring the VCF spec. There are a bunch of fields in dbNSFP that have multiple values, so this does pose an issue. Strange thing is that this hasn't been an issue in the past.

Cheers 
M

**Comment by naumenko-sa** [comment] 2018-09-24 15:03
Hi Brad!

What about just to replace existing gnomad_genome.vcf.gz with the normalized one? Same size. I generated it with vt normalize command. It took 5 hours. I can upload my gnomad_genome.normalized.vcf.gz somewhere to save you some time.

Yes, I think it is hard to overestimate the value of gnomad_genome. It is much better than 1kg for variant prioritization outside exonic regions. Gnomad_exome provides only exonic regions, which is a bit misleading, because people think that 'gnomad means that variants from 15k genomes'. So gnomad_genome is needed for WGS, RNAseq, and even some good coverage WES prioritization.

No sure that subsetting gnomad genomes would be better: 1) excluding exonic regions would not give much economy of space; 2) after any subsetting gnomad frequencies will be different from gnomad website.

Sergey

**Comment by roryk** [comment] 2019-08-10 18:37
Thanks-- @naumenko-sa does bcbio still not make GEMINI databases from RNA-seq analyses? If so that would be a good thing for us to fix.

**Closed** 2020-05-29 04:47 UTC
Labels: bug
